Japanese Morphological Analyzer: MeCab::scoped_array< T > Class Template Reference
MeCab::scoped_array< T > Class Template Reference
#include <scoped_ptr.h>
Public Types
typedef T element_type
Public Member Functions
scoped_array (T *p=0)
virtual ~scoped_array ()
void reset (T *p=0)
T & operator* () const
T * operator-> () const
T * get () const
T & operator[] (size_t i) const
Detailed Description
template<class T>
class MeCab::scoped_array< T >
Definition at line 35 of file scoped_ptr.h.
Member Typedef Documentation
template<class T> typedef T MeCab::scoped_array< T >::element_type
Definition at line 43 of file scoped_ptr.h.
Constructor & Destructor Documentation
template<class T> MeCab::scoped_array< T >::scoped_array (T * p = 0) [inline, explicit]
Definition at line 44 of file scoped_ptr.h.
template<class T> virtual MeCab::scoped_array< T >::~scoped_array () [inline, virtual]
Definition at line 45 of file scoped_ptr.h.
Member Function Documentation
template<class T> T* MeCab::scoped_array< T >::get () const [inline]
Definition at line 52 of file scoped_ptr.h.
Referenced by MeCab::Iconv::convert(), MeCab::TokenizerImpl< N, P >::getBOSNode(), MeCab::TokenizerImpl< N, P >::lookup(), mecab_do(), MeCab::DecoderLearnerTagger::parse(), MeCab::EncoderLearnerTagger::read(), and MeCab::Writer::writeNode().
template<class T> T& MeCab::scoped_array< T >::operator* () const [inline]
Definition at line 50 of file scoped_ptr.h.
template<class T> T* MeCab::scoped_array< T >::operator-> () const [inline]
Definition at line 51 of file scoped_ptr.h.
template<class T> T& MeCab::scoped_array< T >::operator[] (size_t i) const [inline]
Definition at line 53 of file scoped_ptr.h.
template<class T> void MeCab::scoped_array< T >::reset (T * p = 0) [inline]
Definition at line 46 of file scoped_ptr.h.
Referenced by MeCab::TokenizerImpl< N, P >::open(), and MeCab::DecoderLearnerTagger::parse().
The documentation for this class was generated from the following file:
source/libmecab/scoped_ptr.h