Japanese Morphological Analyzer: MeCab::thread Class Reference
MeCab::thread Class Reference
#include <thread.h>
Public Member Functions
virtual void run ()
void start ()
void join ()
virtual ~thread ()
Static Public Member Functions
static void * wrapper (void *ptr)
Detailed Description
Definition at line 38 of file thread.h.
Constructor & Destructor Documentation
virtual MeCab::thread::~thread () [inline, virtual]
Definition at line 81 of file thread.h.
Member Function Documentation
void MeCab::thread::join () [inline]
Definition at line 70 of file thread.h.
virtual void MeCab::thread::run () [inline, virtual]
Definition at line 55 of file thread.h.
Referenced by wrapper().
void MeCab::thread::start () [inline]
Definition at line 57 of file thread.h.
References BEGINTHREAD, and wrapper().
static void* MeCab::thread::wrapper (void * ptr) [inline, static]
Definition at line 49 of file thread.h.
References run().
Referenced by start().
The documentation for this class was generated from the following file:
source/libmecab/thread.h