Japanese Morphological Analyzer: MeCab::scoped_ptr< T > Class Template Reference
MeCab::scoped_ptr< T > Class Template Reference
#include <scoped_ptr.h>
Public Types
typedef T element_type
Public Member Functions
scoped_ptr (T *p=0)
virtual ~scoped_ptr ()
void reset (T *p=0)
T & operator* () const
T * operator-> () const
T * get () const
Detailed Description
template<class T>
class MeCab::scoped_ptr< T >
Definition at line 15 of file scoped_ptr.h.
Member Typedef Documentation
template<class T> typedef T MeCab::scoped_ptr< T >::element_type
Definition at line 23 of file scoped_ptr.h.
Constructor & Destructor Documentation
template<class T> MeCab::scoped_ptr< T >::scoped_ptr (T * p = 0) [inline, explicit]
Definition at line 24 of file scoped_ptr.h.
template<class T> virtual MeCab::scoped_ptr< T >::~scoped_ptr () [inline, virtual]
Definition at line 25 of file scoped_ptr.h.
Member Function Documentation
template<class T> T* MeCab::scoped_ptr< T >::get () const [inline]
Definition at line 32 of file scoped_ptr.h.
Referenced by MeCab::Viterbi::clear(), MeCab::Dictionary::compile(), MeCab::TaggerImpl::nextNode(), MeCab::DecoderLearnerTagger::open(), MeCab::TaggerImpl::parseNBestInit(), and MeCab::Viterbi::set_lattice_level().
template<class T> T& MeCab::scoped_ptr< T >::operator* () const [inline]
Definition at line 30 of file scoped_ptr.h.
template<class T> T* MeCab::scoped_ptr< T >::operator-> () const [inline]
Definition at line 31 of file scoped_ptr.h.
template<class T> void MeCab::scoped_ptr< T >::reset (T * p = 0) [inline]
Definition at line 26 of file scoped_ptr.h.
Referenced by MeCab::Dictionary::compile(), MeCab::TaggerImpl::nextNode(), MeCab::Viterbi::open(), MeCab::DecoderLearnerTagger::open(), MeCab::TaggerImpl::parseNBestInit(), and MeCab::Viterbi::set_lattice_level().
The documentation for this class was generated from the following file:
source/libmecab/scoped_ptr.h