Japanese Morphological Analyzer: jma::JMA_CType_UTF8 Class Reference
jma::JMA_CType_UTF8 Class Reference
JMA_CType_UTF8 gives the character type information in UTF-8 encoding.
#include <jma_ctype_utf8.h>
Public Member Functions
virtual unsigned int getByteCount (const char *p) const
Get the byte count of the first character pointed by p, which character is in a specific encoding.
virtual bool isSpace (const char *p) const
Check whether is white-space character.
virtual string replaceSpaces (const char *str, char replacement)
Replace space characters with replacement character.
Static Public Member Functions
static JMA_CType_UTF8 * instance ()
Create an instance of JMA_CType_UTF8.
Detailed Description
JMA_CType_UTF8 gives the character type information in UTF-8 encoding.
Definition at line 20 of file jma_ctype_utf8.h.
Member Function Documentation
unsigned int jma::JMA_CType_UTF8::getByteCount (const char * p) const [virtual]
Get the byte count of the first character pointed by p, which character is in a specific encoding.
In UTF-8, characters from the U+0000.
Parameters:
p pointer to the character string
Returns:
the count of bytes.
.U+10FFFF range (the UTF-16 accessible range) are encoded using sequences of 1 to 4 octets. The table below summarizes the format of these different octet types. The letter x indicates bits available for encoding bits of the character number.
Char. number range | UTF-8 octet sequence (hexadecimal) | (binary) --------------------+--------------------------------------------- 0000 0000-0000 007F | 0xxxxxxx 0000 0080-0000 07FF | 110xxxxx 10xxxxxx 0000 0800-0000 FFFF | 1110xxxx 10xxxxxx 10xxxxxx 0001 0000-0010 FFFF | 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx
Implements jma::JMA_CType.
Definition at line 76 of file jma_ctype_utf8.cpp.
Referenced by isSpace(), and replaceSpaces().
JMA_CType_UTF8 * jma::JMA_CType_UTF8::instance () [static]
Create an instance of JMA_CType_UTF8.
Returns:
the pointer to instance (invoke new here)
Definition at line 52 of file jma_ctype_utf8.cpp.
bool jma::JMA_CType_UTF8::isSpace (const char * p) const [virtual]
Check whether is white-space character.
White-space characters are " \t\n\v\f\r", and also space character in specific encoding.
Parameters:
p pointer to the character string
Returns:
true for white-space character, false for non white-space character.
Implements jma::JMA_CType.
Definition at line 157 of file jma_ctype_utf8.cpp.
References getByteCount().
string jma::JMA_CType_UTF8::replaceSpaces (const char * str, char replacement) [virtual]
Replace space characters with replacement character.
Parameters:
str the input string
replacement the character to replace the space characters
Returns:
the output string
Implements jma::JMA_CType.
Definition at line 173 of file jma_ctype_utf8.cpp.
References getByteCount(), and replace().
The documentation for this class was generated from the following files:
source/include/jma_ctype_utf8.h
source/src/jma_ctype_utf8.cpp