Japanese Morphological Analyzer: MeCab::Viterbi Class Reference
MeCab::Viterbi Class Reference
#include <viterbi.h>
Public Member Functions
void clear ()
bool open (const Param &param, Tokenizer *t, Connector *c)
void close ()
double Z () const
Node * analyze (const char *str, size_t len)
const char * what ()
bool partial () const
void set_partial (bool partial)
float theta () const
void set_theta (float theta)
int lattice_level () const
void set_lattice_level (int level)
bool all_morphs () const
void set_all_morphs (bool all_morphs)
Viterbi ()
virtual ~Viterbi ()
Detailed Description
Definition at line 20 of file viterbi.h.
Constructor & Destructor Documentation
MeCab::Viterbi::Viterbi () [explicit]
Definition at line 55 of file viterbi.cpp.
MeCab::Viterbi::~Viterbi () [virtual]
Definition at line 58 of file viterbi.cpp.
References close().
Member Function Documentation
bool MeCab::Viterbi::all_morphs () const
Definition at line 97 of file viterbi.cpp.
Referenced by MeCab::TaggerImpl::all_morphs().
Node * MeCab::Viterbi::analyze (const char * str, size_t len)
Definition at line 107 of file viterbi.cpp.
References clear().
Referenced by MeCab::TaggerImpl::parseToNode().
void MeCab::Viterbi::clear ()
Definition at line 133 of file viterbi.cpp.
References MeCab::TokenizerImpl< N, P >::clear(), and MeCab::scoped_ptr< T >::get().
Referenced by analyze().
void MeCab::Viterbi::close ()
Definition at line 80 of file viterbi.cpp.
Referenced by ~Viterbi().
int MeCab::Viterbi::lattice_level () const [inline]
Definition at line 81 of file viterbi.h.
Referenced by MeCab::TaggerImpl::lattice_level(), and MeCab::TaggerImpl::parseNBestInit().
bool MeCab::Viterbi::open (const Param & param, Tokenizer * t, Connector * c)
Definition at line 60 of file viterbi.cpp.
References CHECK_FALSE, MeCab::Param::get(), MIN_INPUT_BUFFER_SIZE, MeCab::scoped_ptr< T >::reset(), set_all_morphs(), set_lattice_level(), set_partial(), and set_theta().
Referenced by MeCab::TaggerImpl::open().
bool MeCab::Viterbi::partial () const [inline]
Definition at line 75 of file viterbi.h.
Referenced by MeCab::TaggerImpl::partial().
void MeCab::Viterbi::set_all_morphs (bool all_morphs)
Definition at line 101 of file viterbi.cpp.
Referenced by open(), and MeCab::TaggerImpl::set_all_morphs().
void MeCab::Viterbi::set_lattice_level (int level)
Definition at line 82 of file viterbi.cpp.
References MeCab::scoped_ptr< T >::get(), PATH_FREELIST_SIZE, and MeCab::scoped_ptr< T >::reset().
Referenced by open(), and MeCab::TaggerImpl::set_lattice_level().
void MeCab::Viterbi::set_partial (bool partial) [inline]
Definition at line 76 of file viterbi.h.
Referenced by open(), and MeCab::TaggerImpl::set_partial().
void MeCab::Viterbi::set_theta (float theta) [inline]
Definition at line 79 of file viterbi.h.
Referenced by open(), and MeCab::TaggerImpl::set_theta().
float MeCab::Viterbi::theta () const [inline]
Definition at line 78 of file viterbi.h.
Referenced by MeCab::TaggerImpl::theta().
const char* MeCab::Viterbi::what () [inline]
Definition at line 73 of file viterbi.h.
References MeCab::whatlog::str().
Referenced by MeCab::TaggerImpl::open(), and MeCab::TaggerImpl::parseToNode().
double MeCab::Viterbi::Z () const [inline]
Definition at line 69 of file viterbi.h.
The documentation for this class was generated from the following files:
source/libmecab/viterbi.h
source/libmecab/viterbi.cpp
source/libmecab/viterbisub.h