Japanese Morphological Analyzer: MeCab::TaggerImpl Class Reference
MeCab::TaggerImpl Class Reference
Public Member Functions
bool open (Param *)
bool open (int, char **)
bool open (const char *)
void close ()
const char * parse (const char *)
const char * parse (const char *, size_t)
const char * parse (const char *, size_t, char *, size_t)
const Node * parseToNode (const char *)
const Node * parseToNode (const char *, size_t=0)
const char * parseNBest (size_t, const char *)
const char * parseNBest (size_t, const char *, size_t)
const char * parseNBest (size_t, const char *, size_t, char *, size_t)
bool parseNBestInit (const char *)
bool parseNBestInit (const char *, size_t)
const Node * nextNode ()
long nextScore ()
Invoke after invoking nextNode();.
const char * next ()
const char * next (char *, size_t)
const char * formatNode (const Node *)
const char * formatNode (const Node *, char *, size_t)
const DictionaryInfo * dictionary_info () const
void set_partial (bool partial)
bool partial () const
void set_theta (float theta)
float theta () const
void set_lattice_level (int level)
int lattice_level () const
void set_all_morphs (bool all_morphs)
bool all_morphs () const
const char * what ()
TaggerImpl ()
virtual ~TaggerImpl ()
Detailed Description
Definition at line 73 of file tagger.cpp.
Constructor & Destructor Documentation
MeCab::TaggerImpl::TaggerImpl () [inline]
Definition at line 121 of file tagger.cpp.
virtual MeCab::TaggerImpl::~TaggerImpl () [inline, virtual]
Definition at line 122 of file tagger.cpp.
References close().
Member Function Documentation
bool MeCab::TaggerImpl::all_morphs () const
Definition at line 206 of file tagger.cpp.
References MeCab::Viterbi::all_morphs().
void MeCab::TaggerImpl::close ()
Definition at line 176 of file tagger.cpp.
Referenced by open(), and ~TaggerImpl().
const DictionaryInfo * MeCab::TaggerImpl::dictionary_info () const
Definition at line 346 of file tagger.cpp.
References MeCab::TokenizerImpl< N, P >::dictionary_info().
Referenced by mecab_do().
const char * MeCab::TaggerImpl::formatNode (const Node * node, char * out, size_t len)
Definition at line 243 of file tagger.cpp.
References CHECK_0, MeCab::StringBuffer::str(), MeCab::Writer::what(), and MeCab::Writer::writeNode().
const char * MeCab::TaggerImpl::formatNode (const Node * node)
Definition at line 234 of file tagger.cpp.
References CHECK_0, MeCab::StringBuffer::clear(), MeCab::StringBuffer::str(), MeCab::Writer::what(), and MeCab::Writer::writeNode().
int MeCab::TaggerImpl::lattice_level () const
Definition at line 198 of file tagger.cpp.
References MeCab::Viterbi::lattice_level().
const char * MeCab::TaggerImpl::next (char * out, size_t len2)
Definition at line 305 of file tagger.cpp.
References CHECK_0, nextNode(), MeCab::StringBuffer::str(), MeCab::Writer::what(), and MeCab::Writer::write().
const char * MeCab::TaggerImpl::next ()
Definition at line 293 of file tagger.cpp.
References CHECK_0, MeCab::StringBuffer::clear(), nextNode(), MeCab::StringBuffer::str(), MeCab::Writer::what(), and MeCab::Writer::write().
const Node * MeCab::TaggerImpl::nextNode ()
Definition at line 281 of file tagger.cpp.
References CHECK_RETURN, MeCab::scoped_ptr< T >::get(), and MeCab::scoped_ptr< T >::reset().
Referenced by next(), and parseNBest().
long MeCab::TaggerImpl::nextScore ()
Invoke after invoking nextNode();.
Definition at line 289 of file tagger.cpp.
bool MeCab::TaggerImpl::open (const char * arg)
Definition at line 135 of file tagger.cpp.
References CHECK_CLOSE_FALSE, open(), MeCab::Param::open(), and MeCab::Param::what().
bool MeCab::TaggerImpl::open (int argc, char ** argv)
Definition at line 129 of file tagger.cpp.
References CHECK_CLOSE_FALSE, open(), MeCab::Param::open(), and MeCab::Param::what().
bool MeCab::TaggerImpl::open (Param * param)
Definition at line 141 of file tagger.cpp.
References CHECK_CLOSE_FALSE, close(), MeCab::Param::get(), MeCab::Param::help(), MeCab::load_dictionary_resource(), MeCab::Writer::open(), MeCab::Viterbi::open(), MeCab::Connector::open(), MeCab::TokenizerImpl< N, P >::open(), set_all_morphs(), set_lattice_level(), MeCab::Param::version(), MeCab::Writer::what(), MeCab::Viterbi::what(), MeCab::Connector::what(), MeCab::TokenizerImpl< N, P >::what(), MeCab::Param::what(), and WHAT.
Referenced by MeCab::createTagger(), mecab_do(), and open().
const char * MeCab::TaggerImpl::parse (const char * str, size_t len, char * out, size_t len2)
Definition at line 223 of file tagger.cpp.
References CHECK_0, parseToNode(), MeCab::StringBuffer::str(), MeCab::Writer::what(), and MeCab::Writer::write().
const char * MeCab::TaggerImpl::parse (const char * str, size_t len)
Definition at line 214 of file tagger.cpp.
References CHECK_0, MeCab::StringBuffer::clear(), parseToNode(), MeCab::StringBuffer::str(), MeCab::Writer::what(), and MeCab::Writer::write().
const char * MeCab::TaggerImpl::parse (const char * str)
Definition at line 210 of file tagger.cpp.
Referenced by mecab_do(), and parseNBest().
const char * MeCab::TaggerImpl::parseNBest (size_t N, const char * str, size_t len, char * out, size_t len2)
Definition at line 350 of file tagger.cpp.
References CHECK_0, nextNode(), parse(), parseNBestInit(), MeCab::StringBuffer::str(), MeCab::Writer::what(), and MeCab::Writer::write().
const char * MeCab::TaggerImpl::parseNBest (size_t N, const char * str, size_t len)
Definition at line 321 of file tagger.cpp.
References CHECK_0, MeCab::StringBuffer::clear(), MECAB_EON_NODE, nextNode(), parse(), parseNBestInit(), MeCab::StringBuffer::str(), MeCab::Writer::what(), MeCab::Writer::write(), and MeCab::Writer::writeNode().
const char * MeCab::TaggerImpl::parseNBest (size_t N, const char * str)
Definition at line 317 of file tagger.cpp.
Referenced by mecab_do().
bool MeCab::TaggerImpl::parseNBestInit (const char * str, size_t len)
Definition at line 269 of file tagger.cpp.
References CHECK_FALSE, MeCab::scoped_ptr< T >::get(), MeCab::Viterbi::lattice_level(), parseToNode(), and MeCab::scoped_ptr< T >::reset().
bool MeCab::TaggerImpl::parseNBestInit (const char * str)
Definition at line 265 of file tagger.cpp.
Referenced by parseNBest().
const Node * MeCab::TaggerImpl::parseToNode (const char * str, size_t len = 0)
Definition at line 258 of file tagger.cpp.
References MeCab::Viterbi::analyze(), CHECK_RETURN, and MeCab::Viterbi::what().
const Node * MeCab::TaggerImpl::parseToNode (const char * str)
Definition at line 254 of file tagger.cpp.
Referenced by parse(), and parseNBestInit().
bool MeCab::TaggerImpl::partial () const
Definition at line 182 of file tagger.cpp.
References MeCab::Viterbi::partial().
void MeCab::TaggerImpl::set_all_morphs (bool all_morphs)
Definition at line 202 of file tagger.cpp.
References MeCab::Viterbi::set_all_morphs().
Referenced by open().
void MeCab::TaggerImpl::set_lattice_level (int level)
Definition at line 194 of file tagger.cpp.
References MeCab::Viterbi::set_lattice_level().
Referenced by open().
void MeCab::TaggerImpl::set_partial (bool partial)
Definition at line 178 of file tagger.cpp.
References MeCab::Viterbi::set_partial().
void MeCab::TaggerImpl::set_theta (float theta)
Definition at line 186 of file tagger.cpp.
References MeCab::Viterbi::set_theta().
float MeCab::TaggerImpl::theta () const
Definition at line 190 of file tagger.cpp.
References MeCab::Viterbi::theta().
const char * MeCab::TaggerImpl::what ()
Definition at line 125 of file tagger.cpp.
References MeCab::whatlog::str().
Referenced by MeCab::createTagger(), and mecab_do().
The documentation for this class was generated from the following file:
source/libmecab/tagger.cpp