Japanese Morphological Analyzer: MeCab::Writer Class Reference
MeCab::Writer Class Reference
#include <writer.h>
Public Member Functions
Writer ()
virtual ~Writer ()
bool open (const Param &)
void close ()
bool writeNode (StringBuffer *os, const char *fmt, const char *sent, const Node *node)
bool writeNode (StringBuffer *os, const char *sent, const Node *node)
bool write (StringBuffer *os, const char *sent, const Node *node)
const char * what ()
Detailed Description
Definition at line 17 of file writer.h.
Constructor & Destructor Documentation
MeCab::Writer::Writer () [inline, explicit]
Definition at line 36 of file writer.h.
virtual MeCab::Writer::~Writer () [inline, virtual]
Definition at line 37 of file writer.h.
Member Function Documentation
void MeCab::Writer::close ()
Definition at line 19 of file writer.cpp.
bool MeCab::Writer::open (const Param & param)
Definition at line 23 of file writer.cpp.
References CHECK_FALSE, MeCab::Param::get(), and MeCab::scoped_string::reset_string().
Referenced by MeCab::TaggerImpl::open().
const char* MeCab::Writer::what () [inline]
Definition at line 45 of file writer.h.
References MeCab::whatlog::str().
Referenced by MeCab::TaggerImpl::formatNode(), MeCab::TaggerImpl::next(), MeCab::TaggerImpl::open(), MeCab::TaggerImpl::parse(), and MeCab::TaggerImpl::parseNBest().
bool MeCab::Writer::write (StringBuffer * os, const char * sent, const Node * node)
Definition at line 100 of file writer.cpp.
Referenced by MeCab::TaggerImpl::next(), MeCab::TaggerImpl::parse(), and MeCab::TaggerImpl::parseNBest().
bool MeCab::Writer::writeNode (StringBuffer * os, const char * sent, const Node * node)
Definition at line 201 of file writer.cpp.
References MeCab::scoped_array< T >::get(), MECAB_BOS_NODE, MECAB_EON_NODE, MECAB_EOS_NODE, MECAB_NOR_NODE, MECAB_UNK_NODE, and writeNode().
bool MeCab::Writer::writeNode (StringBuffer * os, const char * fmt, const char * sent, const Node * node)
Definition at line 218 of file writer.cpp.
References BUF_SIZE, CHECK_FALSE, MeCab::getEscapedChar(), MeCab::tokenizeCSV(), and MeCab::StringBuffer::write().
Referenced by MeCab::TaggerImpl::formatNode(), MeCab::TaggerImpl::parseNBest(), and writeNode().
The documentation for this class was generated from the following files:
source/libmecab/writer.h
source/libmecab/writer.cpp