Japanese Morphological Analyzer: MeCab::StringBuffer Class Reference
MeCab::StringBuffer Class Reference
#include <string_buffer.h>
Public Member Functions
StringBuffer ()
StringBuffer (char *_s, size_t _l)
virtual ~StringBuffer ()
StringBuffer & write (char)
StringBuffer & write (const char *, size_t)
StringBuffer & write (const char *)
StringBuffer & operator<< (double n)
StringBuffer & operator<< (short int n)
StringBuffer & operator<< (int n)
StringBuffer & operator<< (long int n)
StringBuffer & operator<< (unsigned short int n)
StringBuffer & operator<< (unsigned int n)
StringBuffer & operator<< (unsigned long int n)
StringBuffer & operator<< (char n)
StringBuffer & operator<< (unsigned char n)
StringBuffer & operator<< (const char *n)
StringBuffer & operator<< (const std::string &n)
void clear ()
const char * str () const
Detailed Description
Definition at line 20 of file string_buffer.h.
Constructor & Destructor Documentation
MeCab::StringBuffer::StringBuffer () [inline, explicit]
Definition at line 30 of file string_buffer.h.
MeCab::StringBuffer::StringBuffer (char * _s, size_t _l) [inline, explicit]
Definition at line 32 of file string_buffer.h.
MeCab::StringBuffer::~StringBuffer () [virtual]
Definition at line 40 of file string_buffer.cpp.
Member Function Documentation
void MeCab::StringBuffer::clear () [inline]
Definition at line 65 of file string_buffer.h.
Referenced by MeCab::FeatureIndex::buildBigramFeature(), MeCab::EncoderFeatureIndex::buildFeature(), MeCab::FeatureIndex::buildUnigramFeature(), MeCab::TaggerImpl::formatNode(), MeCab::TaggerImpl::next(), MeCab::TaggerImpl::parse(), and MeCab::TaggerImpl::parseNBest().
StringBuffer& MeCab::StringBuffer::operator<< (const std::string & n) [inline]
Definition at line 61 of file string_buffer.h.
References write().
StringBuffer& MeCab::StringBuffer::operator<< (const char * n) [inline]
Definition at line 57 of file string_buffer.h.
References write().
StringBuffer& MeCab::StringBuffer::operator<< (unsigned char n) [inline]
Definition at line 53 of file string_buffer.h.
References write().
StringBuffer& MeCab::StringBuffer::operator<< (char n) [inline]
Definition at line 49 of file string_buffer.h.
References write().
StringBuffer& MeCab::StringBuffer::operator<< (unsigned long int n) [inline]
Definition at line 47 of file string_buffer.h.
References _UITOA.
StringBuffer& MeCab::StringBuffer::operator<< (unsigned int n) [inline]
Definition at line 46 of file string_buffer.h.
References _UITOA.
StringBuffer& MeCab::StringBuffer::operator<< (unsigned short int n) [inline]
Definition at line 45 of file string_buffer.h.
References _UITOA.
StringBuffer& MeCab::StringBuffer::operator<< (long int n) [inline]
Definition at line 44 of file string_buffer.h.
References _ITOA.
StringBuffer& MeCab::StringBuffer::operator<< (int n) [inline]
Definition at line 43 of file string_buffer.h.
References _ITOA.
StringBuffer& MeCab::StringBuffer::operator<< (short int n) [inline]
Definition at line 42 of file string_buffer.h.
References _ITOA.
StringBuffer& MeCab::StringBuffer::operator<< (double n) [inline]
Definition at line 41 of file string_buffer.h.
References _DTOA.
const char* MeCab::StringBuffer::str () const [inline]
Definition at line 66 of file string_buffer.h.
Referenced by MeCab::FeatureIndex::buildBigramFeature(), MeCab::EncoderFeatureIndex::buildFeature(), MeCab::FeatureIndex::buildUnigramFeature(), MeCab::TaggerImpl::formatNode(), MeCab::TaggerImpl::next(), MeCab::TaggerImpl::parse(), and MeCab::TaggerImpl::parseNBest().
StringBuffer & MeCab::StringBuffer::write (const char * str)
Definition at line 55 of file string_buffer.cpp.
References write().
StringBuffer & MeCab::StringBuffer::write (const char * str, size_t length)
Definition at line 59 of file string_buffer.cpp.
StringBuffer & MeCab::StringBuffer::write (char str)
Definition at line 47 of file string_buffer.cpp.
Referenced by operator<<(), write(), and MeCab::Writer::writeNode().
The documentation for this class was generated from the following files:
source/libmecab/string_buffer.h
source/libmecab/string_buffer.cpp