Japanese Morphological Analyzer: jma::scoped_string Class Reference
jma::scoped_string Class Reference
#include <scoped_ptr.h>
Public Member Functions
scoped_string ()
scoped_string (const std::string &str)
void reset_string (const std::string &str)
void reset_string (const char *str)
Detailed Description
Definition at line 63 of file scoped_ptr.h.
Constructor & Destructor Documentation
jma::scoped_string::scoped_string () [inline, explicit]
Definition at line 65 of file scoped_ptr.h.
References reset_string().
jma::scoped_string::scoped_string (const std::string & str) [inline, explicit]
Definition at line 66 of file scoped_ptr.h.
References reset_string().
Member Function Documentation
void jma::scoped_string::reset_string (const char * str) [inline]
Definition at line 76 of file scoped_ptr.h.
References jma::scoped_array< char >::reset().
void jma::scoped_string::reset_string (const std::string & str) [inline]
Definition at line 70 of file scoped_ptr.h.
References jma::scoped_array< char >::reset().
Referenced by scoped_string().
The documentation for this class was generated from the following file:
source/include/scoped_ptr.h