Japanese Morphological Analyzer: MeCab::NBestGenerator Class Reference
MeCab::NBestGenerator Class Reference
#include <nbest_generator.h>
Classes
struct QueueElement
class QueueElementComp
Public Member Functions
NBestGenerator ()
virtual ~NBestGenerator ()
bool set (Node *)
Node * next ()
long nextScore ()
Invoked after invoking next().
Detailed Description
Definition at line 16 of file nbest_generator.h.
Constructor & Destructor Documentation
MeCab::NBestGenerator::NBestGenerator () [inline, explicit]
Definition at line 37 of file nbest_generator.h.
virtual MeCab::NBestGenerator::~NBestGenerator () [inline, virtual]
Definition at line 38 of file nbest_generator.h.
Member Function Documentation
Node * MeCab::NBestGenerator::next ()
Definition at line 25 of file nbest_generator.cpp.
References MeCab::FreeList< T >::alloc(), and MECAB_BOS_NODE.
long MeCab::NBestGenerator::nextScore ()
Invoked after invoking next().
Definition at line 54 of file nbest_generator.cpp.
bool MeCab::NBestGenerator::set (Node * node)
Definition at line 13 of file nbest_generator.cpp.
References MeCab::FreeList< T >::alloc(), and MeCab::FreeList< T >::free().
The documentation for this class was generated from the following files:
source/libmecab/nbest_generator.h
source/libmecab/nbest_generator.cpp