Japanese Morphological Analyzer: jma::Analyzer Class Reference
jma::Analyzer Class Reference
Analyzer executes the Japanese morphological analysis.
#include <analyzer.h>
Public Types
enum OptionType {
OPTION_TYPE_POS_TAGGING, OPTION_TYPE_NBEST, OPTION_TYPE_POS_FORMAT_ALPHABET, OPTION_TYPE_POS_FULL_CATEGORY,
OPTION_TYPE_COMPOUND_MORPHOLOGY, OPTION_TYPE_DECOMPOSE_USER_NOUN, OPTION_TYPE_CONVERT_TO_HIRAGANA, OPTION_TYPE_CONVERT_TO_KATAKANA,
OPTION_TYPE_CONVERT_TO_HALF_WIDTH, OPTION_TYPE_CONVERT_TO_FULL_WIDTH, OPTION_TYPE_CONVERT_TO_LOWER_CASE, OPTION_TYPE_CONVERT_TO_UPPER_CASE,
OPTION_TYPE_NUM
}
Option type for analysis.
Public Member Functions
Analyzer ()
Constructor.
virtual ~Analyzer ()
Destructor.
virtual int setKnowledge (Knowledge *pKnowledge)=0
Set the Knowledge for analysis.
virtual int runWithSentence (Sentence &sentence)=0
Execute the morphological analysis based on a sentence.
virtual const char * runWithString (const char *inStr)=0
Execute the morphological analysis based on a paragraph string.
virtual int runWithStream (const char *inFileName, const char *outFileName)=0
Execute the morphological analysis based on a file.
virtual void splitSentence (const char *paragraph, std::vector< Sentence > &sentences)=0
Split a paragraph string into sentences.
virtual std::string convertCharacters (const char *str) const =0
The characters, configured by OPTION_TYPE_CONVERT_TO_*, are converted to their target types, other characters are kept as original.
void setOption (OptionType nOption, double nValue)
Set the option value for analysis.
double getOption (OptionType nOption) const
Get the option value.
void setPOSDelimiter (const char *delimiter)
Set the delimiter between word and POS tag in the output result of runWithString() and runWithStream(), which delimiter is "/" defaultly so that the result would be "word/pos word/pos ...".
const char * getPOSDelimiter () const
Get the delimiter between word and POS tag in the output result of runWithString() and runWithStream(), which delimiter is "/" defaultly so that the result would be "word/pos word/pos ...".
void setWordDelimiter (const char *delimiter)
Set the delimiter between the pairs (word and POS tag) in the output result of runWithString() and runWithStream(), which delimiter is " " (double-space) defaultly so that the result would be "word/pos word/pos ...".
const char * getWordDelimiter () const
Get the delimiter between the pairs (word and POS tag) in the output result of runWithString() and runWithStream(), which delimiter is " " (double-space) defaultly so that the result would be "word/pos word/pos ...".
Protected Attributes
const char * posDelimiter_
the delimiter between word and POS tag in the output result
const char * wordDelimiter_
the delimiter between the pairs (word and POS tag) in the output result
Detailed Description
Analyzer executes the Japanese morphological analysis.
Typically, the usage is like below:
 // create instances
 JMA_Factory* factory = JMA_Factory::instance();
 Analyzer* analyzer = factory->createAnalyzer();
 Knowledge* knowledge = factory->createKnowledge();
 // load dictionaries (optional)
 knowledge->setSystemDict("...");
 knowledge->addUserDict("...", Knowledge::ENCODE_TYPE_***);
 knowledge->loadDict();
 knowledge->loadStopWordDict("...");
 // set knowledge
 analyzer->setKnowledge(knowledge);
 // analyze a sentence
 Sentence s;
 s.setString("...");
 analyzer->runWithSentence(s);
 ...
 // analyze a paragraph
 const char* result = analyzer->runWithString("...");
 ...
 // analyze a file
 analyzer->runWithStream("...", "...");
 // split paragraphs into sentences
 string line;
 vector<Sentence> sentVec;
 while(getline(cin, line)) // get paragraph string from standard input
 {
      sentVec.clear(); // remove previous sentences
      analyzer->splitSentence(line.c_str(), sentVec);
      for(size_t i=0; i<sentVec.size(); ++i)
      {
          analyzer->runWithSentence(sentVec[i]); // analyze each sentence
          ...
      }
  }
 delete knowledge;
 delete analyzer;
Definition at line 74 of file analyzer.h.
Member Enumeration Documentation
enum jma::Analyzer::OptionType
Option type for analysis.
Enumerator:
OPTION_TYPE_POS_TAGGING
Configure whether to print part-of-speech tags.
If a non-zero value is configured, part-of-speech tags are printed in below APIs: runWithString(), runWithStream(), output example: "通常/名詞,一般 は/助詞,係助詞 ".
If a zero value is configured, part-of-speech tags are not printed in above APIS, output example: "通常 は ".
Default value: 1
OPTION_TYPE_NBEST
Configure the number of n-best results.
If a positive value is configured, the maximum number of n-best results are got in below APIs: runWithSentence().
If non-positive value is configured, it is ignored as invalid value.
If the value of option OPTION_TYPE_POS_TAGGING is zero, the n-best results are different on Morpheme::lexicon_, otherwise, they are different on either Morpheme::lexicon_ or Morpheme::posStr_.
Default value: 1
OPTION_TYPE_POS_FORMAT_ALPHABET
Configure whether to print part-of-speech tags in alphabet format.
If a non-zero value is configured, part-of-speech tags are in alphabet format in below APIs: runWithSentence(), runWithString(), runWithStream(), output example: "通常/NC-G は/PL-A ".
If a zero value is configured, part-of-speech tags are in Japanese format in above APIS, output example: "通常/名詞,一般 は/助詞,係助詞 ".
Default value: 0
OPTION_TYPE_POS_FULL_CATEGORY
Configure whether to print part-of-speech tags in Japanese format of full category.
If a non-zero value is configured, part-of-speech tags are in Japanese format of full category, which might includes asterisk symbol, it is valid for below APIs: runWithSentence(), runWithString(), runWithStream(), output example: "通常/名詞,一般,*,* は/助詞,係助詞,*,* ".
If a zero value is configured, part-of-speech tags are in effective category format, which excludes asterisk symbol, output example: "通常/名詞,一般 は/助詞,係助詞 ".
If the value of option OPTION_TYPE_POS_FORMAT_ALPHABET is non-zero, this option would take no effect.
Default value: 0
OPTION_TYPE_COMPOUND_MORPHOLOGY
Configure whether to combine a sequence of words into single compound words.
If a non-zero value is configured, sequence of words are combined into single compound words, it is valid for below APIs: runWithSentence(), runWithString(), runWithStream(), output example: "長野県/名詞,固有名詞,地域,一般 ".
If a zero value is configured, compound words are decomposed into their components in above APIS, output example: "長野/名詞,固有名詞,地域,一般 県/名詞,接尾,地域 ".
The rules to combine into compound words are defined in the file "compound.def" under system dictionary path, if this file does not exist, no words would be combined into compound words.
Default value: 1
OPTION_TYPE_DECOMPOSE_USER_NOUN
Configure whether to decompose user defined compound into a sequence of nouns.
If a non-zero value is configured, user defined compounds are decomposed into a sequence of nouns, it is valid for below APIs: runWithSentence(), runWithString(), runWithStream(), output example: "本田/名詞,ユーザ 総一郎/名詞,ユーザ ".
If a zero value is configured, user defined compounds are not decomposed in above APIS, output example: "本田総一郎/名詞,ユーザ ".
The decomposition pattern is defined in user dictionary, such as "本田総一郎 2,3".
Default value: 0
OPTION_TYPE_CONVERT_TO_HIRAGANA
Configure whether to convert Japanese Katakana characters to their Hiragana equivalents.
If a non-zero value is configured, Katakana characters are converted to their Hiragana equivalents, it is valid for below APIs: convertCharacters(), output example: "帝国でーたばんく".
If a zero value is configured, Katakana characters are not converted as original, output example: "帝国データバンク".
Default value: 0
OPTION_TYPE_CONVERT_TO_KATAKANA
Configure whether to convert Japanese Hiragana characters to their Katakana equivalents.
If a non-zero value is configured, Hiragana characters are converted to their Katakana equivalents, it is valid for below APIs: convertCharacters(), output example: "少ナクトモ".
If a zero value is configured, Hiragana characters are not converted as original, output example: "少なくとも".
Default value: 0
OPTION_TYPE_CONVERT_TO_HALF_WIDTH
Configure whether to convert digits and alphabets to their half width equivalents.
If a non-zero value is configured, digits and alphabets are converted to their half width equivalents, it is valid for below APIs: convertCharacters(), output example: "ABC123".
If a zero value is configured, digits and alphabets are not converted as original, output example: "ＡＢＣ１２３".
Default value: 0
OPTION_TYPE_CONVERT_TO_FULL_WIDTH
Configure whether to convert digits and alphabets to their full width equivalents.
If a non-zero value is configured, digits and alphabets are converted to their full width equivalents, it is valid for below APIs: convertCharacters(), output example: "ＡＢＣ１２３".
If a zero value is configured, digits and alphabets are not converted as original, output example: "ABC123".
Default value: 0
OPTION_TYPE_CONVERT_TO_LOWER_CASE
Configure whether to convert alphabets to their lower case equivalents.
If a non-zero value is configured, alphabets are converted to their lower case equivalents, it is valid for below APIs: convertCharacters(), output example: "abcａｂｃ".
If a zero value is configured, digits and alphabets are not converted as original, output example: "ABCＡＢＣ".
Default value: 0
OPTION_TYPE_CONVERT_TO_UPPER_CASE
Configure whether to convert alphabets to their upper case equivalents.
If a non-zero value is configured, alphabets are converted to their upper case equivalents, it is valid for below APIs: convertCharacters(), output example: "ABCＡＢＣ".
If a zero value is configured, digits and alphabets are not converted as original, output example: "abcａｂｃ".
Default value: 0
OPTION_TYPE_NUM
the count of option types
Definition at line 137 of file analyzer.h.
Constructor & Destructor Documentation
jma::Analyzer::Analyzer ()
Constructor.
Definition at line 25 of file analyzer.cpp.
References OPTION_TYPE_COMPOUND_MORPHOLOGY, OPTION_TYPE_CONVERT_TO_HIRAGANA, OPTION_TYPE_CONVERT_TO_KATAKANA, OPTION_TYPE_NBEST, OPTION_TYPE_POS_FORMAT_ALPHABET, OPTION_TYPE_POS_FULL_CATEGORY, and OPTION_TYPE_POS_TAGGING.
jma::Analyzer::~Analyzer () [virtual]
Destructor.
Definition at line 39 of file analyzer.cpp.
Member Function Documentation
virtual std::string jma::Analyzer::convertCharacters (const char * str) const [pure virtual]
The characters, configured by OPTION_TYPE_CONVERT_TO_*, are converted to their target types, other characters are kept as original.
Parameters:
str string to convert from
Returns:
the conversion result
Implemented in jma::JMA_Analyzer.
Referenced by main().
double jma::Analyzer::getOption (OptionType nOption) const
Get the option value.
Parameters:
nOption the option type
Returns:
the option value
Definition at line 52 of file analyzer.cpp.
Referenced by jma::JMA_Analyzer::convertCharacters(), jma::JMA_Analyzer::isOutputPOS(), and jma::JMA_Analyzer::runWithSentence().
const char * jma::Analyzer::getPOSDelimiter () const
Get the delimiter between word and POS tag in the output result of runWithString() and runWithStream(), which delimiter is "/" defaultly so that the result would be "word/pos word/pos ...".
Returns:
the delimiter between word and POS tag in the output result
Definition at line 62 of file analyzer.cpp.
References posDelimiter_.
Referenced by testWithSentence().
const char * jma::Analyzer::getWordDelimiter () const
Get the delimiter between the pairs (word and POS tag) in the output result of runWithString() and runWithStream(), which delimiter is " " (double-space) defaultly so that the result would be "word/pos word/pos ...".
Returns:
the delimiter between the pairs (word and POS tag) in the output result
Definition at line 72 of file analyzer.cpp.
References wordDelimiter_.
Referenced by testWithSentence().
virtual int jma::Analyzer::runWithSentence (Sentence & sentence) [pure virtual]
Execute the morphological analysis based on a sentence.
Parameters:
sentence the instance containing the raw sentence string and also to save the analysis result
Returns:
0 for fail, 1 for success
Precondition:
the raw sentence string could be got by sentence.getString().
Postcondition:
on successful return, the n-best results could be got by sentence.getListSize(), etc.
Implemented in jma::JMA_Analyzer.
Referenced by main(), JMA_AnalyzerTest::runWithSentenceTest(), and testWithSentence().
virtual int jma::Analyzer::runWithStream (const char * inFileName, const char * outFileName) [pure virtual]
Execute the morphological analysis based on a file.
Parameters:
inFileName input file name
outFileName output file name
Returns:
0 for fail, 1 for success
Postcondition:
on successful return, the one-best result is printed to file outFileName.
Implemented in jma::JMA_Analyzer.
Referenced by AnalyzerThread::run(), and testWithStream().
virtual const char* jma::Analyzer::runWithString (const char * inStr) [pure virtual]
Execute the morphological analysis based on a paragraph string.
Parameters:
inStr paragraph string
Returns:
0 for fail, otherwise a non-zero string pointer for the one-best result
Implemented in jma::JMA_Analyzer.
Referenced by main(), and testWithString().
virtual int jma::Analyzer::setKnowledge (Knowledge * pKnowledge) [pure virtual]
Set the Knowledge for analysis.
Parameters:
pKnowledge the pointer of Knowledge
Returns:
0 for fail, 1 for success
Implemented in jma::JMA_Analyzer.
Referenced by main().
void jma::Analyzer::setOption (OptionType nOption, double nValue)
Set the option value for analysis.
Parameters:
nOption the option type
nValue the option value
Attention:
when nOption is OPTION_TYPE_NBEST, the invalid nValue less than 1 will take no effect.
Definition at line 43 of file analyzer.cpp.
References OPTION_TYPE_NBEST.
Referenced by main().
void jma::Analyzer::setPOSDelimiter (const char * delimiter)
Set the delimiter between word and POS tag in the output result of runWithString() and runWithStream(), which delimiter is "/" defaultly so that the result would be "word/pos word/pos ...".
Parameters:
delimiter the delimiter between word and POS tag in the output result
Definition at line 57 of file analyzer.cpp.
References posDelimiter_.
void jma::Analyzer::setWordDelimiter (const char * delimiter)
Set the delimiter between the pairs (word and POS tag) in the output result of runWithString() and runWithStream(), which delimiter is " " (double-space) defaultly so that the result would be "word/pos word/pos ...".
Parameters:
delimiter the delimiter between the pairs (word and POS tag) in the output result
Definition at line 67 of file analyzer.cpp.
References wordDelimiter_.
virtual void jma::Analyzer::splitSentence (const char * paragraph, std::vector< Sentence > & sentences) [pure virtual]
Split a paragraph string into sentences.
Parameters:
paragraph paragraph string
sentences sentence vector
Attention:
the original elements in sentences would not be removed, and the splited sentences are appended into sentences.
Implemented in jma::JMA_Analyzer.
Referenced by main().
Member Data Documentation
const char* jma::Analyzer::posDelimiter_ [protected]
the delimiter between word and POS tag in the output result
Definition at line 351 of file analyzer.h.
Referenced by getPOSDelimiter(), and setPOSDelimiter().
const char* jma::Analyzer::wordDelimiter_ [protected]
the delimiter between the pairs (word and POS tag) in the output result
Definition at line 354 of file analyzer.h.
Referenced by getWordDelimiter(), and setWordDelimiter().
The documentation for this class was generated from the following files:
include/analyzer.h
source/src/analyzer.cpp