Japanese Morphological Analyzer: MeCab::DecoderFeatureIndex Class Reference
MeCab::DecoderFeatureIndex Class Reference
#include <feature_index.h>
Public Member Functions
bool open (const Param &param)
void clear ()
void close ()
bool buildFeature (LearnerPath *path)
Detailed Description
Definition at line 87 of file feature_index.h.
Member Function Documentation
bool MeCab::DecoderFeatureIndex::buildFeature (LearnerPath * path) [virtual]
Implements MeCab::FeatureIndex.
Definition at line 185 of file feature_index.cpp.
References MeCab::FeatureIndex::buildBigramFeature(), MeCab::FeatureIndex::buildUnigramFeature(), CHECK_DIE, MeCab::DictionaryRewriter::rewrite2(), and MeCab::FeatureIndex::rewrite_.
void MeCab::DecoderFeatureIndex::clear () [virtual]
Implements MeCab::FeatureIndex.
Definition at line 141 of file feature_index.cpp.
References MeCab::FeatureIndex::feature_freelist_, and MeCab::ChunkFreeList< T >::free().
void MeCab::DecoderFeatureIndex::close () [virtual]
Implements MeCab::FeatureIndex.
Definition at line 158 of file feature_index.cpp.
References MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::clear(), MeCab::Mmap< T >::close(), and MeCab::FeatureIndex::maxid_.
Referenced by open().
bool MeCab::DecoderFeatureIndex::open (const Param & param) [virtual]
Implements MeCab::FeatureIndex.
Definition at line 120 of file feature_index.cpp.
References MeCab::FeatureIndex::alpha_, MeCab::Mmap< T >::begin(), CHECK_FALSE, close(), MeCab::Param::get(), MeCab::FeatureIndex::maxid_, MeCab::Mmap< T >::open(), MeCab::FeatureIndex::openTemplate(), MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::set_array(), and MeCab::Mmap< T >::what().
Referenced by MeCab::DictionaryGenerator::run().
The documentation for this class was generated from the following files:
source/libmecab/feature_index.h
source/libmecab/feature_index.cpp