Japanese Morphological Analyzer: jma::JMA_Analyzer Class Reference
jma::JMA_Analyzer Class Reference
JMA_Analyzer executes the Japanese morphological analysis based on conditional random field.
#include <jma_analyzer.h>
Public Member Functions
JMA_Analyzer ()
Constructor.
~JMA_Analyzer ()
Destructor.
virtual int setKnowledge (Knowledge *pKnowledge)
Set the Knowledge for analysis.
virtual int runWithSentence (Sentence &sentence)
Execute the morphological analysis based on a sentence.
virtual const char * runWithString (const char *inStr)
Execute the morphological analysis based on a paragraph string.
virtual int runWithStream (const char *inFileName, const char *outFileName)
Execute the morphological analysis based on a file.
virtual void splitSentence (const char *paragraph, std::vector< Sentence > &sentences)
Split a paragraph string into sentences.
virtual std::string convertCharacters (const char *str) const
The characters, configured by OPTION_TYPE_CONVERT_TO_*, are converted to their target types, other characters are kept as original.
bool isOutputPOS () const
Check whether output POS.
void runOneBest (Sentence &sentence) const
Execute the one-best morphological analysis based on a sentence.
bool runNBest (Sentence &sentence, int nbest) const
Execute the n-best morphological analysis based on a sentence.
Detailed Description
JMA_Analyzer executes the Japanese morphological analysis based on conditional random field.
Definition at line 27 of file jma_analyzer.h.
Constructor & Destructor Documentation
jma::JMA_Analyzer::JMA_Analyzer ()
Constructor.
Definition at line 195 of file jma_analyzer.cpp.
jma::JMA_Analyzer::~JMA_Analyzer ()
Destructor.
Definition at line 202 of file jma_analyzer.cpp.
Member Function Documentation
std::string jma::JMA_Analyzer::convertCharacters (const char * str) const [virtual]
The characters, configured by OPTION_TYPE_CONVERT_TO_*, are converted to their target types, other characters are kept as original.
Parameters:
str string to convert from
Returns:
the conversion result
Implements jma::Analyzer.
Definition at line 495 of file jma_analyzer.cpp.
References jma::JMA_Knowledge::getCType(), jma::Analyzer::getOption(), jma::Analyzer::OPTION_TYPE_CONVERT_TO_FULL_WIDTH, jma::Analyzer::OPTION_TYPE_CONVERT_TO_HALF_WIDTH, jma::Analyzer::OPTION_TYPE_CONVERT_TO_HIRAGANA, jma::Analyzer::OPTION_TYPE_CONVERT_TO_KATAKANA, jma::Analyzer::OPTION_TYPE_CONVERT_TO_LOWER_CASE, jma::Analyzer::OPTION_TYPE_CONVERT_TO_UPPER_CASE, jma::CharTable::toLeft(), and jma::CharTable::toRight().
bool jma::JMA_Analyzer::isOutputPOS () const
Check whether output POS.
Returns:
true for output POS, false for not to output POS.
Definition at line 217 of file jma_analyzer.cpp.
References jma::Analyzer::getOption(), and jma::Analyzer::OPTION_TYPE_POS_TAGGING.
Referenced by runNBest().
bool jma::JMA_Analyzer::runNBest (Sentence & sentence, int nbest) const
Execute the n-best morphological analysis based on a sentence.
Parameters:
sentence the instance containing the raw sentence string and also to save the analysis result
nbest the n-best value, which is at least 2
Returns:
true for success, false for fail
Precondition:
the raw sentence string could be got by sentence.getString().
Postcondition:
on successful return, the n-best results could be got by sentence.getListSize(), etc.
Attention:
white-space characters are ignored in the analysis, which include " \t\n\v\f\r", and also space character in specific encoding.
Definition at line 635 of file jma_analyzer.cpp.
References jma::Sentence::addList(), jma::Sentence::getString(), isOutputPOS(), and jma::isSameMorphemeList().
Referenced by runWithSentence().
void jma::JMA_Analyzer::runOneBest (Sentence & sentence) const
Execute the one-best morphological analysis based on a sentence.
Parameters:
sentence the instance containing the raw sentence string and also to save the analysis result
Precondition:
the raw sentence string could be got by sentence.getString().
Postcondition:
on return, the one-best result could be got by sentence.getListSize(), etc.
Attention:
white-space characters are ignored in the analysis, which include " \t\n\v\f\r", and also space character in specific encoding.
Definition at line 616 of file jma_analyzer.cpp.
References jma::Sentence::addList(), and jma::Sentence::getString().
Referenced by runWithSentence().
int jma::JMA_Analyzer::runWithSentence (Sentence & sentence) [virtual]
Execute the morphological analysis based on a sentence.
Parameters:
sentence the instance containing the raw sentence string and also to save the analysis result
Returns:
0 for fail, 1 for success
Precondition:
the raw sentence string could be got by sentence.getString().
Postcondition:
on successful return, the n-best results could be got by sentence.getListSize(), etc.
Attention:
white-space characters are ignored in the analysis, which include " \t\n\v\f\r", and also space character in specific encoding.
Implements jma::Analyzer.
Definition at line 280 of file jma_analyzer.cpp.
References jma::JMA_Knowledge::getCType(), jma::Analyzer::getOption(), jma::Analyzer::OPTION_TYPE_NBEST, runNBest(), and runOneBest().
Referenced by main().
int jma::JMA_Analyzer::runWithStream (const char * inFileName, const char * outFileName) [virtual]
Execute the morphological analysis based on a file.
Parameters:
inFileName input file name
outFileName output file name
Returns:
0 for fail, 1 for success
Postcondition:
on successful return, the one-best result is printed to file outFileName.
Implements jma::Analyzer.
Definition at line 312 of file jma_analyzer.cpp.
References jma::JMA_Knowledge::getCType(), and runWithString().
Referenced by JMA_AnalyzerTest::runWithStreamTest().
const char * jma::JMA_Analyzer::runWithString (const char * inStr) [virtual]
Execute the morphological analysis based on a paragraph string.
Parameters:
inStr paragraph string
Returns:
0 for fail, otherwise a non-zero string pointer for the one-best result
Implements jma::Analyzer.
Definition at line 300 of file jma_analyzer.cpp.
References jma::JMA_Knowledge::getCType().
Referenced by main(), and runWithStream().
int jma::JMA_Analyzer::setKnowledge (Knowledge * pKnowledge) [virtual]
Set the Knowledge for analysis.
Parameters:
pKnowledge the pointer of Knowledge
Returns:
0 for fail, 1 for success
Implements jma::Analyzer.
Definition at line 248 of file jma_analyzer.cpp.
References jma::JMA_Knowledge::createTagger(), jma::JMA_Knowledge::getCaseTable(), jma::JMA_Knowledge::getCType(), jma::JMA_Knowledge::getDecompMap(), jma::JMA_Knowledge::getKanaTable(), jma::JMA_Knowledge::getPOSTable(), and jma::JMA_Knowledge::getWidthTable().
Referenced by main(), JMA_AnalyzerTest::SetUp(), and TEST_F().
void jma::JMA_Analyzer::splitSentence (const char * paragraph, std::vector< Sentence > & sentences) [virtual]
Split a paragraph string into sentences.
Parameters:
paragraph paragraph string
sentences sentence vector
Attention:
the original elements in sentences would not be removed, and the splited sentences are appended into sentences.
Implements jma::Analyzer.
Definition at line 339 of file jma_analyzer.cpp.
References jma::JMA_Knowledge::getCType().
The documentation for this class was generated from the following files:
source/include/jma_analyzer.h
source/src/jma_analyzer.cpp