Japanese Morphological Analyzer: jma::JMA_Factory Class Reference
jma::JMA_Factory Class Reference
JMA_Factory creates instances for Japanese morphological analysis.
#include <jma_factory.h>
Public Member Functions
virtual Analyzer * createAnalyzer ()
Create an instance of Analyzer.
virtual Knowledge * createKnowledge ()
Create an instance of Knowledge.
Static Public Member Functions
static JMA_Factory * instance ()
Create an instance of JMA_Factory.
Protected Member Functions
JMA_Factory ()
Constructor.
virtual ~JMA_Factory ()
Destructor.
Detailed Description
JMA_Factory creates instances for Japanese morphological analysis.
Definition at line 21 of file jma_factory.h.
Constructor & Destructor Documentation
jma::JMA_Factory::JMA_Factory () [protected]
Constructor.
Definition at line 38 of file jma_factory.cpp.
jma::JMA_Factory::~JMA_Factory () [protected, virtual]
Destructor.
Definition at line 42 of file jma_factory.cpp.
Member Function Documentation
Analyzer * jma::JMA_Factory::createAnalyzer () [virtual]
Create an instance of Analyzer.
Returns:
the pointer to instance
Definition at line 28 of file jma_factory.cpp.
Referenced by main(), and TEST().
Knowledge * jma::JMA_Factory::createKnowledge () [virtual]
Create an instance of Knowledge.
Returns:
the pointer to instance
Definition at line 33 of file jma_factory.cpp.
Referenced by main(), and TEST().
JMA_Factory * jma::JMA_Factory::instance () [static]
Create an instance of JMA_Factory.
Returns:
the pointer to instance
Definition at line 18 of file jma_factory.cpp.
The documentation for this class was generated from the following files:
include/jma_factory.h
source/src/jma_factory.cpp