Japanese Morphological Analyzer: MeCab::LearnerTagger Class Reference
MeCab::LearnerTagger Class Reference
#include <learner_tagger.h>
Public Member Functions
bool empty () const
void close ()
void clear ()
const char * what ()
LearnerTagger ()
virtual ~LearnerTagger ()
Protected Member Functions
LearnerNode * lookup (size_t)
bool connect (size_t, LearnerNode *)
bool viterbi ()
bool buildLattice ()
bool initList ()
Protected Attributes
LearnerTokenizer * tokenizer_
FreeList< LearnerPath > * path_freelist_
FeatureIndex * feature_index_
scoped_string begin__
const char * begin_
const char * end_
size_t len_
std::vector< LearnerNode * > beginNodeList_
std::vector< LearnerNode * > endNodeList_
whatlog what_
Detailed Description
Definition at line 21 of file learner_tagger.h.
Constructor & Destructor Documentation
MeCab::LearnerTagger::LearnerTagger () [inline, explicit]
Definition at line 45 of file learner_tagger.h.
virtual MeCab::LearnerTagger::~LearnerTagger () [inline, virtual]
Definition at line 47 of file learner_tagger.h.
Member Function Documentation
bool MeCab::LearnerTagger::buildLattice () [protected]
Definition at line 329 of file learner_tagger.cpp.
References beginNodeList_, connect(), endNodeList_, len_, and lookup().
Referenced by MeCab::DecoderLearnerTagger::parse(), and MeCab::EncoderLearnerTagger::read().
void MeCab::LearnerTagger::clear () [inline]
Definition at line 42 of file learner_tagger.h.
void MeCab::LearnerTagger::close () [inline]
Definition at line 41 of file learner_tagger.h.
Referenced by MeCab::DecoderLearnerTagger::open(), MeCab::EncoderLearnerTagger::open(), MeCab::DecoderLearnerTagger::~DecoderLearnerTagger(), and MeCab::EncoderLearnerTagger::~EncoderLearnerTagger().
bool MeCab::LearnerTagger::connect (size_t pos, LearnerNode * _rNode) [protected]
Definition at line 280 of file learner_tagger.cpp.
References MeCab::FreeList< T >::alloc(), MeCab::FeatureIndex::buildFeature(), CHECK_DIE, CHECK_FALSE, endNodeList_, feature_index_, path_freelist_, and MeCab::FeatureIndex::what().
Referenced by buildLattice().
bool MeCab::LearnerTagger::empty () const [inline]
Definition at line 40 of file learner_tagger.h.
References len_.
Referenced by MeCab::CRFLearner::run(), and MeCab::OLLearner::run().
bool MeCab::LearnerTagger::initList () [protected]
Definition at line 308 of file learner_tagger.cpp.
References begin_, beginNodeList_, end_, endNodeList_, MeCab::TokenizerImpl< N, P >::getBOSNode(), MeCab::TokenizerImpl< N, P >::getEOSNode(), len_, and tokenizer_.
Referenced by MeCab::DecoderLearnerTagger::parse(), and MeCab::EncoderLearnerTagger::read().
LearnerNode * MeCab::LearnerTagger::lookup (size_t pos) [protected]
Definition at line 273 of file learner_tagger.cpp.
References begin_, beginNodeList_, end_, MeCab::TokenizerImpl< N, P >::lookup(), and tokenizer_.
Referenced by buildLattice(), and MeCab::EncoderLearnerTagger::read().
bool MeCab::LearnerTagger::viterbi () [protected]
Definition at line 348 of file learner_tagger.cpp.
References beginNodeList_, MeCab::FeatureIndex::calcCost(), feature_index_, and len_.
Referenced by MeCab::EncoderLearnerTagger::gradient(), MeCab::EncoderLearnerTagger::online_update(), and MeCab::DecoderLearnerTagger::parse().
const char* MeCab::LearnerTagger::what () [inline]
Definition at line 43 of file learner_tagger.h.
References MeCab::whatlog::str(), and what_.
Referenced by MeCab::CRFLearner::run(), and MeCab::OLLearner::run().
Member Data Documentation
const char* MeCab::LearnerTagger::begin_ [protected]
Definition at line 27 of file learner_tagger.h.
Referenced by initList(), lookup(), MeCab::DecoderLearnerTagger::parse(), and MeCab::EncoderLearnerTagger::read().
scoped_string MeCab::LearnerTagger::begin__ [protected]
Definition at line 26 of file learner_tagger.h.
Referenced by MeCab::DecoderLearnerTagger::parse(), and MeCab::EncoderLearnerTagger::read().
std::vector<LearnerNode *> MeCab::LearnerTagger::beginNodeList_ [protected]
Definition at line 30 of file learner_tagger.h.
Referenced by buildLattice(), MeCab::EncoderLearnerTagger::gradient(), initList(), lookup(), MeCab::EncoderLearnerTagger::read(), and viterbi().
const char* MeCab::LearnerTagger::end_ [protected]
Definition at line 28 of file learner_tagger.h.
Referenced by initList(), and lookup().
std::vector<LearnerNode *> MeCab::LearnerTagger::endNodeList_ [protected]
Definition at line 31 of file learner_tagger.h.
Referenced by buildLattice(), connect(), MeCab::EncoderLearnerTagger::eval(), MeCab::EncoderLearnerTagger::gradient(), initList(), MeCab::EncoderLearnerTagger::online_update(), MeCab::DecoderLearnerTagger::parse(), and MeCab::EncoderLearnerTagger::read().
FeatureIndex* MeCab::LearnerTagger::feature_index_ [protected]
Definition at line 25 of file learner_tagger.h.
Referenced by connect(), MeCab::DecoderLearnerTagger::open(), MeCab::EncoderLearnerTagger::open(), MeCab::DecoderLearnerTagger::parse(), MeCab::EncoderLearnerTagger::read(), and viterbi().
size_t MeCab::LearnerTagger::len_ [protected]
Definition at line 29 of file learner_tagger.h.
Referenced by buildLattice(), empty(), MeCab::EncoderLearnerTagger::gradient(), initList(), MeCab::EncoderLearnerTagger::read(), and viterbi().
FreeList<LearnerPath>* MeCab::LearnerTagger::path_freelist_ [protected]
Definition at line 24 of file learner_tagger.h.
Referenced by connect(), MeCab::DecoderLearnerTagger::open(), MeCab::EncoderLearnerTagger::open(), and MeCab::DecoderLearnerTagger::parse().
LearnerTokenizer* MeCab::LearnerTagger::tokenizer_ [protected]
Definition at line 23 of file learner_tagger.h.
Referenced by initList(), lookup(), MeCab::DecoderLearnerTagger::open(), MeCab::EncoderLearnerTagger::open(), MeCab::DecoderLearnerTagger::parse(), and MeCab::EncoderLearnerTagger::read().
whatlog MeCab::LearnerTagger::what_ [protected]
Definition at line 32 of file learner_tagger.h.
Referenced by what().
The documentation for this class was generated from the following files:
source/libmecab/learner_tagger.h
source/libmecab/learner_tagger.cpp