Japanese Morphological Analyzer: MeCab::OLLearner Class Reference
MeCab::OLLearner Class Reference
Static Public Member Functions
static int run (Param *param)
Detailed Description
Definition at line 257 of file learner.cpp.
Member Function Documentation
static int MeCab::OLLearner::run (Param * param) [inline, static]
Definition at line 259 of file learner.cpp.
References MeCab::_max(), CHECK_DIE, MeCab::TokenizerImpl< N, P >::clear(), DCONF, DICRC, MeCab::LearnerTagger::empty(), MeCab::EncoderLearnerTagger::eval(), MeCab::FreeList< T >::free(), MeCab::Param::get(), MeCab::Param::load(), MeCab::EncoderLearnerTagger::online_update(), MeCab::EncoderLearnerTagger::open(), MeCab::TokenizerImpl< N, P >::open(), PATH_FREELIST_SIZE, MeCab::Param::program_name(), MeCab::EncoderLearnerTagger::read(), MeCab::Param::rest_args(), MeCab::LearnerTagger::what(), and MeCab::TokenizerImpl< N, P >::what().
The documentation for this class was generated from the following file:
source/libmecab/learner.cpp