Japanese Morphological Analyzer: jma::Sentence Class Reference
jma::Sentence Class Reference
Sentence saves the results of Japanese morphological analysis.
#include <sentence.h>
Public Member Functions
Sentence ()
Default Constructor.
Sentence (const char *pString)
Constructor with initial sentence string.
void setString (const char *pString)
Set the raw sentence string.
const char * getString (void) const
Get the raw sentence string.
int getListSize (void) const
Get the number of candidates of morphological analysis result.
int getCount (int nPos) const
Get the number of morphemes in candidate result nPos.
const char * getLexicon (int nPos, int nIdx) const
Get the string of morpheme nIdx in candidate result nPos.
int getPOS (int nPos, int nIdx) const
Get the POS index code of morpheme nIdx in candidate result nPos.
const char * getStrPOS (int nPos, int nIdx) const
Get the POS string of morpheme nIdx in candidate result nPos.
const char * getBaseForm (int nPos, int nIdx) const
Get the base form string of morpheme nIdx in candidate result nPos.
const char * getReadForm (int nPos, int nIdx) const
Get the reading form string of morpheme nIdx in candidate result nPos.
const char * getNormForm (int nPos, int nIdx) const
Get the normalized form string of morpheme nIdx in candidate result nPos.
const MorphemeList * getMorphemeList (int nPos) const
Get the MorphemeList of candidate result nPos.
double getScore (int nPos) const
Get the score of candidate result nPos.
void setScore (int nPos, double nScore)
Set the score of candidate result nPos.
int getOneBestIndex (void) const
Get the index of the candidate result, which has the highest score.
void addList (MorphemeList &morphemeList, double score=0.0)
Add a candidate result of morphological analysis.
Detailed Description
Sentence saves the results of Japanese morphological analysis.
Typically, the usage is like below:
 Sentence s;
 s.setString("...");
 Analyzer* analyzer = ...;
 analyzer->runWithSentence(s);
 // get n-best results
 for(int i=0; i<s.getListSize(); ++i)
 {
      for(int j=0; j<s.getCount(i); ++j)
      {
          const char* pLexicon = s.getLexicon(i, j);
          const char* strPOS = s.getStrPOS(i, j);
          const char* baseForm = s.getBaseForm(i, j);
          const char* readForm = s.getReadForm(i, j);
          const char* normForm = s.getNormForm(i, j);
          ...
      }
      double score = s.getScore(i);
      ...
 }
 // get one-best result
 int i = s.getOneBestIndex();
 for(int j=0; j<s.getCount(i); ++j)
 {
      const char* pLexicon = s.getLexicon(i, j);
      const char* strPOS = s.getStrPOS(i, j);
      const char* baseForm = s.getBaseForm(i, j);
      const char* readForm = s.getReadForm(i, j);
      const char* normForm = s.getNormForm(i, j);
      ...
 }
 ...
Definition at line 114 of file sentence.h.
Constructor & Destructor Documentation
jma::Sentence::Sentence ()
Default Constructor.
Definition at line 28 of file sentence.cpp.
jma::Sentence::Sentence (const char * pString)
Constructor with initial sentence string.
Definition at line 32 of file sentence.cpp.
Member Function Documentation
void jma::Sentence::addList (MorphemeList & morphemeList, double score = 0.0)
Add a candidate result of morphological analysis.
Parameters:
morphemeList the candidate result. After this function call, this parameter content would be cleared as its original content is swapped into candidates_.
score the score value of the candidate
Definition at line 114 of file sentence.cpp.
Referenced by jma::JMA_Analyzer::runNBest(), jma::JMA_Analyzer::runOneBest(), and TEST().
const char * jma::Sentence::getBaseForm (int nPos, int nIdx) const
Get the base form string of morpheme nIdx in candidate result nPos.
For example in Japanese, "来る" is returned as the base form of morpheme "来".
Parameters:
nPos candidate result index
nIdx morpheme index
Returns:
base form string
Definition at line 74 of file sentence.cpp.
Referenced by main(), JMA_AnalyzerTest::runWithSentenceTest(), TEST(), and testWithSentence().
int jma::Sentence::getCount (int nPos) const
Get the number of morphemes in candidate result nPos.
Parameters:
nPos candidate result index
Returns:
the number of morphemes
Definition at line 54 of file sentence.cpp.
Referenced by main(), JMA_AnalyzerTest::runWithSentenceTest(), TEST(), and testWithSentence().
const char * jma::Sentence::getLexicon (int nPos, int nIdx) const
Get the string of morpheme nIdx in candidate result nPos.
Parameters:
nPos candidate result index
nIdx morpheme index
Returns:
morpheme string
Definition at line 59 of file sentence.cpp.
Referenced by main(), JMA_AnalyzerTest::runWithSentenceTest(), TEST(), and testWithSentence().
int jma::Sentence::getListSize (void) const
Get the number of candidates of morphological analysis result.
Returns:
the number of candidates
Definition at line 49 of file sentence.cpp.
Referenced by main(), JMA_AnalyzerTest::runWithSentenceTest(), TEST(), and testWithSentence().
const MorphemeList * jma::Sentence::getMorphemeList (int nPos) const
Get the MorphemeList of candidate result nPos.
Parameters:
nPos candidate result index
Returns:
the MorphemeList
Definition at line 89 of file sentence.cpp.
const char * jma::Sentence::getNormForm (int nPos, int nIdx) const
Get the normalized form string of morpheme nIdx in candidate result nPos.
For example in Japanese, "渡辺" is returned as the normalized form of morpheme "渡邊".
Parameters:
nPos candidate result index
nIdx morpheme index
Returns:
normalized form string, if no normalized form exists, empty string "" is returned
Definition at line 84 of file sentence.cpp.
Referenced by main(), JMA_AnalyzerTest::runWithSentenceTest(), TEST(), and testWithSentence().
int jma::Sentence::getOneBestIndex (void) const
Get the index of the candidate result, which has the highest score.
Returns:
candidate result index, -1 is returned if there is no candidate result.
Definition at line 104 of file sentence.cpp.
Referenced by main(), JMA_AnalyzerTest::runWithSentenceTest(), TEST(), and testWithSentence().
int jma::Sentence::getPOS (int nPos, int nIdx) const
Get the POS index code of morpheme nIdx in candidate result nPos.
Parameters:
nPos candidate result index
nIdx morpheme index
Returns:
POS index code, -1 for non POS available
Definition at line 64 of file sentence.cpp.
Referenced by JMA_AnalyzerTest::runWithSentenceTest(), and TEST().
const char * jma::Sentence::getReadForm (int nPos, int nIdx) const
Get the reading form string of morpheme nIdx in candidate result nPos.
For example in Japanese, "くる" is returned as the reading form of morpheme "来る".
Parameters:
nPos candidate result index
nIdx morpheme index
Returns:
reading form string, if no reading form exists, empty string "" is returned
Definition at line 79 of file sentence.cpp.
Referenced by main(), JMA_AnalyzerTest::runWithSentenceTest(), TEST(), and testWithSentence().
double jma::Sentence::getScore (int nPos) const
Get the score of candidate result nPos.
Parameters:
nPos candidate result index
Returns:
the score value
Definition at line 94 of file sentence.cpp.
Referenced by main(), JMA_AnalyzerTest::runWithSentenceTest(), TEST(), and testWithSentence().
const char * jma::Sentence::getString (void) const
Get the raw sentence string.
Returns:
value of the raw string
Definition at line 44 of file sentence.cpp.
Referenced by jma::JMA_Analyzer::runNBest(), jma::JMA_Analyzer::runOneBest(), JMA_AnalyzerTest::runWithSentenceTest(), and TEST().
const char * jma::Sentence::getStrPOS (int nPos, int nIdx) const
Get the POS string of morpheme nIdx in candidate result nPos.
Parameters:
nPos candidate result index
nIdx morpheme index
Returns:
POS string
Definition at line 69 of file sentence.cpp.
Referenced by main(), JMA_AnalyzerTest::runWithSentenceTest(), TEST(), and testWithSentence().
void jma::Sentence::setScore (int nPos, double nScore)
Set the score of candidate result nPos.
Parameters:
nPos candidate result index
nScore the score value
Definition at line 99 of file sentence.cpp.
Referenced by TEST().
void jma::Sentence::setString (const char * pString)
Set the raw sentence string.
Parameters:
pString value of the raw string
Attention:
the previous analysis results will be removed.
Definition at line 37 of file sentence.cpp.
Referenced by main(), JMA_AnalyzerTest::runWithSentenceTest(), and testWithSentence().
The documentation for this class was generated from the following files:
include/sentence.h
source/src/sentence.cpp