Japanese Morphological Analyzer: MeCab::Connector Class Reference
MeCab::Connector Class Reference
#include <connector.h>
Public Member Functions
bool open (const Param &param)
void close ()
void clear ()
const char * what ()
size_t left_size () const
size_t right_size () const
void set_left_size (size_t lsize)
void set_right_size (size_t rsize)
int cost (const Node *lNode, const Node *rNode) const
short * mutable_matrix ()
const short * matrix () const
bool openText (const char *filename)
bool open (const char *filename, const char *mode="r")
bool is_valid (size_t lid, size_t rid) const
Connector ()
virtual ~Connector ()
Static Public Member Functions
static bool compile (const char *, const char *)
Detailed Description
Definition at line 17 of file connector.h.
Constructor & Destructor Documentation
MeCab::Connector::Connector () [inline, explicit]
Definition at line 56 of file connector.h.
virtual MeCab::Connector::~Connector () [inline, virtual]
Definition at line 59 of file connector.h.
References close().
Member Function Documentation
void MeCab::Connector::clear () [inline]
Definition at line 29 of file connector.h.
void MeCab::Connector::close ()
Definition at line 47 of file connector.cpp.
References MMAP_CLOSE.
Referenced by ~Connector().
bool MeCab::Connector::compile (const char * ifile, const char * ofile) [static]
Definition at line 65 of file connector.cpp.
References BUF_SIZE, c, CHECK_DIE, matrix(), MATRIX_DEF_DEFAULT, MeCab::progress_bar(), and MeCab::tokenize2().
Referenced by MeCab::DictionaryComplier::run().
int MeCab::Connector::cost (const Node * lNode, const Node * rNode) const [inline]
Definition at line 39 of file connector.h.
bool MeCab::Connector::is_valid (size_t lid, size_t rid) const [inline]
Definition at line 50 of file connector.h.
Referenced by MeCab::Dictionary::compile().
size_t MeCab::Connector::left_size () const [inline]
Definition at line 33 of file connector.h.
Referenced by MeCab::Dictionary::compile().
const short* MeCab::Connector::matrix () const [inline]
Definition at line 45 of file connector.h.
Referenced by compile().
short* MeCab::Connector::mutable_matrix () [inline]
Definition at line 44 of file connector.h.
bool MeCab::Connector::open (const char * filename, const char * mode = "r")
Definition at line 26 of file connector.cpp.
References MeCab::Mmap< T >::begin(), CHECK_CLOSE_FALSE, MMAP_OPEN, and MeCab::Mmap< T >::size().
bool MeCab::Connector::open (const Param & param)
Definition at line 18 of file connector.cpp.
References MeCab::create_filename(), MeCab::Param::get(), and MATRIX_FILE.
Referenced by MeCab::Dictionary::compile(), and MeCab::TaggerImpl::open().
bool MeCab::Connector::openText (const char * filename)
Definition at line 51 of file connector.cpp.
References BUF_SIZE, CHECK_CLOSE_FALSE, CHECK_DIE, and MeCab::tokenize2().
Referenced by MeCab::Dictionary::compile().
size_t MeCab::Connector::right_size () const [inline]
Definition at line 34 of file connector.h.
Referenced by MeCab::Dictionary::compile().
void MeCab::Connector::set_left_size (size_t lsize) [inline]
Definition at line 36 of file connector.h.
Referenced by MeCab::Dictionary::compile().
void MeCab::Connector::set_right_size (size_t rsize) [inline]
Definition at line 37 of file connector.h.
Referenced by MeCab::Dictionary::compile().
const char* MeCab::Connector::what () [inline]
Definition at line 31 of file connector.h.
References MeCab::whatlog::str().
Referenced by MeCab::TaggerImpl::open().
The documentation for this class was generated from the following files:
source/libmecab/connector.h
source/libmecab/connector.cpp