Japanese Morphological Analyzer: jma::GenericArray< ArrayType > Class Template Reference
jma::GenericArray< ArrayType > Class Template Reference
GenericArray can accessing the content in the array quickly and dynamically increment.
#include <generic_array.h>
Public Member Functions
GenericArray (bool pIgnDupl=true)
Create a default GenericArray with none content.
GenericArray (ArrayType *d, size_t s, bool pIgnDupl=true)
Create a GenerecArray with existent array.
GenericArray (const GenericArray &other)
Cpoy an instance from other GenericArray.
GenericArray (const vector< ArrayType > &vec)
Create an instance from a vector.
~GenericArray ()
bool insert (const ArrayType &ele)
Insert a new length at the end of the GenericArray.
bool empty ()
Whether the array is empty.
bool contains (const ArrayType &ele)
Whether the ele is contained in the Array.
Public Attributes
ArrayType * data
Store the elements.
size_t size
The size of the elements.
Detailed Description
template<typename ArrayType>
class jma::GenericArray< ArrayType >
GenericArray can accessing the content in the array quickly and dynamically increment.
GenericArray can accessing the content in the array quickly and dynamically increment. And the type that GenericArray stores is based on the template parameter ArrayType.
Definition at line 25 of file generic_array.h.
Constructor & Destructor Documentation
template<typename ArrayType> jma::GenericArray< ArrayType >::GenericArray (bool pIgnDupl = true) [inline]
Create a default GenericArray with none content.
Parameters:
pIgnDupl whether ignore duplicate elements, default is true
Definition at line 32 of file generic_array.h.
template<typename ArrayType> jma::GenericArray< ArrayType >::GenericArray (ArrayType * d, size_t s, bool pIgnDupl = true) [inline]
Create a GenerecArray with existent array.
This method DO NOT copy the the array
Parameters:
d existent array pointer
s existent array length
pIgnDupl whether ignore duplicate elements, default is ture
Definition at line 44 of file generic_array.h.
template<typename ArrayType> jma::GenericArray< ArrayType >::GenericArray (const GenericArray< ArrayType > & other) [inline]
Cpoy an instance from other GenericArray.
It is deep copy.
Parameters:
other existent GenericArray
Definition at line 53 of file generic_array.h.
template<typename ArrayType> jma::GenericArray< ArrayType >::GenericArray (const vector< ArrayType > & vec) [inline]
Create an instance from a vector.
Parameters:
vec outer vector
Definition at line 68 of file generic_array.h.
template<typename ArrayType> jma::GenericArray< ArrayType >::~GenericArray () [inline]
Definition at line 76 of file generic_array.h.
Member Function Documentation
template<typename ArrayType> bool jma::GenericArray< ArrayType >::contains (const ArrayType & ele) [inline]
Whether the ele is contained in the Array.
Parameters:
ele the element to be checked
Returns:
true if the element is contained in the Array
Definition at line 132 of file generic_array.h.
Referenced by jma::GenericArray< unsigned int >::insert(), and jma::JMA_Knowledge::isSentenceSeparator().
template<typename ArrayType> bool jma::GenericArray< ArrayType >::empty () [inline]
Whether the array is empty.
Returns:
true if the array is empty
Definition at line 122 of file generic_array.h.
template<typename ArrayType> bool jma::GenericArray< ArrayType >::insert (const ArrayType & ele) [inline]
Insert a new length at the end of the GenericArray.
Parameters:
ele new element
Returns:
whether insert successfully
Definition at line 88 of file generic_array.h.
Referenced by jma::JMA_Knowledge::addSentenceSeparator(), and jma::JMA_Knowledge::loadSentenceSeparatorConfig().
Member Data Documentation
template<typename ArrayType> ArrayType* jma::GenericArray< ArrayType >::data
Store the elements.
Definition at line 145 of file generic_array.h.
Referenced by jma::GenericArray< unsigned int >::contains(), jma::GenericArray< unsigned int >::GenericArray(), jma::GenericArray< unsigned int >::insert(), and jma::GenericArray< unsigned int >::~GenericArray().
template<typename ArrayType> size_t jma::GenericArray< ArrayType >::size
The size of the elements.
Definition at line 150 of file generic_array.h.
Referenced by jma::GenericArray< unsigned int >::contains(), jma::GenericArray< unsigned int >::empty(), jma::GenericArray< unsigned int >::GenericArray(), and jma::GenericArray< unsigned int >::insert().
The documentation for this class was generated from the following file:
source/include/generic_array.h