Japanese Morphological Analyzer: MeCab::MemoryPool< _Key, _Value > Class Template Reference
MeCab::MemoryPool< _Key, _Value > Class Template Reference
#include <mempool.h>
Public Types
typedef _Key key_type
typedef _Value value_type
Public Member Functions
MemoryPool ()
virtual ~MemoryPool ()
void lock ()
void unlock ()
value_type * get (const key_type &key)
void release (value_type *m=0)
Detailed Description
template<typename _Key, typename _Value>
class MeCab::MemoryPool< _Key, _Value >
Definition at line 37 of file mempool.h.
Member Typedef Documentation
template<typename _Key, typename _Value> typedef _Key MeCab::MemoryPool< _Key, _Value >::key_type
Definition at line 44 of file mempool.h.
template<typename _Key, typename _Value> typedef _Value MeCab::MemoryPool< _Key, _Value >::value_type
Definition at line 45 of file mempool.h.
Constructor & Destructor Documentation
template<typename _Key, typename _Value> MeCab::MemoryPool< _Key, _Value >::MemoryPool () [inline, explicit]
Definition at line 47 of file mempool.h.
template<typename _Key, typename _Value> virtual MeCab::MemoryPool< _Key, _Value >::~MemoryPool () [inline, virtual]
Definition at line 49 of file mempool.h.
References MeCab::Mutex::lock(), and MeCab::Mutex::unlock().
Member Function Documentation
template<typename _Key, typename _Value> value_type* MeCab::MemoryPool< _Key, _Value >::get (const key_type & key) [inline]
Definition at line 60 of file mempool.h.
References MeCab::Mutex::lock(), and MeCab::Mutex::unlock().
template<typename _Key, typename _Value> void MeCab::MemoryPool< _Key, _Value >::lock () [inline]
Definition at line 57 of file mempool.h.
References MeCab::Mutex::lock().
template<typename _Key, typename _Value> void MeCab::MemoryPool< _Key, _Value >::release (value_type * m = 0) [inline]
Definition at line 80 of file mempool.h.
References MeCab::Mutex::lock(), and MeCab::Mutex::unlock().
template<typename _Key, typename _Value> void MeCab::MemoryPool< _Key, _Value >::unlock () [inline]
Definition at line 58 of file mempool.h.
References MeCab::Mutex::unlock().
The documentation for this class was generated from the following file:
source/libmecab/mempool.h