Japanese Morphological Analyzer: MeCab::DictionaryGenerator Class Reference
MeCab::DictionaryGenerator Class Reference
Static Public Member Functions
static int run (int argc, char **argv)
Detailed Description
Definition at line 45 of file dictionary_generator.cpp.
Member Function Documentation
static int MeCab::DictionaryGenerator::run (int argc, char ** argv) [inline, static]
Definition at line 198 of file dictionary_generator.cpp.
References MeCab::ContextID::build(), CHAR_PROPERTY_DEF_FILE, MeCab::Dictionary::charset(), CHECK_DIE, MeCab::copy(), COPYRIGHT, DCONF, DICRC, MeCab::enum_csv_dictionaries(), FEATURE_FILE, MeCab::Param::get(), MeCab::Param::help_version(), LEFT_ID_FILE, MeCab::Param::load(), MATRIX_DEF_FILE, OCONF, MeCab::DictionaryRewriter::open(), MeCab::DecoderFeatureIndex::open(), MeCab::CharProperty::open(), MeCab::Dictionary::open(), MeCab::Param::open(), MeCab::remove_pathname(), REWRITE_FILE, RIGHT_ID_FILE, MeCab::ContextID::save(), MeCab::Param::set(), SYS_DIC_FILE, MeCab::toLower(), UNK_DEF_FILE, MeCab::FeatureIndex::what(), and MeCab::Param::what().
Referenced by mecab_dict_gen().
The documentation for this class was generated from the following file:
source/libmecab/dictionary_generator.cpp