Japanese Morphological Analyzer: jma::JMA_Knowledge Class Reference
jma::JMA_Knowledge Class Reference
JMA_Knowledge manages the linguistic information for Japanese morphological analysis.
#include <jma_knowledge.h>
Public Types
typedef std::map< std::string,
MorphemeList > DecompMap
The map to decompose user defined noun.
Public Member Functions
JMA_Knowledge ()
Constructor.
virtual ~JMA_Knowledge ()
Destructor.
virtual int loadDict ()
Load the dictionaries, which are set by setSystemDict() and addUserDict().
virtual int loadStopWordDict (const char *fileName)
Load the stop-word dictionary file, which is in text format.
virtual int setKeywordPOS (const std::vector< std::string > &posVec)
Set the part-of-speech tags as keywords.
virtual int encodeSystemDict (const char *txtDirPath, const char *binDirPath, EncodeType binEncodeType)
Encode the system dictionary files from text to binary file.
MeCab::Tagger * createTagger () const
Create tagger by loading dictionary files.
const POSTable & getPOSTable () const
Get the part-of-speech tags table.
const CharTable & getKanaTable () const
Get the mapping table to convert between Hiragana and Katakana characters.
const CharTable & getWidthTable () const
Get the mapping table to convert between half and full width characters.
const CharTable & getCaseTable () const
Get the mapping table to convert between lower and upper case characters.
const DecompMap & getDecompMap () const
Get the map to decompose user defined noun.
bool isStopWord (const std::string &word) const
Whether the specific word is stop word.
unsigned int stopWordCount () const
Get the number of stop words loaded.
bool isSentenceSeparator (const char *p) const
Check whether is a seperator of sentence.
bool isKeywordPOS (int pos) const
Whether the specific part-of-speech tag is keyword.
unsigned int keywordPOSCount () const
Get the number of keyword POS.
int getBaseFormOffset () const
Get the feature offset of base form indexed from zero.
int getReadFormOffset () const
Get the feature offset of reading form indexed from zero.
int getNormFormOffset () const
Get the feature offset of normalized form indexed from zero.
int getUserNounPOSIndex () const
Get the part-of-speech index code of user defined noun.
JMA_CType * getCType ()
Get the current JMA_CType.
Detailed Description
JMA_Knowledge manages the linguistic information for Japanese morphological analysis.
Definition at line 38 of file jma_knowledge.h.
Member Typedef Documentation
typedef std::map<std::string, MorphemeList> jma::JMA_Knowledge::DecompMap
The map to decompose user defined noun.
The key of the map is the user defined noun, such as "本田総一郎", the value of the map is a list of decomposed morphemes, such as "本田", "総一郎", the decomposed morpheme includes Morpheme::lexicon_ and Morpheme::readForm_, if Morpheme::readForm_ is an empty string, no read form is defined.
Definition at line 48 of file jma_knowledge.h.
Constructor & Destructor Documentation
jma::JMA_Knowledge::JMA_Knowledge ()
Constructor.
Definition at line 172 of file jma_knowledge.cpp.
jma::JMA_Knowledge::~JMA_Knowledge () [virtual]
Destructor.
Definition at line 179 of file jma_knowledge.cpp.
References jma::JMA_Dictionary::close(), jma::JMA_UserDictionary::release(), and jma::Knowledge::systemDictPath_.
Member Function Documentation
MeCab::Tagger * jma::JMA_Knowledge::createTagger () const
Create tagger by loading dictionary files.
Returns:
pointer to tagger. 0 for fail, otherwise the life cycle of the tagger should be maintained by the caller.
Definition at line 304 of file jma_knowledge.cpp.
References jma::Knowledge::systemDictPath_.
Referenced by loadDict(), JMA_Knowledge_Test::loadDictTest(), main(), and jma::JMA_Analyzer::setKnowledge().
virtual int jma::JMA_Knowledge::encodeSystemDict (const char * txtDirPath, const char * binDirPath, EncodeType binEncodeType) [virtual]
Encode the system dictionary files from text to binary file.
Parameters:
txtDirPath the directory path of text files
binDirPath the directory path of binary files
binEncodeType the encoding type of binary system dictionary
Returns:
0 for fail, 1 for success
Precondition:
both txtDirPath and binDirPath are assumed as the directory paths that already exists. If any of the directory paths does not exist, 0 would be returned for fail.
int jma::JMA_Knowledge::getBaseFormOffset () const
Get the feature offset of base form indexed from zero.
For example, if an entry in dictionary file contains the features like "動詞,自立,*,*,一段,未然形,見る,ミ,ミ", the feature offset of base form "見る" would be 6.
Returns:
the feature offset
Definition at line 725 of file jma_knowledge.cpp.
Referenced by JMA_Knowledge_Test::loadDictTest().
const CharTable & jma::JMA_Knowledge::getCaseTable () const
Get the mapping table to convert between lower and upper case characters.
Returns:
reference to the table instance.
Definition at line 344 of file jma_knowledge.cpp.
Referenced by JMA_Knowledge_Test::loadDictTest(), and jma::JMA_Analyzer::setKnowledge().
JMA_CType * jma::JMA_Knowledge::getCType ()
Get the current JMA_CType.
Returns:
the current JMA_CType
Definition at line 745 of file jma_knowledge.cpp.
Referenced by jma::JMA_Analyzer::convertCharacters(), JMA_Knowledge_Test::loadDictTest(), jma::JMA_Analyzer::runWithSentence(), jma::JMA_Analyzer::runWithStream(), jma::JMA_Analyzer::runWithString(), jma::JMA_Analyzer::setKnowledge(), and jma::JMA_Analyzer::splitSentence().
const JMA_Knowledge::DecompMap & jma::JMA_Knowledge::getDecompMap () const
Get the map to decompose user defined noun.
Returns:
reference to the map instance.
Definition at line 349 of file jma_knowledge.cpp.
Referenced by JMA_Knowledge_Test::loadDictTest(), and jma::JMA_Analyzer::setKnowledge().
const CharTable & jma::JMA_Knowledge::getKanaTable () const
Get the mapping table to convert between Hiragana and Katakana characters.
Returns:
reference to the table instance.
Definition at line 334 of file jma_knowledge.cpp.
Referenced by JMA_Knowledge_Test::loadDictTest(), and jma::JMA_Analyzer::setKnowledge().
int jma::JMA_Knowledge::getNormFormOffset () const
Get the feature offset of normalized form indexed from zero.
For example, if an entry in dictionary file contains the features like "名詞,固有名詞,人名,姓,*,*,渡邊,わたなべ,ワタナベ,渡辺", the feature offset of normalized form "渡辺" would be 9.
Returns:
the feature offset
Definition at line 735 of file jma_knowledge.cpp.
Referenced by JMA_Knowledge_Test::loadDictTest().
const POSTable & jma::JMA_Knowledge::getPOSTable () const
Get the part-of-speech tags table.
Returns:
reference to the table instance.
Definition at line 329 of file jma_knowledge.cpp.
Referenced by JMA_Knowledge_Test::loadDictTest(), and jma::JMA_Analyzer::setKnowledge().
int jma::JMA_Knowledge::getReadFormOffset () const
Get the feature offset of reading form indexed from zero.
For example, if an entry in dictionary file contains the features like "動詞,自立,*,*,一段,未然形,見る,ミ,ミ", the feature offset of reading form "ミ" would be 7.
Returns:
the feature offset
Definition at line 730 of file jma_knowledge.cpp.
Referenced by JMA_Knowledge_Test::loadDictTest().
int jma::JMA_Knowledge::getUserNounPOSIndex () const
Get the part-of-speech index code of user defined noun.
Returns:
the POS index code, -1 for not defined.
Definition at line 740 of file jma_knowledge.cpp.
References jma::POSTable::getIndexFromAlphaPOS().
Referenced by JMA_Knowledge_Test::loadDictTest().
const CharTable & jma::JMA_Knowledge::getWidthTable () const
Get the mapping table to convert between half and full width characters.
Returns:
reference to the table instance.
Definition at line 339 of file jma_knowledge.cpp.
Referenced by JMA_Knowledge_Test::loadDictTest(), and jma::JMA_Analyzer::setKnowledge().
bool jma::JMA_Knowledge::isKeywordPOS (int pos) const
Whether the specific part-of-speech tag is keyword.
Parameters:
pos the index code of part-of-speech tag
Returns:
whether is keyword
Definition at line 712 of file jma_knowledge.cpp.
bool jma::JMA_Knowledge::isSentenceSeparator (const char * p) const
Check whether is a seperator of sentence.
Parameters:
p pointer to the character string, it would check all the characters until null character
Returns:
true for separator, false for non separator.
Definition at line 707 of file jma_knowledge.cpp.
Referenced by JMA_Knowledge_Test::loadDictTest(), and main().
bool jma::JMA_Knowledge::isStopWord (const std::string & word) const
Whether the specific word is stop word.
Parameters:
word the word to be checked
Returns:
whether the word is in the stop word list
Definition at line 697 of file jma_knowledge.cpp.
Referenced by main().
unsigned int jma::JMA_Knowledge::keywordPOSCount () const
Get the number of keyword POS.
Returns:
the number of keyword POS.
Definition at line 720 of file jma_knowledge.cpp.
int jma::JMA_Knowledge::loadDict () [virtual]
Load the dictionaries, which are set by setSystemDict() and addUserDict().
Returns:
0 for fail, 1 for success
Precondition:
the directory path of system dictionary should be set by setSystemDict().
if any user dictionary file need to be loaded, the file name should be added by addUserDict().
Implements jma::Knowledge.
Definition at line 445 of file jma_knowledge.cpp.
References jma::createFilePath(), createTagger(), jma::Knowledge::encodeStr(), jma::Knowledge::getEncodeType(), jma::POSTable::loadCombineRule(), jma::CharTable::loadConfig(), jma::POSTable::loadConfig(), jma::JMA_Dictionary::open(), and jma::Knowledge::systemDictPath_.
Referenced by JMA_Knowledge_Test::loadDictTest(), main(), and JMA_AnalyzerTest::SetUp().
int jma::JMA_Knowledge::loadStopWordDict (const char * fileName) [virtual]
Load the stop-word dictionary file, which is in text format.
The words in this file are ignored in the morphological analysis result.
Parameters:
fileName the file name
Returns:
0 for fail, 1 for success
Implements jma::Knowledge.
Definition at line 543 of file jma_knowledge.cpp.
Referenced by main().
int jma::JMA_Knowledge::setKeywordPOS (const std::vector< std::string > & posVec) [virtual]
Set the part-of-speech tags as keywords.
If this method is not called or posVec is empty, the results of Analyzer::runWith*() would contain all words. Otherwise, if posVec is not empty, the results of Analyzer::runWith*() would only contain the words with part-of-speech tags specified by this method.
Parameters:
posVec the vector of part-of-speech tags in alphabet format, such as "NC-G"
Returns:
the number of part-of-speech tags successfully set
Attention:
This method should be called after loadDict(), otherwise no keyword part-of-speech tag would be set
Implements jma::Knowledge.
Definition at line 1048 of file jma_knowledge.cpp.
References jma::POSTable::getIndexFromAlphaPOS().
unsigned int jma::JMA_Knowledge::stopWordCount () const
Get the number of stop words loaded.
Returns:
the number of stop words loaded.
Definition at line 702 of file jma_knowledge.cpp.
The documentation for this class was generated from the following files:
source/include/jma_knowledge.h
source/src/jma_knowledge.cpp