Japanese Morphological Analyzer: jma::JMA_CType Class Reference
jma::JMA_CType Class Reference
JMA_CType gives the character type information.
#include <jma_ctype.h>
Public Member Functions
virtual ~JMA_CType ()
Destrucor.
virtual unsigned int getByteCount (const char *p) const =0
Get the byte count of the first character pointed by p, which character is in a specific encoding.
virtual bool isSpace (const char *p) const =0
Check whether is white-space character.
virtual string replaceSpaces (const char *str, char replacement)=0
Replace space characters with replacement character.
size_t length (const char *p) const
Get the number of the characters in the p.
Static Public Member Functions
static JMA_CType * instance (Knowledge::EncodeType type)
Create an instance of CMA_CType based on the character encode type.
Detailed Description
JMA_CType gives the character type information.
CMA_CType gives the character type information.
Definition at line 24 of file jma_ctype.h.
Constructor & Destructor Documentation
jma::JMA_CType::~JMA_CType () [virtual]
Destrucor.
Definition at line 39 of file jma_ctype.cpp.
Member Function Documentation
virtual unsigned int jma::JMA_CType::getByteCount (const char * p) const [pure virtual]
Get the byte count of the first character pointed by p, which character is in a specific encoding.
Parameters:
p pointer to the character string
Returns:
the count of bytes.
Implemented in jma::JMA_CType_EUCJP, jma::JMA_CType_SJIS, and jma::JMA_CType_UTF8.
Referenced by jma::JMA_Knowledge::isSentenceSeparator(), length(), jma::JMA_Knowledge::loadSentenceSeparatorConfig(), jma::CTypeTokenizer::next(), and testGetByteCount().
JMA_CType * jma::JMA_CType::instance (Knowledge::EncodeType type) [static]
Create an instance of CMA_CType based on the character encode type.
Parameters:
type the character encode type
Returns:
the pointer to instance
Definition at line 20 of file jma_ctype.cpp.
References jma::Knowledge::ENCODE_TYPE_EUCJP, jma::Knowledge::ENCODE_TYPE_SJIS, and jma::Knowledge::ENCODE_TYPE_UTF8.
Referenced by jma::JMA_Knowledge::onEncodeTypeChange().
virtual bool jma::JMA_CType::isSpace (const char * p) const [pure virtual]
Check whether is white-space character.
White-space characters are " \t\n\v\f\r", and also space character in specific encoding.
Parameters:
p pointer to the character string
Returns:
true for white-space character, false for non white-space character.
Implemented in jma::JMA_CType_EUCJP, jma::JMA_CType_SJIS, and jma::JMA_CType_UTF8.
Referenced by jma::JMA_Knowledge::isStopWord().
size_t jma::JMA_CType::length (const char * p) const
Get the number of the characters in the p.
Parameters:
p pointer to the string to be checked
Returns:
the number of the characters in the p
Definition at line 43 of file jma_ctype.cpp.
References getByteCount().
Referenced by testGetByteCount().
virtual string jma::JMA_CType::replaceSpaces (const char * str, char replacement) [pure virtual]
Replace space characters with replacement character.
Parameters:
str the input string
replacement the character to replace the space characters
Returns:
the output string
Implemented in jma::JMA_CType_EUCJP, jma::JMA_CType_SJIS, and jma::JMA_CType_UTF8.
Referenced by jma::JMA_Analyzer::runWithSentence(), jma::JMA_Analyzer::runWithStream(), and jma::JMA_Analyzer::runWithString().
The documentation for this class was generated from the following files:
source/include/jma_ctype.h
source/src/jma_ctype.cpp