Japanese Morphological Analyzer: MeCab::Mmap< T > Class Template Reference
MeCab::Mmap< T > Class Template Reference
#include <mmap.h>
Public Member Functions
T & operator[] (size_t n)
const T & operator[] (size_t n) const
T * begin ()
const T * begin () const
T * end ()
const T * end () const
size_t size ()
const char * what ()
const char * file_name ()
size_t file_size ()
bool empty ()
bool open (const char *filename, const char *mode="r")
void close ()
Mmap ()
virtual ~Mmap ()
Detailed Description
template<class T>
class MeCab::Mmap< T >
Definition at line 66 of file mmap.h.
Constructor & Destructor Documentation
template<class T> MeCab::Mmap< T >::Mmap () [inline]
Definition at line 213 of file mmap.h.
template<class T> virtual MeCab::Mmap< T >::~Mmap () [inline, virtual]
Definition at line 216 of file mmap.h.
Member Function Documentation
template<class T> const T* MeCab::Mmap< T >::begin () const [inline]
Definition at line 85 of file mmap.h.
template<class T> T* MeCab::Mmap< T >::begin () [inline]
Definition at line 84 of file mmap.h.
Referenced by MeCab::copy(), MeCab::DecoderFeatureIndex::open(), MeCab::Dictionary::open(), MeCab::Connector::open(), and MeCab::CharProperty::open().
template<class T> void MeCab::Mmap< T >::close () [inline]
Definition at line 188 of file mmap.h.
Referenced by MeCab::DecoderFeatureIndex::close(), MeCab::Mmap< char >::open(), and MeCab::Mmap< char >::~Mmap().
template<class T> bool MeCab::Mmap< T >::empty () [inline]
Definition at line 92 of file mmap.h.
template<class T> const T* MeCab::Mmap< T >::end () const [inline]
Definition at line 87 of file mmap.h.
template<class T> T* MeCab::Mmap< T >::end () [inline]
Definition at line 86 of file mmap.h.
Referenced by MeCab::Dictionary::open().
template<class T> const char* MeCab::Mmap< T >::file_name () [inline]
Definition at line 90 of file mmap.h.
template<class T> size_t MeCab::Mmap< T >::file_size () [inline]
Definition at line 91 of file mmap.h.
template<class T> bool MeCab::Mmap< T >::open (const char * filename, const char * mode = "r") [inline]
Definition at line 147 of file mmap.h.
Referenced by MeCab::copy(), and MeCab::DecoderFeatureIndex::open().
template<class T> const T& MeCab::Mmap< T >::operator[] (size_t n) const [inline]
Definition at line 83 of file mmap.h.
template<class T> T& MeCab::Mmap< T >::operator[] (size_t n) [inline]
Definition at line 82 of file mmap.h.
template<class T> size_t MeCab::Mmap< T >::size () [inline]
Definition at line 88 of file mmap.h.
Referenced by MeCab::copy(), MeCab::Mmap< char >::end(), MeCab::Dictionary::open(), MeCab::Connector::open(), and MeCab::CharProperty::open().
template<class T> const char* MeCab::Mmap< T >::what () [inline]
Definition at line 89 of file mmap.h.
Referenced by MeCab::copy(), and MeCab::DecoderFeatureIndex::open().
The documentation for this class was generated from the following file:
source/libmecab/mmap.h