Japanese Morphological Analyzer: MeCab::ChunkFreeList< T > Class Template Reference
MeCab::ChunkFreeList< T > Class Template Reference
#include <freelist.h>
Public Member Functions
void free ()
T * alloc (T *src)
T * alloc (size_t req=1)
ChunkFreeList (size_t _size)
virtual ~ChunkFreeList ()
Detailed Description
template<class T>
class MeCab::ChunkFreeList< T >
Definition at line 44 of file freelist.h.
Constructor & Destructor Documentation
template<class T> MeCab::ChunkFreeList< T >::ChunkFreeList (size_t _size) [inline, explicit]
Definition at line 77 of file freelist.h.
template<class T> virtual MeCab::ChunkFreeList< T >::~ChunkFreeList () [inline, virtual]
Definition at line 80 of file freelist.h.
Member Function Documentation
template<class T> T* MeCab::ChunkFreeList< T >::alloc (size_t req = 1) [inline]
Definition at line 60 of file freelist.h.
template<class T> T* MeCab::ChunkFreeList< T >::alloc (T * src) [inline]
Definition at line 54 of file freelist.h.
Referenced by MeCab::ChunkFreeList< char >::alloc(), and MeCab::FeatureIndex::strdup().
template<class T> void MeCab::ChunkFreeList< T >::free () [inline]
Definition at line 52 of file freelist.h.
Referenced by MeCab::DecoderFeatureIndex::clear().
The documentation for this class was generated from the following file:
source/libmecab/freelist.h