Japanese Morphological Analyzer: MeCab::Dictionary Class Reference
MeCab::Dictionary Class Reference
#include <dictionary.h>
Public Types
typedef
Darts::DoubleArray::result_pair_type result_type
Public Member Functions
bool open (const char *filename, const char *mode="r")
void close ()
size_t commonPrefixSearch (const char *key, size_t len, result_type *result, size_t rlen)
result_type exactMatchSearch (const char *key)
bool isCompatible (const Dictionary &d) const
const char * filename () const
const char * charset () const
unsigned short version () const
size_t size () const
int type () const
size_t lsize () const
size_t rsize () const
const Token * token (const result_type &n) const
size_t token_size (const result_type &n) const
const char * feature (const Token &t) const
const char * what ()
Dictionary ()
virtual ~Dictionary ()
Static Public Member Functions
static bool compile (const Param &param, const std::vector< std::string > &dics, const char *matrix_file, const char *matrix_bin_file, const char *left_id_file, const char *right_id_file, const char *rewrite_file, const char *pos_id_file, const char *output)
Detailed Description
Definition at line 19 of file dictionary.h.
Member Typedef Documentation
typedef Darts::DoubleArray::result_pair_type MeCab::Dictionary::result_type
Definition at line 35 of file dictionary.h.
Constructor & Destructor Documentation
MeCab::Dictionary::Dictionary () [inline, explicit]
Definition at line 87 of file dictionary.h.
virtual MeCab::Dictionary::~Dictionary () [inline, virtual]
Definition at line 89 of file dictionary.h.
References close().
Member Function Documentation
const char* MeCab::Dictionary::charset () const [inline]
Definition at line 62 of file dictionary.h.
Referenced by compile(), MeCab::TokenizerImpl< N, P >::open(), and MeCab::DictionaryGenerator::run().
void MeCab::Dictionary::close ()
Definition at line 80 of file dictionary.cpp.
References MMAP_CLOSE.
Referenced by ~Dictionary().
size_t MeCab::Dictionary::commonPrefixSearch (const char * key, size_t len, result_type * result, size_t rlen) [inline]
Definition at line 41 of file dictionary.h.
References MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::commonPrefixSearch().
bool MeCab::Dictionary::compile (const Param & param, const std::vector< std::string > & dics, const char * matrix_file, const char * matrix_bin_file, const char * left_id_file, const char * right_id_file, const char * rewrite_file, const char * pos_id_file, const char * output) [static]
Definition at line 84 of file dictionary.cpp.
References BUF_SIZE, charset(), CHECK_DIE, feature(), MeCab::scoped_ptr< T >::get(), MeCab::Param::get(), MeCab::Connector::is_valid(), MeCab::Connector::left_size(), lsize(), MECAB_NOR_NODE, MECAB_UNK_DIC, MeCab::Connector::open(), MeCab::Iconv::open(), MeCab::Connector::openText(), MeCab::progress_bar_darts(), MeCab::scoped_ptr< T >::reset(), MeCab::Connector::right_size(), rsize(), MeCab::Connector::set_left_size(), MeCab::Connector::set_right_size(), token(), MeCab::tokenizeCSV(), type(), UNK_DEF_DEFAULT, and version().
Referenced by MeCab::DictionaryComplier::run().
result_type MeCab::Dictionary::exactMatchSearch (const char * key) [inline]
Definition at line 47 of file dictionary.h.
References MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::exactMatchSearch().
Referenced by MeCab::TokenizerImpl< N, P >::open().
const char* MeCab::Dictionary::feature (const Token & t) const [inline]
Definition at line 73 of file dictionary.h.
Referenced by compile().
const char* MeCab::Dictionary::filename () const [inline]
Definition at line 61 of file dictionary.h.
bool MeCab::Dictionary::isCompatible (const Dictionary & d) const [inline]
Definition at line 53 of file dictionary.h.
References charset_, MeCab::decode_charset(), lsize_, rsize_, and version_.
Referenced by MeCab::TokenizerImpl< N, P >::open().
size_t MeCab::Dictionary::lsize () const [inline]
Definition at line 66 of file dictionary.h.
Referenced by compile().
bool MeCab::Dictionary::open (const char * filename, const char * mode = "r")
Definition at line 29 of file dictionary.cpp.
References MeCab::Mmap< T >::begin(), CHECK_CLOSE_FALSE, MeCab::Mmap< T >::end(), MMAP_OPEN, MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::set_array(), and MeCab::Mmap< T >::size().
Referenced by MeCab::TokenizerImpl< N, P >::open(), and MeCab::DictionaryGenerator::run().
size_t MeCab::Dictionary::rsize () const [inline]
Definition at line 67 of file dictionary.h.
Referenced by compile().
size_t MeCab::Dictionary::size () const [inline]
Definition at line 64 of file dictionary.h.
const Token* MeCab::Dictionary::token (const result_type & n) const [inline]
Definition at line 69 of file dictionary.h.
References MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::DoubleArrayImpl::result_pair_type::value.
Referenced by compile(), and MeCab::TokenizerImpl< N, P >::open().
size_t MeCab::Dictionary::token_size (const result_type & n) const [inline]
Definition at line 72 of file dictionary.h.
References MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::DoubleArrayImpl::result_pair_type::value.
Referenced by MeCab::TokenizerImpl< N, P >::open().
int MeCab::Dictionary::type () const [inline]
Definition at line 65 of file dictionary.h.
Referenced by compile(), and MeCab::TokenizerImpl< N, P >::open().
unsigned short MeCab::Dictionary::version () const [inline]
Definition at line 63 of file dictionary.h.
Referenced by compile().
const char* MeCab::Dictionary::what () [inline]
Definition at line 85 of file dictionary.h.
References MeCab::whatlog::str().
Referenced by MeCab::TokenizerImpl< N, P >::open().
The documentation for this class was generated from the following files:
source/libmecab/dictionary.h
source/libmecab/dictionary.cpp