Japanese Morphological Analyzer: MeCab::CharProperty Class Reference
MeCab::CharProperty Class Reference
#include <char_property.h>
Public Member Functions
bool open (const Param &)
bool open (const char *)
void close ()
size_t size () const
void set_charset (const char *charset)
int id (const char *) const
const char * name (size_t i) const
const char * what ()
const char * seekToOtherType (const char *begin, const char *end, CharInfo c, CharInfo *fail, size_t *mblen, size_t *clen) const
CharInfo getCharInfo (const char *begin, const char *end, size_t *mblen) const
CharInfo getCharInfo (size_t id) const
CharProperty ()
virtual ~CharProperty ()
Static Public Member Functions
static bool compile (const char *, const char *, const char *)
Detailed Description
Definition at line 26 of file char_property.h.
Constructor & Destructor Documentation
MeCab::CharProperty::CharProperty () [inline, explicit]
Definition at line 88 of file char_property.h.
virtual MeCab::CharProperty::~CharProperty () [inline, virtual]
Definition at line 89 of file char_property.h.
References close().
Member Function Documentation
void MeCab::CharProperty::close ()
Definition at line 107 of file char_property.cpp.
References MMAP_CLOSE.
Referenced by MeCab::TokenizerImpl< N, P >::close(), and ~CharProperty().
bool MeCab::CharProperty::compile (const char * cfile, const char * ufile, const char * ofile) [static]
Definition at line 128 of file char_property.cpp.
References BUF_SIZE, CHAR_PROPERTY_DEF_DEFAULT, CHECK_DIE, high, low, size(), MeCab::tokenize2(), MeCab::tokenizeCSV(), and UNK_DEF_DEFAULT.
Referenced by MeCab::DictionaryComplier::run().
CharInfo MeCab::CharProperty::getCharInfo (size_t id) const [inline]
Definition at line 84 of file char_property.h.
CharInfo MeCab::CharProperty::getCharInfo (const char * begin, const char * end, size_t * mblen) const [inline]
Definition at line 57 of file char_property.h.
References MeCab::ASCII, MeCab::ascii_to_ucs2(), MeCab::CP932, MeCab::cp932_to_ucs2(), MeCab::EUC_JP, MeCab::euc_to_ucs2(), MeCab::UTF16, MeCab::utf16_to_ucs2(), MeCab::UTF16BE, MeCab::utf16be_to_ucs2(), MeCab::UTF16LE, MeCab::utf16le_to_ucs2(), MeCab::UTF8, and MeCab::utf8_to_ucs2().
Referenced by MeCab::TokenizerImpl< N, P >::lookup(), MeCab::TokenizerImpl< N, P >::open(), and seekToOtherType().
int MeCab::CharProperty::id (const char * key) const
Definition at line 122 of file char_property.cpp.
const char * MeCab::CharProperty::name (size_t i) const
Definition at line 113 of file char_property.cpp.
Referenced by MeCab::TokenizerImpl< N, P >::open().
bool MeCab::CharProperty::open (const char * filename)
Definition at line 83 of file char_property.cpp.
References MeCab::Mmap< T >::begin(), CHECK_CLOSE_FALSE, MMAP_OPEN, MeCab::read_ptr(), and MeCab::Mmap< T >::size().
bool MeCab::CharProperty::open (const Param & param)
Definition at line 77 of file char_property.cpp.
References CHAR_PROPERTY_FILE, MeCab::create_filename(), and MeCab::Param::get().
Referenced by MeCab::TokenizerImpl< N, P >::open(), and MeCab::DictionaryGenerator::run().
const char* MeCab::CharProperty::seekToOtherType (const char * begin, const char * end, CharInfo c, CharInfo * fail, size_t * mblen, size_t * clen) const [inline]
Definition at line 44 of file char_property.h.
References getCharInfo(), and MeCab::CharInfo::isKindOf().
Referenced by MeCab::TokenizerImpl< N, P >::lookup().
void MeCab::CharProperty::set_charset (const char * charset)
Definition at line 118 of file char_property.cpp.
References MeCab::decode_charset().
Referenced by MeCab::TokenizerImpl< N, P >::open().
size_t MeCab::CharProperty::size () const
Definition at line 111 of file char_property.cpp.
Referenced by compile(), and MeCab::TokenizerImpl< N, P >::open().
const char* MeCab::CharProperty::what () [inline]
Definition at line 42 of file char_property.h.
References MeCab::whatlog::str().
Referenced by MeCab::TokenizerImpl< N, P >::open().
The documentation for this class was generated from the following files:
source/libmecab/char_property.h
source/libmecab/char_property.cpp