Japanese Morphological Analyzer: MeCab::EncoderLearnerTagger Class Reference
MeCab::EncoderLearnerTagger Class Reference
#include <learner_tagger.h>
Public Member Functions
bool open (LearnerTokenizer *tokenzier, FreeList< LearnerPath > *path_freelist, FeatureIndex *feature_index, size_t eval_size, size_t unk_eval_size)
bool read (std::istream *, std::vector< double > *)
int eval (size_t *, size_t *, size_t *) const
double gradient (double *expected)
double online_update (double *expected)
EncoderLearnerTagger ()
virtual ~EncoderLearnerTagger ()
Detailed Description
Definition at line 50 of file learner_tagger.h.
Constructor & Destructor Documentation
MeCab::EncoderLearnerTagger::EncoderLearnerTagger () [inline, explicit]
Definition at line 65 of file learner_tagger.h.
virtual MeCab::EncoderLearnerTagger::~EncoderLearnerTagger () [inline, virtual]
Definition at line 66 of file learner_tagger.h.
References MeCab::LearnerTagger::close().
Member Function Documentation
int MeCab::EncoderLearnerTagger::eval (size_t * crr, size_t * prec, size_t * recall) const
Definition at line 195 of file learner_tagger.cpp.
References MeCab::LearnerTagger::endNodeList_, and MeCab::node_cmp_eq().
Referenced by MeCab::OLLearner::run().
double MeCab::EncoderLearnerTagger::gradient (double * expected)
Definition at line 378 of file learner_tagger.cpp.
References MeCab::LearnerTagger::beginNodeList_, MeCab::calc_alpha(), MeCab::calc_beta(), MeCab::calc_expectation(), MeCab::LearnerTagger::endNodeList_, MeCab::LearnerTagger::len_, and MeCab::LearnerTagger::viterbi().
double MeCab::EncoderLearnerTagger::online_update (double * expected)
Definition at line 402 of file learner_tagger.cpp.
References MeCab::calc_online_update(), MeCab::LearnerTagger::endNodeList_, and MeCab::LearnerTagger::viterbi().
Referenced by MeCab::OLLearner::run().
bool MeCab::EncoderLearnerTagger::open (LearnerTokenizer * tokenzier, FreeList< LearnerPath > * path_freelist, FeatureIndex * feature_index, size_t eval_size, size_t unk_eval_size)
Definition at line 32 of file learner_tagger.cpp.
References MeCab::LearnerTagger::close(), MeCab::LearnerTagger::feature_index_, MeCab::LearnerTagger::path_freelist_, and MeCab::LearnerTagger::tokenizer_.
Referenced by MeCab::CRFLearner::run(), and MeCab::OLLearner::run().
bool MeCab::EncoderLearnerTagger::read (std::istream * is, std::vector< double > * observed)
Definition at line 62 of file learner_tagger.cpp.
References MeCab::LearnerTagger::begin_, MeCab::LearnerTagger::begin__, MeCab::LearnerTagger::beginNodeList_, BUF_SIZE, MeCab::LearnerTagger::buildLattice(), CHECK_DIE, CHECK_FALSE, MeCab::LearnerTagger::endNodeList_, MeCab::LearnerTagger::feature_index_, MeCab::scoped_array< T >::get(), MeCab::TokenizerImpl< N, P >::getNewNode(), MeCab::LearnerTagger::initList(), MeCab::LearnerTagger::len_, MeCab::LearnerTagger::lookup(), MECAB_EOS_NODE, MECAB_NOR_NODE, MeCab::node_cmp_eq(), MeCab::scoped_string::reset_string(), MeCab::FeatureIndex::strdup(), MeCab::tokenize(), and MeCab::LearnerTagger::tokenizer_.
Referenced by MeCab::CRFLearner::run(), and MeCab::OLLearner::run().
The documentation for this class was generated from the following files:
source/libmecab/learner_tagger.h
source/libmecab/learner_tagger.cpp