Japanese Morphological Analyzer: jma::KanaTable Class Reference
jma::KanaTable Class Reference
KanaTable stores the mapping table between Japanese Hiragana and Katakana characters.
#include <kana_table.h>
Public Types
enum POSFormat { POS_FORMAT_DEFAULT, POS_FORMAT_ALPHABET, POS_FORMAT_FULL_CATEGORY, POS_FORMAT_NUM }
POS format type.
Public Member Functions
KanaTable ()
Constructor.
bool loadConfig (const char *fileName, Knowledge::EncodeType src, Knowledge::EncodeType dest)
Load the configuration file "kana-map.def", which is in text format.
const char * toHiragana (const char *str) const
Convert Japanese Katakana character to its Hiragana equivalent, other character is returned as 0.
const char * toKatakana (const char *str) const
Convert Japanese Hiragana character to its Katakana equivalent, other character is returned as 0.
Detailed Description
KanaTable stores the mapping table between Japanese Hiragana and Katakana characters.
Definition at line 23 of file kana_table.h.
Member Enumeration Documentation
enum jma::KanaTable::POSFormat
POS format type.
Enumerator:
POS_FORMAT_DEFAULT default Japanese format such like "名詞,一般".
POS_FORMAT_ALPHABET Alphabet format such like "NC-G".
POS_FORMAT_FULL_CATEGORY Japanese format of furl category such like "名詞,一般,*,*".
POS_FORMAT_NUM the count of format types
Definition at line 34 of file kana_table.h.
Constructor & Destructor Documentation
jma::KanaTable::KanaTable ()
Constructor.
Definition at line 25 of file kana_table.cpp.
Member Function Documentation
bool jma::KanaTable::loadConfig (const char * fileName, Knowledge::EncodeType src, Knowledge::EncodeType dest)
Load the configuration file "kana-map.def", which is in text format.
This file contains the mapping table between Hiragana and Katakana characters, which format is "Hiragana Katakana".
Parameters:
fileName the file name
src source encode type of fileName
dest destination encode type to convert
Returns:
true for success, false for fail
Attention:
if this function is already called before, the table previously loaded would be removed.
Definition at line 29 of file kana_table.cpp.
References jma::Iconv::convert(), and jma::Iconv::open().
Referenced by jma::JMA_Knowledge::loadDict().
const char * jma::KanaTable::toHiragana (const char * str) const
Convert Japanese Katakana character to its Hiragana equivalent, other character is returned as 0.
Parameters:
str the character string
Returns:
if str is Katakana character, its Hiragana equivalent is returned, otherwise 0 is returned
Definition at line 107 of file kana_table.cpp.
Referenced by jma::JMA_Analyzer::convertToHiragana().
const char * jma::KanaTable::toKatakana (const char * str) const
Convert Japanese Hiragana character to its Katakana equivalent, other character is returned as 0.
Parameters:
str the character string
Returns:
if str is Hiragana character, its Katakana equivalent is returned, otherwise 0 is returned
Definition at line 116 of file kana_table.cpp.
Referenced by jma::JMA_Analyzer::convertToKatakana().
The documentation for this class was generated from the following files:
source/include/kana_table.h
source/src/kana_table.cpp