Japanese Morphological Analyzer: MeCab::DictionaryComplier Class Reference
MeCab::DictionaryComplier Class Reference
Static Public Member Functions
static int run (int argc, char **argv)
Detailed Description
Definition at line 23 of file dictionary_compiler.cpp.
Member Function Documentation
static int MeCab::DictionaryComplier::run (int argc, char ** argv) [inline, static]
Definition at line 25 of file dictionary_compiler.cpp.
References CHAR_PROPERTY_DEF_FILE, CHAR_PROPERTY_FILE, CHECK_DIE, MeCab::Connector::compile(), MeCab::CharProperty::compile(), MeCab::Dictionary::compile(), COPYRIGHT, DCONF, DICRC, MeCab::enum_csv_dictionaries(), MeCab::Param::get(), MeCab::Param::help_version(), LEFT_ID_FILE, MeCab::Param::load(), MATRIX_DEF_FILE, MATRIX_FILE, MECAB_DEFAULT_CHARSET, MECAB_SYS_DIC, MECAB_UNK_DIC, MECAB_USR_DIC, OCONF, MeCab::Param::open(), POS_ID_FILE, MeCab::Param::rest_args(), REWRITE_FILE, RIGHT_ID_FILE, MeCab::Param::set(), SYS_DIC_FILE, UNK_DEF_FILE, UNK_DIC_FILE, and MeCab::Param::what().
Referenced by mecab_dict_index().
The documentation for this class was generated from the following file:
source/libmecab/dictionary_compiler.cpp