Japanese Morphological Analyzer: MeCab::Param Class Reference
MeCab::Param Class Reference
#include <param.h>
Public Member Functions
bool open (int argc, char **argv, const Option *opt)
bool open (const char *arg, const Option *opt)
bool load (const char *filename)
void clear ()
const std::vector< std::string > & rest_args () const
const char * program_name () const
const char * what ()
const char * help () const
const char * version () const
int help_version () const
template<class T >
T get (const char *key) const
template<class T >
void set (const char *key, const T &value, bool rewrite=true)
void dump_config (std::ostream *os) const
Param ()
virtual ~Param ()
Detailed Description
Definition at line 46 of file param.h.
Constructor & Destructor Documentation
MeCab::Param::Param () [inline, explicit]
Definition at line 88 of file param.h.
virtual MeCab::Param::~Param () [inline, virtual]
Definition at line 89 of file param.h.
Member Function Documentation
void MeCab::Param::clear ()
Definition at line 189 of file param.cpp.
void MeCab::Param::dump_config (std::ostream * os) const
Definition at line 60 of file param.cpp.
Referenced by mecab_do().
template<class T > T MeCab::Param::get (const char * key) const [inline]
Definition at line 69 of file param.h.
Referenced by MeCab::Dictionary::compile(), MeCab::Eval::eval(), MeCab::load_dictionary_resource(), mecab_do(), MeCab::Writer::open(), MeCab::Viterbi::open(), MeCab::TaggerImpl::open(), MeCab::DecoderFeatureIndex::open(), MeCab::Connector::open(), MeCab::CharProperty::open(), MeCab::FeatureIndex::openTemplate(), MeCab::Learner::run(), MeCab::CRFLearner::run(), MeCab::OLLearner::run(), MeCab::HMMLearner::run(), MeCab::TestSentenceGenerator::run(), MeCab::DictionaryGenerator::run(), and MeCab::DictionaryComplier::run().
const char* MeCab::Param::help () const [inline]
Definition at line 64 of file param.h.
Referenced by help_version(), and MeCab::TaggerImpl::open().
int MeCab::Param::help_version () const
Definition at line 212 of file param.cpp.
References help(), and version().
Referenced by MeCab::Eval::eval(), MeCab::Learner::run(), MeCab::TestSentenceGenerator::run(), MeCab::DictionaryGenerator::run(), and MeCab::DictionaryComplier::run().
bool MeCab::Param::load (const char * filename)
Definition at line 68 of file param.cpp.
References CHECK_FALSE.
Referenced by MeCab::load_dictionary_resource(), MeCab::CRFLearner::run(), MeCab::OLLearner::run(), MeCab::HMMLearner::run(), MeCab::DictionaryGenerator::run(), and MeCab::DictionaryComplier::run().
bool MeCab::Param::open (const char * arg, const Option * opt)
Definition at line 194 of file param.cpp.
References BUF_SIZE, and open().
bool MeCab::Param::open (int argc, char ** argv, const Option * opt)
Definition at line 92 of file param.cpp.
References MeCab::Option::default_value, GOTO_ERROR, MeCab::init_param(), MeCab::Option::name, and WHAT.
Referenced by MeCab::Eval::eval(), mecab_do(), MeCab::TaggerImpl::open(), open(), MeCab::Learner::run(), MeCab::TestSentenceGenerator::run(), MeCab::DictionaryGenerator::run(), and MeCab::DictionaryComplier::run().
const char* MeCab::Param::program_name () const [inline]
Definition at line 62 of file param.h.
Referenced by MeCab::Eval::eval(), MeCab::Learner::run(), MeCab::CRFLearner::run(), MeCab::OLLearner::run(), and MeCab::HMMLearner::run().
const std::vector<std::string>& MeCab::Param::rest_args () const [inline]
Definition at line 60 of file param.h.
Referenced by MeCab::Eval::eval(), mecab_do(), MeCab::Learner::run(), MeCab::CRFLearner::run(), MeCab::OLLearner::run(), MeCab::HMMLearner::run(), MeCab::TestSentenceGenerator::run(), and MeCab::DictionaryComplier::run().
template<class T > void MeCab::Param::set (const char * key, const T & value, bool rewrite = true) [inline]
Definition at line 79 of file param.h.
Referenced by MeCab::load_dictionary_resource(), mecab_do(), MeCab::DictionaryGenerator::run(), and MeCab::DictionaryComplier::run().
const char* MeCab::Param::version () const [inline]
Definition at line 65 of file param.h.
Referenced by help_version(), and MeCab::TaggerImpl::open().
const char* MeCab::Param::what () [inline]
Definition at line 63 of file param.h.
References MeCab::whatlog::str().
Referenced by MeCab::Eval::eval(), mecab_do(), MeCab::TaggerImpl::open(), MeCab::Learner::run(), MeCab::TestSentenceGenerator::run(), MeCab::DictionaryGenerator::run(), and MeCab::DictionaryComplier::run().
The documentation for this class was generated from the following files:
source/libmecab/param.h
source/libmecab/param.cpp