Japanese Morphological Analyzer: MeCab::LBFGS Class Reference
MeCab::LBFGS Class Reference
#include <lbfgs.h>
Classes
class Mcsrch
Public Member Functions
LBFGS ()
virtual ~LBFGS ()
void clear ()
int optimize (size_t size, double *x, double f, double *g, bool orthant, double C)
Detailed Description
Definition at line 15 of file lbfgs.h.
Constructor & Destructor Documentation
MeCab::LBFGS::LBFGS () [inline, explicit]
Definition at line 34 of file lbfgs.h.
virtual MeCab::LBFGS::~LBFGS () [inline, virtual]
Definition at line 38 of file lbfgs.h.
References clear().
Member Function Documentation
void MeCab::LBFGS::clear ()
Definition at line 404 of file lbfgs.cpp.
Referenced by optimize(), and ~LBFGS().
int MeCab::LBFGS::optimize (size_t size, double * x, double f, double * g, bool orthant, double C) [inline]
Definition at line 42 of file lbfgs.h.
References clear().
Referenced by MeCab::CRFLearner::run().
The documentation for this class was generated from the following files:
source/libmecab/lbfgs.h
source/libmecab/lbfgs.cpp