Japanese Morphological Analyzer: MeCab::FeatureIndex Class Reference
MeCab::FeatureIndex Class Reference
#include <feature_index.h>
Public Member Functions
virtual bool open (const Param &)=0
virtual void clear ()=0
virtual void close ()=0
virtual bool buildFeature (LearnerPath *path)=0
void set_alpha (const double *)
size_t size () const
bool buildUnigramFeature (LearnerPath *, const char *)
bool buildBigramFeature (LearnerPath *, const char *, const char *)
void calcCost (LearnerPath *path)
void calcCost (LearnerNode *node)
const char * what ()
const char * strdup (const char *str)
FeatureIndex ()
virtual ~FeatureIndex ()
Static Public Member Functions
static bool convert (const char *text_filename, const char *binary_filename)
Protected Member Functions
virtual int id (const char *)=0
const char * getIndex (char **, char **, size_t)
bool openTemplate (const Param &)
Protected Attributes
std::vector< int > feature_
ChunkFreeList< int > feature_freelist_
ChunkFreeList< char > char_freelist_
std::vector< const char * > unigram_templs_
std::vector< const char * > bigram_templs_
DictionaryRewriter rewrite_
StringBuffer os_
size_t maxid_
const double * alpha_
whatlog what_
Detailed Description
Definition at line 24 of file feature_index.h.
Constructor & Destructor Documentation
MeCab::FeatureIndex::FeatureIndex () [inline, explicit]
Definition at line 64 of file feature_index.h.
virtual MeCab::FeatureIndex::~FeatureIndex () [inline, virtual]
Definition at line 67 of file feature_index.h.
Member Function Documentation
bool MeCab::FeatureIndex::buildBigramFeature (LearnerPath * path, const char * rfeature, const char * lfeature)
Definition at line 331 of file feature_index.cpp.
References ADDB, bigram_templs_, BUFSIZE, CHECK_FALSE, MeCab::StringBuffer::clear(), COPY_FEATURE, feature_, MeCab::getEscapedChar(), getIndex(), os_, POSSIZE, MeCab::StringBuffer::str(), and MeCab::tokenizeCSV().
Referenced by MeCab::DecoderFeatureIndex::buildFeature().
virtual bool MeCab::FeatureIndex::buildFeature (LearnerPath * path) [pure virtual]
Implemented in MeCab::EncoderFeatureIndex, and MeCab::DecoderFeatureIndex.
Referenced by MeCab::LearnerTagger::connect().
bool MeCab::FeatureIndex::buildUnigramFeature (LearnerPath * path, const char * ufeature)
Definition at line 286 of file feature_index.cpp.
References ADDB, BUFSIZE, CHECK_FALSE, MeCab::StringBuffer::clear(), COPY_FEATURE, feature_, MeCab::getEscapedChar(), getIndex(), os_, POSSIZE, MeCab::StringBuffer::str(), MeCab::tokenizeCSV(), and unigram_templs_.
Referenced by MeCab::EncoderFeatureIndex::buildFeature(), and MeCab::DecoderFeatureIndex::buildFeature().
void MeCab::FeatureIndex::calcCost (LearnerNode * node)
Definition at line 164 of file feature_index.cpp.
References alpha_, and MECAB_EOS_NODE.
void MeCab::FeatureIndex::calcCost (LearnerPath * path)
Definition at line 171 of file feature_index.cpp.
References alpha_, and MeCab::is_empty().
Referenced by MeCab::LearnerTagger::viterbi().
virtual void MeCab::FeatureIndex::clear () [pure virtual]
Implemented in MeCab::EncoderFeatureIndex, and MeCab::DecoderFeatureIndex.
Referenced by MeCab::DecoderLearnerTagger::parse().
virtual void MeCab::FeatureIndex::close () [pure virtual]
Implemented in MeCab::EncoderFeatureIndex, and MeCab::DecoderFeatureIndex.
bool MeCab::FeatureIndex::convert (const char * text_filename, const char * binary_filename) [static]
Definition at line 464 of file feature_index.cpp.
References MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::array(), BUF_SIZE, MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::build(), CHECK_DIE, MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::size(), size(), MeCab::tokenize2(), and MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::unit_size().
Referenced by MeCab::Learner::run(), and MeCab::HMMLearner::run().
const char * MeCab::FeatureIndex::getIndex (char ** p, char ** column, size_t max) [protected]
Definition at line 31 of file feature_index.cpp.
References CHECK_RETURN.
Referenced by buildBigramFeature(), and buildUnigramFeature().
virtual int MeCab::FeatureIndex::id (const char *) [protected, pure virtual]
virtual bool MeCab::FeatureIndex::open (const Param &) [pure virtual]
Implemented in MeCab::EncoderFeatureIndex, and MeCab::DecoderFeatureIndex.
Referenced by MeCab::DecoderLearnerTagger::open().
bool MeCab::FeatureIndex::openTemplate (const Param & param) [protected]
Definition at line 75 of file feature_index.cpp.
References bigram_templs_, BUF_SIZE, CHECK_FALSE, MeCab::create_filename(), FEATURE_FILE, MeCab::Param::get(), MeCab::DictionaryRewriter::open(), rewrite_, REWRITE_FILE, strdup(), MeCab::tokenize2(), and unigram_templs_.
Referenced by MeCab::DecoderFeatureIndex::open(), and MeCab::EncoderFeatureIndex::open().
void MeCab::FeatureIndex::set_alpha (const double * alpha)
Definition at line 71 of file feature_index.cpp.
References alpha_.
size_t MeCab::FeatureIndex::size () const [inline]
Definition at line 49 of file feature_index.h.
References maxid_.
Referenced by convert().
const char * MeCab::FeatureIndex::strdup (const char * str)
Definition at line 178 of file feature_index.cpp.
References MeCab::ChunkFreeList< T >::alloc(), and char_freelist_.
Referenced by openTemplate(), and MeCab::EncoderLearnerTagger::read().
const char* MeCab::FeatureIndex::what () [inline]
Definition at line 57 of file feature_index.h.
References MeCab::whatlog::str(), and what_.
Referenced by MeCab::LearnerTagger::connect(), MeCab::DecoderLearnerTagger::open(), MeCab::Learner::run(), and MeCab::DictionaryGenerator::run().
Member Data Documentation
const double* MeCab::FeatureIndex::alpha_ [protected]
Definition at line 34 of file feature_index.h.
Referenced by calcCost(), MeCab::DecoderFeatureIndex::open(), MeCab::EncoderFeatureIndex::save(), and set_alpha().
std::vector<const char*> MeCab::FeatureIndex::bigram_templs_ [protected]
Definition at line 30 of file feature_index.h.
Referenced by buildBigramFeature(), and openTemplate().
ChunkFreeList<char> MeCab::FeatureIndex::char_freelist_ [protected]
Definition at line 28 of file feature_index.h.
Referenced by strdup().
std::vector<int> MeCab::FeatureIndex::feature_ [protected]
Definition at line 26 of file feature_index.h.
Referenced by buildBigramFeature(), and buildUnigramFeature().
ChunkFreeList<int> MeCab::FeatureIndex::feature_freelist_ [protected]
Definition at line 27 of file feature_index.h.
Referenced by MeCab::DecoderFeatureIndex::clear().
size_t MeCab::FeatureIndex::maxid_ [protected]
Definition at line 33 of file feature_index.h.
Referenced by MeCab::DecoderFeatureIndex::close(), MeCab::EncoderFeatureIndex::close(), MeCab::DecoderFeatureIndex::open(), MeCab::EncoderFeatureIndex::shrink(), and size().
StringBuffer MeCab::FeatureIndex::os_ [protected]
Definition at line 32 of file feature_index.h.
Referenced by buildBigramFeature(), MeCab::EncoderFeatureIndex::buildFeature(), and buildUnigramFeature().
DictionaryRewriter MeCab::FeatureIndex::rewrite_ [protected]
Definition at line 31 of file feature_index.h.
Referenced by MeCab::EncoderFeatureIndex::buildFeature(), MeCab::DecoderFeatureIndex::buildFeature(), MeCab::EncoderFeatureIndex::clearcache(), and openTemplate().
std::vector<const char*> MeCab::FeatureIndex::unigram_templs_ [protected]
Definition at line 29 of file feature_index.h.
Referenced by buildUnigramFeature(), and openTemplate().
whatlog MeCab::FeatureIndex::what_ [protected]
Definition at line 35 of file feature_index.h.
Referenced by what().
The documentation for this class was generated from the following files:
source/libmecab/feature_index.h
source/libmecab/feature_index.cpp