Japanese Morphological Analyzer: MeCab::Iconv Class Reference
MeCab::Iconv Class Reference
#include <iconv_utils.h>
Public Member Functions
Iconv ()
virtual ~Iconv ()
bool open (const char *from, const char *to)
bool convert (std::string *)
Detailed Description
Definition at line 20 of file iconv_utils.h.
Constructor & Destructor Documentation
MeCab::Iconv::Iconv () [explicit]
Definition at line 197 of file iconv_utils.cpp.
MeCab::Iconv::~Iconv () [virtual]
Definition at line 199 of file iconv_utils.cpp.
Member Function Documentation
bool MeCab::Iconv::convert (std::string * str)
Definition at line 111 of file iconv_utils.cpp.
References MeCab::scoped_array< T >::get().
Referenced by MeCab::POSIDGenerator::open(), and MeCab::DictionaryRewriter::open().
bool MeCab::Iconv::open (const char * from, const char * to)
Definition at line 81 of file iconv_utils.cpp.
Referenced by MeCab::Dictionary::compile().
The documentation for this class was generated from the following files:
source/libmecab/iconv_utils.h
source/libmecab/iconv_utils.cpp