Japanese Morphological Analyzer: MeCab::Learner Class Reference
MeCab::Learner Class Reference
Static Public Member Functions
static bool run (int argc, char **argv)
Detailed Description
Definition at line 599 of file learner.cpp.
Member Function Documentation
static bool MeCab::Learner::run (int argc, char ** argv) [inline, static]
Definition at line 601 of file learner.cpp.
References CHECK_DIE, MeCab::FeatureIndex::convert(), COPYRIGHT, MeCab::Param::get(), MeCab::Param::help_version(), MeCab::Param::open(), MeCab::Param::program_name(), MeCab::Param::rest_args(), MeCab::toLower(), MeCab::FeatureIndex::what(), and MeCab::Param::what().
Referenced by mecab_cost_train().
The documentation for this class was generated from the following file:
source/libmecab/learner.cpp