Japanese Morphological Analyzer: MeCab::POSIDGenerator Class Reference
MeCab::POSIDGenerator Class Reference
#include <dictionary_rewriter.h>
Public Member Functions
bool open (const char *filename, Iconv *iconv=0)
void clear ()
int id (const char *key) const
Detailed Description
Definition at line 66 of file dictionary_rewriter.h.
Member Function Documentation
void MeCab::POSIDGenerator::clear () [inline]
Definition at line 72 of file dictionary_rewriter.h.
int MeCab::POSIDGenerator::id (const char * key) const
Definition at line 229 of file dictionary_rewriter.cpp.
References BUF_SIZE, CHECK_DIE, MeCab::RewriteRules::rewrite(), and MeCab::tokenizeCSV().
bool MeCab::POSIDGenerator::open (const char * filename, Iconv * iconv = 0)
Definition at line 202 of file dictionary_rewriter.cpp.
References CHECK_DIE, MeCab::Iconv::convert(), and MeCab::tokenize2().
The documentation for this class was generated from the following files:
source/libmecab/dictionary_rewriter.h
source/libmecab/dictionary_rewriter.cpp