Japanese Morphological Analyzer: jma::Knowledge Class Reference
jma::Knowledge Class Reference
Knowledge manages the linguistic information for Japanese morphological analysis.
#include <knowledge.h>
Public Types
enum EncodeType { ENCODE_TYPE_EUCJP, ENCODE_TYPE_SJIS, ENCODE_TYPE_UTF8, ENCODE_TYPE_NUM }
Encode type of characters.
Public Member Functions
Knowledge ()
Constructor.
virtual ~Knowledge ()
Destructor.
void setSystemDict (const char *dirPath)
Set the directory path of system dictionary files, which are in binary format.
void addUserDict (const char *fileName, EncodeType type=ENCODE_TYPE_UTF8)
Add the user dictionary file, which is in text format, the source encoding type of user dictionary file is also given in parameter, which is UTF-8 by default, this function could be called more than once, so that multiple user dictionaries could be added.
virtual int loadDict ()=0
Load the dictionaries, which are set by setSystemDict() and addUserDict().
virtual int loadStopWordDict (const char *fileName)=0
Load the stop-word dictionary file, which is in text format.
virtual int setKeywordPOS (const std::vector< std::string > &posVec)=0
Set the part-of-speech tags as keywords.
virtual int encodeSystemDict (const char *txtDirPath, const char *binDirPath, EncodeType binEncodeType)=0
Encode the system dictionary files from text to binary file.
EncodeType getEncodeType () const
Get the character encode type.
Static Public Member Functions
static EncodeType decodeEncodeType (const char *encodeStr)
Get the encode type from the encode type string.
static const char * encodeStr (EncodeType encodeType)
Get the encode type string from the encode type.
Protected Types
typedef std::pair< std::string,
EncodeType > UserDictFileType
user dictionary file type, it is a pair of file name and its encoding type
Protected Attributes
EncodeType encodeType_
character encode type of binary system dicitonary, it is also the encode type of string/stream to analyze
std::string systemDictPath_
the directory path of system dictionary files
std::vector< UserDictFileType > userDictNames_
the file names of user dictionaries
Detailed Description
Knowledge manages the linguistic information for Japanese morphological analysis.
Definition at line 22 of file knowledge.h.
Member Typedef Documentation
typedef std::pair<std::string, EncodeType> jma::Knowledge::UserDictFileType [protected]
user dictionary file type, it is a pair of file name and its encoding type
Definition at line 130 of file knowledge.h.
Member Enumeration Documentation
enum jma::Knowledge::EncodeType
Encode type of characters.
Enumerator:
ENCODE_TYPE_EUCJP
EUC-JP character type.
ENCODE_TYPE_SJIS
SHIFT-JIS character type.
ENCODE_TYPE_UTF8
UTF-8 character type.
ENCODE_TYPE_NUM
the count of character types
Definition at line 28 of file knowledge.h.
Constructor & Destructor Documentation
jma::Knowledge::Knowledge ()
Constructor.
Definition at line 44 of file knowledge.cpp.
jma::Knowledge::~Knowledge () [virtual]
Destructor.
Definition at line 49 of file knowledge.cpp.
Member Function Documentation
void jma::Knowledge::addUserDict (const char * fileName, EncodeType type = ENCODE_TYPE_UTF8)
Add the user dictionary file, which is in text format, the source encoding type of user dictionary file is also given in parameter, which is UTF-8 by default, this function could be called more than once, so that multiple user dictionaries could be added.
Parameters:
fileName the file path of user dictionary
type the source encoding type of user dictionary, UTF-8 is assumed if omitted
Definition at line 96 of file knowledge.cpp.
References userDictNames_.
Referenced by JMA_Knowledge_Test::loadDictTest(), main(), and JMA_AnalyzerTest::SetUp().
Knowledge::EncodeType jma::Knowledge::decodeEncodeType (const char * encodeStr) [static]
Get the encode type from the encode type string.
Parameters:
encodeStr encode type string
Returns:
the encoding type, note that Knowledge::ENCODE_TYPE_NUM would be returned if the encoding type is unkown.
Definition at line 58 of file knowledge.cpp.
References ENCODE_TYPE_EUCJP, ENCODE_TYPE_NUM, ENCODE_TYPE_SJIS, ENCODE_TYPE_UTF8, and toLower().
const char * jma::Knowledge::encodeStr (EncodeType encodeType) [static]
Get the encode type string from the encode type.
Parameters:
encodeType encode type
Returns:
the encoding type string, note that 0 would be returned if the encoding type is unkown.
Definition at line 80 of file knowledge.cpp.
References ENCODE_TYPE_NUM.
Referenced by jma::JMA_Knowledge::loadDict().
virtual int jma::Knowledge::encodeSystemDict (const char * txtDirPath, const char * binDirPath, EncodeType binEncodeType) [pure virtual]
Encode the system dictionary files from text to binary file.
Parameters:
txtDirPath the directory path of text files
binDirPath the directory path of binary files
binEncodeType the encoding type of binary system dictionary
Returns:
0 for fail, 1 for success
Precondition:
both txtDirPath and binDirPath are assumed as the directory paths that already exists. If any of the directory paths does not exist, 0 would be returned for fail.
Referenced by main().
Knowledge::EncodeType jma::Knowledge::getEncodeType () const
Get the character encode type.
Returns:
the encode type
Definition at line 53 of file knowledge.cpp.
References encodeType_.
Referenced by jma::JMA_Knowledge::loadDict(), JMA_Knowledge_Test::loadDictTest(), main(), JMA_AnalyzerTest::SetUp(), and TEST().
virtual int jma::Knowledge::loadDict () [pure virtual]
Load the dictionaries, which are set by setSystemDict() and addUserDict().
Returns:
0 for fail, 1 for success
Precondition:
the directory path of system dictionary should be set by setSystemDict().
if any user dictionary file need to be loaded, the file name should be added by addUserDict().
Implemented in jma::JMA_Knowledge.
Referenced by main().
virtual int jma::Knowledge::loadStopWordDict (const char * fileName) [pure virtual]
Load the stop-word dictionary file, which is in text format.
The words in this file are ignored in the morphological analysis result.
Parameters:
fileName the file name
Returns:
0 for fail, 1 for success
Attention:
The encoding type of this file should be the same to the encoding type of system dictioanry loaded.
Implemented in jma::JMA_Knowledge.
Referenced by main().
virtual int jma::Knowledge::setKeywordPOS (const std::vector< std::string > & posVec) [pure virtual]
Set the part-of-speech tags as keywords.
If this method is not called or posVec is empty, the results of Analyzer::runWith*() would contain all words. Otherwise, if posVec is not empty, the results of Analyzer::runWith*() would only contain the words with part-of-speech tags specified by this method.
Parameters:
posVec the vector of part-of-speech tags in alphabet format, such as "NC-G"
Returns:
the number of part-of-speech tags successfully set
Attention:
This method should be called after loadDict(), otherwise no keyword part-of-speech tag would be set
Implemented in jma::JMA_Knowledge.
Referenced by main().
void jma::Knowledge::setSystemDict (const char * dirPath)
Set the directory path of system dictionary files, which are in binary format.
Parameters:
dirPath the directory path
Definition at line 89 of file knowledge.cpp.
References systemDictPath_.
Referenced by JMA_Knowledge_Test::loadDictTest(), main(), and JMA_AnalyzerTest::SetUp().
Member Data Documentation
EncodeType jma::Knowledge::encodeType_ [protected]
character encode type of binary system dicitonary, it is also the encode type of string/stream to analyze
Definition at line 124 of file knowledge.h.
Referenced by getEncodeType().
std::string jma::Knowledge::systemDictPath_ [protected]
the directory path of system dictionary files
Definition at line 127 of file knowledge.h.
Referenced by jma::JMA_Knowledge::createTagger(), jma::JMA_Knowledge::loadDict(), setSystemDict(), and jma::JMA_Knowledge::~JMA_Knowledge().
std::vector<UserDictFileType> jma::Knowledge::userDictNames_ [protected]
the file names of user dictionaries
Definition at line 133 of file knowledge.h.
Referenced by addUserDict().
The documentation for this class was generated from the following files:
include/knowledge.h
source/src/knowledge.cpp