Japanese Morphological Analyzer: MeCab::FreeList< T > Class Template Reference
MeCab::FreeList< T > Class Template Reference
#include <freelist.h>
Public Member Functions
void free ()
T * alloc ()
FreeList (size_t _size)
virtual ~FreeList ()
Detailed Description
template<class T>
class MeCab::FreeList< T >
Definition at line 17 of file freelist.h.
Constructor & Destructor Documentation
template<class T> MeCab::FreeList< T >::FreeList (size_t _size) [inline, explicit]
Definition at line 36 of file freelist.h.
template<class T> virtual MeCab::FreeList< T >::~FreeList () [inline, virtual]
Definition at line 38 of file freelist.h.
Member Function Documentation
template<class T> T* MeCab::FreeList< T >::alloc () [inline]
Definition at line 27 of file freelist.h.
Referenced by MeCab::LearnerTagger::connect(), MeCab::TokenizerImpl< Node, Path >::getNewNode(), MeCab::NBestGenerator::next(), MeCab::TokenizerImpl< N, P >::open(), and MeCab::NBestGenerator::set().
template<class T> void MeCab::FreeList< T >::free () [inline]
Definition at line 25 of file freelist.h.
Referenced by MeCab::TokenizerImpl< N, P >::clear(), MeCab::TokenizerImpl< N, P >::open(), MeCab::DecoderLearnerTagger::parse(), MeCab::OLLearner::run(), and MeCab::NBestGenerator::set().
The documentation for this class was generated from the following file:
source/libmecab/freelist.h