Japanese Morphological Analyzer: jma::CharTable Class Reference
jma::CharTable Class Reference
CharTable stores the mapping table between characters from one type to another.
#include <char_table.h>
Public Member Functions
CharTable ()
Constructor.
bool loadConfig (const char *fileName, MeCab::Iconv &iconv)
Load the configuration file, such as "map-kana.def", which is in text format.
const char * toRight (const char *str) const
Convert character to the right type, other character not in the left type is returned as 0.
const char * toLeft (const char *str) const
Convert character to the left type, other character not in the right type is returned as 0.
Detailed Description
CharTable stores the mapping table between characters from one type to another.
Definition at line 28 of file char_table.h.
Constructor & Destructor Documentation
jma::CharTable::CharTable ()
Constructor.
Definition at line 25 of file char_table.cpp.
Member Function Documentation
bool jma::CharTable::loadConfig (const char * fileName, MeCab::Iconv & iconv)
Load the configuration file, such as "map-kana.def", which is in text format.
This file contains the mapping table between one type to another, which format is "LeftType RightType".
Parameters:
fileName the file name
iconv to convert the input file's encoding type to run time encoding type
Returns:
true for success, false for fail
Attention:
if this function is already called before, the table previously loaded would be removed.
Definition at line 29 of file char_table.cpp.
References jma::JMA_Dictionary::getDict(), jma::JMA_Dictionary::instance(), jma::DictUnit::length_, and jma::DictUnit::text_.
Referenced by jma::JMA_Knowledge::loadDict().
const char * jma::CharTable::toLeft (const char * str) const
Convert character to the left type, other character not in the right type is returned as 0.
Parameters:
str the character string
Returns:
if str is in the right type, its left type equivalent is returned, otherwise 0 is returned
Definition at line 109 of file char_table.cpp.
Referenced by jma::JMA_Analyzer::convertCharacters().
const char * jma::CharTable::toRight (const char * str) const
Convert character to the right type, other character not in the left type is returned as 0.
Parameters:
str the character string
Returns:
if str is in the left type, its right type equivalent is returned, otherwise 0 is returned
Definition at line 118 of file char_table.cpp.
Referenced by jma::JMA_Analyzer::convertCharacters().
The documentation for this class was generated from the following files:
source/include/char_table.h
source/src/char_table.cpp