Japanese Morphological Analyzer: JMA_AnalyzerTest Class Reference
JMA_AnalyzerTest Class Reference
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
virtual void runWithSentenceTest (Analyzer *pAnalyzer)
virtual void runWithStreamTest (const char *strInputFile, const char *strOutputFile)
Protected Attributes
JMA_Analyzer * analyzer_
JMA_Knowledge * knowledge_
Detailed Description
Definition at line 23 of file unittest_jma_analyzer.cpp.
Member Function Documentation
virtual void JMA_AnalyzerTest::runWithSentenceTest (Analyzer * pAnalyzer) [inline, protected, virtual]
Definition at line 46 of file unittest_jma_analyzer.cpp.
References jma::Sentence::getBaseForm(), jma::Sentence::getCount(), jma::Sentence::getLexicon(), jma::Sentence::getListSize(), jma::Sentence::getNormForm(), jma::Sentence::getOneBestIndex(), jma::Sentence::getPOS(), jma::Sentence::getReadForm(), jma::Sentence::getScore(), jma::Sentence::getString(), jma::Sentence::getStrPOS(), jma::Analyzer::runWithSentence(), and jma::Sentence::setString().
virtual void JMA_AnalyzerTest::runWithStreamTest (const char * strInputFile, const char * strOutputFile) [inline, protected, virtual]
Definition at line 98 of file unittest_jma_analyzer.cpp.
References analyzer_, and jma::JMA_Analyzer::runWithStream().
virtual void JMA_AnalyzerTest::SetUp () [inline, protected, virtual]
Definition at line 26 of file unittest_jma_analyzer.cpp.
References jma::Knowledge::addUserDict(), analyzer_, jma::Knowledge::getEncodeType(), knowledge_, jma::JMA_Knowledge::loadDict(), jma::JMA_Analyzer::setKnowledge(), jma::Knowledge::setSystemDict(), TEST_JMA_DEFAULT_SYSTEM_DICT, and TEST_JMA_DEFAULT_USER_DICT.
virtual void JMA_AnalyzerTest::TearDown () [inline, protected, virtual]
Definition at line 41 of file unittest_jma_analyzer.cpp.
References analyzer_, and knowledge_.
Member Data Documentation
JMA_Analyzer* JMA_AnalyzerTest::analyzer_ [protected]
Definition at line 108 of file unittest_jma_analyzer.cpp.
Referenced by runWithStreamTest(), SetUp(), and TearDown().
JMA_Knowledge* JMA_AnalyzerTest::knowledge_ [protected]
Definition at line 109 of file unittest_jma_analyzer.cpp.
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following file:
source/unit_test/unittest_jma_analyzer.cpp