Japanese Morphological Analyzer: MeCab::TokenizerImpl< N, P > Class Template Reference
MeCab::TokenizerImpl< N, P > Class Template Reference
#include <tokenizer.h>
Public Member Functions
N * getNewNode ()
N * getBOSNode ()
N * getEOSNode ()
N * lookup (const char *begin, const char *end)
bool open (const Param &)
void close ()
void clear ()
const DictionaryInfo * dictionary_info () const
const char * what ()
TokenizerImpl ()
virtual ~TokenizerImpl ()
Detailed Description
template<typename N, typename P>
class MeCab::TokenizerImpl< N, P >
Definition at line 22 of file tokenizer.h.
Constructor & Destructor Documentation
template<typename N , typename P > MeCab::TokenizerImpl< N, P >::TokenizerImpl () [inline, explicit]
Definition at line 71 of file tokenizer.cpp.
template<typename N, typename P> virtual MeCab::TokenizerImpl< N, P >::~TokenizerImpl () [inline, virtual]
Definition at line 62 of file tokenizer.h.
Member Function Documentation
template<typename N , typename P > void MeCab::TokenizerImpl< N, P >::clear () [inline]
Definition at line 78 of file tokenizer.cpp.
References MeCab::FreeList< T >::free().
Referenced by MeCab::Viterbi::clear(), MeCab::DecoderLearnerTagger::parse(), and MeCab::OLLearner::run().
template<typename N , typename P > void MeCab::TokenizerImpl< N, P >::close () [inline]
Definition at line 282 of file tokenizer.cpp.
References MeCab::CharProperty::close().
Referenced by MeCab::TokenizerImpl< N, P >::open(), and MeCab::TokenizerImpl< Node, Path >::~TokenizerImpl().
template<typename N , typename P > const DictionaryInfo * MeCab::TokenizerImpl< N, P >::dictionary_info () const [inline]
Definition at line 277 of file tokenizer.cpp.
Referenced by MeCab::TaggerImpl::dictionary_info().
template<typename N , typename P > N * MeCab::TokenizerImpl< N, P >::getBOSNode () [inline]
Definition at line 84 of file tokenizer.cpp.
References BOS_KEY, MeCab::scoped_array< T >::get(), MeCab::TokenizerImpl< N, P >::getNewNode(), and MECAB_BOS_NODE.
Referenced by MeCab::TokenizerImpl< N, P >::getEOSNode(), and MeCab::LearnerTagger::initList().
template<typename N , typename P > N * MeCab::TokenizerImpl< N, P >::getEOSNode () [inline]
Definition at line 96 of file tokenizer.cpp.
References MeCab::TokenizerImpl< N, P >::getBOSNode(), and MECAB_EOS_NODE.
Referenced by MeCab::LearnerTagger::initList().
template<typename N, typename P> N* MeCab::TokenizerImpl< N, P >::getNewNode () [inline]
Definition at line 41 of file tokenizer.h.
Referenced by MeCab::TokenizerImpl< N, P >::getBOSNode(), MeCab::TokenizerImpl< N, P >::lookup(), and MeCab::EncoderLearnerTagger::read().
template<typename N , typename P > N * MeCab::TokenizerImpl< N, P >::lookup (const char * begin, const char * end) [inline]
Definition at line 206 of file tokenizer.cpp.
References ADDUNKNWON, MeCab::CharInfo::default_type, DRESULT_SIZE, MeCab::scoped_array< T >::get(), MeCab::CharProperty::getCharInfo(), MeCab::TokenizerImpl< N, P >::getNewNode(), MeCab::CharInfo::group, MeCab::CharInfo::invoke, MeCab::CharInfo::isKindOf(), MeCab::CharInfo::length, MECAB_NOR_NODE, and MeCab::CharProperty::seekToOtherType().
Referenced by MeCab::LearnerTagger::lookup().
template<typename N , typename P > bool MeCab::TokenizerImpl< N, P >::open (const Param & param) [inline]
Definition at line 103 of file tokenizer.cpp.
References MeCab::FreeList< T >::alloc(), BUF_SIZE, MeCab::Dictionary::charset(), CHECK_CLOSE_FALSE, MeCab::TokenizerImpl< N, P >::close(), MeCab::create_filename(), DEFAULT_MAX_GROUPING_SIZE, MeCab::Dictionary::exactMatchSearch(), MeCab::FreeList< T >::free(), MeCab::CharProperty::getCharInfo(), MeCab::Dictionary::isCompatible(), MeCab::CharProperty::name(), MeCab::CharProperty::open(), MeCab::Dictionary::open(), MeCab::scoped_array< T >::reset(), MeCab::scoped_string::reset_string(), MeCab::CharProperty::set_charset(), MeCab::CharProperty::size(), SYS_DIC_FILE, MeCab::Dictionary::token(), MeCab::Dictionary::token_size(), MeCab::tokenizeCSV(), MeCab::Dictionary::type(), UNK_DIC_FILE, MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::DoubleArrayImpl::result_pair_type::value, MeCab::CharProperty::what(), and MeCab::Dictionary::what().
Referenced by MeCab::TaggerImpl::open(), MeCab::DecoderLearnerTagger::open(), MeCab::CRFLearner::run(), and MeCab::OLLearner::run().
template<typename N, typename P> const char* MeCab::TokenizerImpl< N, P >::what () [inline]
Definition at line 59 of file tokenizer.h.
Referenced by MeCab::TaggerImpl::open(), MeCab::DecoderLearnerTagger::open(), MeCab::CRFLearner::run(), and MeCab::OLLearner::run().
The documentation for this class was generated from the following files:
source/libmecab/tokenizer.h
source/libmecab/tokenizer.cpp