Japanese Morphological Analyzer: MeCab::DecoderLearnerTagger Class Reference
MeCab::DecoderLearnerTagger Class Reference
#include <learner_tagger.h>
Public Member Functions
bool open (const Param &)
bool parse (std::istream *, std::ostream *)
virtual ~DecoderLearnerTagger ()
Detailed Description
Definition at line 69 of file learner_tagger.h.
Constructor & Destructor Documentation
virtual MeCab::DecoderLearnerTagger::~DecoderLearnerTagger () [inline, virtual]
Definition at line 77 of file learner_tagger.h.
References MeCab::LearnerTagger::close().
Member Function Documentation
bool MeCab::DecoderLearnerTagger::open (const Param & param)
Definition at line 46 of file learner_tagger.cpp.
References BUF_SIZE, CHECK_CLOSE_FALSE, MeCab::LearnerTagger::close(), MeCab::LearnerTagger::feature_index_, MeCab::scoped_ptr< T >::get(), MeCab::FeatureIndex::open(), MeCab::TokenizerImpl< N, P >::open(), MeCab::LearnerTagger::path_freelist_, MeCab::scoped_ptr< T >::reset(), MeCab::LearnerTagger::tokenizer_, MeCab::FeatureIndex::what(), and MeCab::TokenizerImpl< N, P >::what().
bool MeCab::DecoderLearnerTagger::parse (std::istream * is, std::ostream * os)
Definition at line 244 of file learner_tagger.cpp.
References MeCab::LearnerTagger::begin_, MeCab::LearnerTagger::begin__, BUF_SIZE, MeCab::LearnerTagger::buildLattice(), MeCab::TokenizerImpl< N, P >::clear(), MeCab::FeatureIndex::clear(), MeCab::LearnerTagger::endNodeList_, MeCab::LearnerTagger::feature_index_, MeCab::FreeList< T >::free(), MeCab::scoped_array< T >::get(), MeCab::LearnerTagger::initList(), MeCab::LearnerTagger::path_freelist_, MeCab::scoped_array< T >::reset(), MeCab::LearnerTagger::tokenizer_, and MeCab::LearnerTagger::viterbi().
The documentation for this class was generated from the following files:
source/libmecab/learner_tagger.h
source/libmecab/learner_tagger.cpp