Japanese Morphological Analyzer: jma::POSTable Class Reference
jma::POSTable Class Reference
POSTable stores the table of part-of-speech tags, each tag includes a string value and its index code.
#include <pos_table.h>
Public Types
enum POSFormat { POS_FORMAT_DEFAULT, POS_FORMAT_ALPHABET, POS_FORMAT_FULL_CATEGORY, POS_FORMAT_NUM }
POS format type.
Public Member Functions
POSTable ()
Constructor.
~POSTable ()
Destructor.
bool loadConfig (const char *fileName, MeCab::Iconv &iconv)
Load the configuration file "pos-id.def", which is in text format.
bool loadCombineRule (const char *fileName)
Load the combination rule file "compound.def", which is in text format.
const char * getPOS (int index, POSFormat format=POS_FORMAT_DEFAULT) const
From POS index code, get POS string in specific format.
const RuleNode * getCombineRule (int startPOS, const MeCab::Node *nextNode) const
Get the longest matched rule to combine the nodes.
int getIndexFromAlphaPOS (const std::string &posStr) const
Get POS index code from POS string in alphabet format.
Detailed Description
POSTable stores the table of part-of-speech tags, each tag includes a string value and its index code.
Note that the string value of part-of-speech tag is in Alphabet format such like "NP-S".
Definition at line 62 of file pos_table.h.
Member Enumeration Documentation
enum jma::POSTable::POSFormat
POS format type.
Enumerator:
POS_FORMAT_DEFAULT
default Japanese format such like "名詞,一般".
POS_FORMAT_ALPHABET
Alphabet format such like "NC-G".
POS_FORMAT_FULL_CATEGORY
Japanese format of furl category such like "名詞,一般,*,*".
POS_FORMAT_NUM
the count of format types
Definition at line 78 of file pos_table.h.
Constructor & Destructor Documentation
jma::POSTable::POSTable ()
Constructor.
Definition at line 26 of file pos_table.cpp.
jma::POSTable::~POSTable ()
Destructor.
Definition at line 31 of file pos_table.cpp.
Member Function Documentation
const RuleNode * jma::POSTable::getCombineRule (int startPOS, const MeCab::Node * nextNode) const
Get the longest matched rule to combine the nodes.
Parameters:
startPOS the POS index code of the start node
nextNode the node next to the start node, the matching process ends before the end-of-sentence node is reached.
Returns:
the leaf Trie node of the longest matched rule for combination, if no rule is found, 0 is returned.
Definition at line 258 of file pos_table.cpp.
References jma::RuleNode::children_, jma::RuleNode::level_, POS_FORMAT_ALPHABET, and jma::RuleNode::target_.
int jma::POSTable::getIndexFromAlphaPOS (const std::string & posStr) const
Get POS index code from POS string in alphabet format.
Parameters:
posStr POS string in alphabet format
Returns:
POS index code, -1 for not found.
Definition at line 293 of file pos_table.cpp.
Referenced by jma::JMA_Knowledge::getUserNounPOSIndex(), loadCombineRule(), and jma::JMA_Knowledge::setKeywordPOS().
const char * jma::POSTable::getPOS (int index, POSFormat format = POS_FORMAT_DEFAULT) const
From POS index code, get POS string in specific format.
Parameters:
index the POS index code
format the POS string format
Returns:
POS string, if non POS is available, the empty string is returned.
Definition at line 156 of file pos_table.cpp.
bool jma::POSTable::loadCombineRule (const char * fileName)
Load the combination rule file "compound.def", which is in text format.
Each entry in this file would be like "NC-G NS-G NC-G", the left two columns are POS to combine from, the last column is POS as combination result.
Parameters:
fileName the file name
Returns:
true for success, false for fail
Attention:
if this function is already called before, the rules previously loaded would be removed.
Definition at line 164 of file pos_table.cpp.
References jma::RuleNode::children_, getIndexFromAlphaPOS(), jma::RuleNode::level_, and jma::RuleNode::target_.
Referenced by jma::JMA_Knowledge::loadDict().
bool jma::POSTable::loadConfig (const char * fileName, MeCab::Iconv & iconv)
Load the configuration file "pos-id.def", which is in text format.
This file contains the part-of-speech configuration, which format is "JapanesePOS index AlphabetPOS".
Parameters:
fileName the file name
iconv to convert the input file's encoding type to run time encoding type
Returns:
true for success, false for fail
Attention:
if this function is already called before, the table previously loaded would be removed.
Definition at line 36 of file pos_table.cpp.
References jma::JMA_Dictionary::getDict(), jma::JMA_Dictionary::instance(), jma::DictUnit::length_, POS_FORMAT_ALPHABET, POS_FORMAT_DEFAULT, POS_FORMAT_FULL_CATEGORY, and jma::DictUnit::text_.
Referenced by jma::JMA_Knowledge::loadDict().
The documentation for this class was generated from the following files:
source/include/pos_table.h
source/src/pos_table.cpp