Japanese Morphological Analyzer: MeCab::scoped_string Class Reference
MeCab::scoped_string Class Reference
#include <scoped_ptr.h>
Public Member Functions
scoped_string ()
scoped_string (const std::string &str)
void reset_string (const std::string &str)
void reset_string (const char *str)
Detailed Description
Definition at line 56 of file scoped_ptr.h.
Constructor & Destructor Documentation
MeCab::scoped_string::scoped_string () [inline, explicit]
Definition at line 58 of file scoped_ptr.h.
References reset_string().
MeCab::scoped_string::scoped_string (const std::string & str) [inline, explicit]
Definition at line 59 of file scoped_ptr.h.
References reset_string().
Member Function Documentation
void MeCab::scoped_string::reset_string (const char * str) [inline]
Definition at line 69 of file scoped_ptr.h.
References MeCab::scoped_array< char >::reset().
void MeCab::scoped_string::reset_string (const std::string & str) [inline]
Definition at line 63 of file scoped_ptr.h.
References MeCab::scoped_array< char >::reset().
Referenced by MeCab::Writer::open(), MeCab::TokenizerImpl< N, P >::open(), MeCab::EncoderLearnerTagger::read(), and scoped_string().
The documentation for this class was generated from the following file:
source/libmecab/scoped_ptr.h