Japanese Morphological Analyzer: JMA_Knowledge_Test Class Reference
JMA_Knowledge_Test Class Reference
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
virtual void loadDictTest ()
virtual void printDict ()
Protected Attributes
JMA_Knowledge * knowledge_
Detailed Description
Definition at line 25 of file unittest_jma_knowledge.cpp.
Member Function Documentation
virtual void JMA_Knowledge_Test::loadDictTest () [inline, protected, virtual]
Definition at line 37 of file unittest_jma_knowledge.cpp.
References jma::Knowledge::addUserDict(), jma::JMA_Knowledge::createTagger(), jma::JMA_Knowledge::getBaseFormOffset(), jma::JMA_Knowledge::getCaseTable(), jma::JMA_Knowledge::getCType(), jma::JMA_Knowledge::getDecompMap(), jma::Knowledge::getEncodeType(), jma::JMA_Knowledge::getKanaTable(), jma::JMA_Knowledge::getNormFormOffset(), jma::JMA_Knowledge::getPOSTable(), jma::JMA_Knowledge::getReadFormOffset(), jma::JMA_Knowledge::getUserNounPOSIndex(), jma::JMA_Knowledge::getWidthTable(), jma::JMA_Knowledge::isSentenceSeparator(), knowledge_, jma::JMA_Knowledge::loadDict(), jma::Knowledge::setSystemDict(), TEST_JMA_DEFAULT_SYSTEM_DICT, and TEST_JMA_DEFAULT_USER_DICT.
virtual void JMA_Knowledge_Test::printDict () [inline, protected, virtual]
Definition at line 69 of file unittest_jma_knowledge.cpp.
virtual void JMA_Knowledge_Test::SetUp () [inline, protected, virtual]
Definition at line 28 of file unittest_jma_knowledge.cpp.
References knowledge_.
virtual void JMA_Knowledge_Test::TearDown () [inline, protected, virtual]
Definition at line 33 of file unittest_jma_knowledge.cpp.
References knowledge_.
Member Data Documentation
JMA_Knowledge* JMA_Knowledge_Test::knowledge_ [protected]
Definition at line 76 of file unittest_jma_knowledge.cpp.
Referenced by loadDictTest(), SetUp(), and TearDown().
The documentation for this class was generated from the following file:
source/unit_test/unittest_jma_knowledge.cpp