Japanese Morphological Analyzer: MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ > Class Template Reference
MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ > Class Template Reference
#include <darts.h>
Classes
struct node_t
struct result_pair_type
struct unit_t
Public Types
typedef array_type_ value_type
typedef node_type_ key_type
typedef array_type_ result_type
Public Member Functions
DoubleArrayImpl ()
~DoubleArrayImpl ()
void set_result (value_type &x, value_type r, size_t)
void set_result (result_pair_type &x, value_type r, size_t l)
void set_array (void *ptr, size_t size=0)
const void * array () const
void clear ()
size_t unit_size () const
size_t size () const
size_t total_size () const
size_t nonzero_size () const
int build (size_t key_size, key_type **key, size_t *length=0, value_type *value=0, int(*progress_func)(size_t, size_t)=0)
int open (const char *file, const char *mode="rb", size_t offset=0, size_t size=0)
int save (const char *file, const char *mode="wb", size_t offset=0)
template<class T >
void exactMatchSearch (const key_type *key, T &result, size_t len=0, size_t node_pos=0)
template<class T >
T exactMatchSearch (const key_type *key, size_t len=0, size_t node_pos=0)
template<class T >
size_t commonPrefixSearch (const key_type *key, T *result, size_t result_len, size_t len=0, size_t node_pos=0)
value_type traverse (const key_type *key, size_t &node_pos, size_t &key_pos, size_t len=0)
Detailed Description
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>>
class MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >
Definition at line 51 of file darts.h.
Member Typedef Documentation
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> typedef node_type_ MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::key_type
Definition at line 212 of file darts.h.
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> typedef array_type_ MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::result_type
Definition at line 213 of file darts.h.
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> typedef array_type_ MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::value_type
Definition at line 211 of file darts.h.
Constructor & Destructor Documentation
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::DoubleArrayImpl () [inline, explicit]
Definition at line 220 of file darts.h.
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::~DoubleArrayImpl () [inline]
Definition at line 223 of file darts.h.
Member Function Documentation
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> const void* MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::array () const [inline]
Definition at line 241 of file darts.h.
Referenced by MeCab::FeatureIndex::convert().
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> int MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::build (size_t key_size, key_type ** key, size_t * length = 0, value_type * value = 0, int(*)(size_t, size_t) progress_func = 0) [inline]
Definition at line 267 of file darts.h.
Referenced by MeCab::FeatureIndex::convert().
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> void MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::clear () [inline]
Definition at line 245 of file darts.h.
Referenced by MeCab::DecoderFeatureIndex::close(), MeCab::Darts::DoubleArrayImpl< char, unsigned char, int, unsigned int >::open(), MeCab::Darts::DoubleArrayImpl< char, unsigned char, int, unsigned int >::set_array(), and MeCab::Darts::DoubleArrayImpl< char, unsigned char, int, unsigned int >::~DoubleArrayImpl().
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> template<class T > size_t MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::commonPrefixSearch (const key_type * key, T * result, size_t result_len, size_t len = 0, size_t node_pos = 0) [inline]
Definition at line 428 of file darts.h.
Referenced by MeCab::Dictionary::commonPrefixSearch().
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> template<class T > T MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::exactMatchSearch (const key_type * key, size_t len = 0, size_t node_pos = 0) [inline]
Definition at line 400 of file darts.h.
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> template<class T > void MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::exactMatchSearch (const key_type * key, T & result, size_t len = 0, size_t node_pos = 0) [inline]
Definition at line 391 of file darts.h.
Referenced by MeCab::Dictionary::exactMatchSearch().
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> size_t MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::nonzero_size () const [inline]
Definition at line 260 of file darts.h.
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> int MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::open (const char * file, const char * mode = "rb", size_t offset = 0, size_t size = 0) [inline]
Definition at line 304 of file darts.h.
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> int MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::save (const char * file, const char * mode = "wb", size_t offset = 0) [inline]
Definition at line 330 of file darts.h.
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> void MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::set_array (void * ptr, size_t size = 0) [inline]
Definition at line 234 of file darts.h.
Referenced by MeCab::DecoderFeatureIndex::open(), and MeCab::Dictionary::open().
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> void MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::set_result (result_pair_type & x, value_type r, size_t l) [inline]
Definition at line 229 of file darts.h.
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> void MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::set_result (value_type & x, value_type r, size_t) [inline]
Definition at line 225 of file darts.h.
Referenced by MeCab::Darts::DoubleArrayImpl< char, unsigned char, int, unsigned int >::commonPrefixSearch(), and MeCab::Darts::DoubleArrayImpl< char, unsigned char, int, unsigned int >::exactMatchSearch().
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> size_t MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::size () const [inline]
Definition at line 257 of file darts.h.
Referenced by MeCab::FeatureIndex::convert(), MeCab::Darts::DoubleArrayImpl< char, unsigned char, int, unsigned int >::open(), and MeCab::Darts::DoubleArrayImpl< char, unsigned char, int, unsigned int >::set_array().
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> size_t MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::total_size () const [inline]
Definition at line 258 of file darts.h.
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> value_type MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::traverse (const key_type * key, size_t & node_pos, size_t & key_pos, size_t len = 0) [inline]
Definition at line 467 of file darts.h.
template<class node_type_, class node_u_type_, class array_type_, class array_u_type_, class length_func_ = Length<node_type_>> size_t MeCab::Darts::DoubleArrayImpl< node_type_, node_u_type_, array_type_, array_u_type_, length_func_ >::unit_size () const [inline]
Definition at line 256 of file darts.h.
Referenced by MeCab::FeatureIndex::convert().
The documentation for this class was generated from the following file:
source/libmecab/darts.h