Japanese Morphological Analyzer: MeCab::HMMLearner Class Reference
MeCab::HMMLearner Class Reference
Static Public Member Functions
static int run (Param *param)
Detailed Description
Definition at line 30 of file learner.cpp.
Member Function Documentation
static int MeCab::HMMLearner::run (Param * param) [inline, static]
Definition at line 32 of file learner.cpp.
References BUF_SIZE, CHECK_DIE, MeCab::FeatureIndex::convert(), DCONF, DICRC, MeCab::enum_csv_dictionaries(), MeCab::escape_csv_element(), MeCab::Param::get(), MeCab::Param::load(), MeCab::DictionaryRewriter::open(), MeCab::Param::program_name(), MeCab::Param::rest_args(), MeCab::DictionaryRewriter::rewrite(), REWRITE_FILE, MeCab::tokenize(), MeCab::tokenize2(), and MeCab::tokenizeCSV().
The documentation for this class was generated from the following file:
source/libmecab/learner.cpp