Japanese Morphological Analyzer: jma::JMA_Dictionary Class Reference
jma::JMA_Dictionary Class Reference
JMA_Dictionary is a collection of DictArchive shared by multiple threads.
#include <jma_dictionary.h>
Public Member Functions
bool open (const char *dirName)
Load the archive file "sys.bin" under dirName.
bool close (const char *dirName)
Close the opened archive file "sys.bin" under dirName.
const DictUnit * getDict (const char *fileName) const
Get a dictionary file.
void debugPrint () const
Print status for debug use.
Static Public Member Functions
static JMA_Dictionary * instance ()
Get the instance of JMA_Dictionary.
static bool compile (const std::vector< std::string > &srcFiles, const char *destFile)
Complile dictionary files srcVec into archive destFile.
Protected Member Functions
JMA_Dictionary ()
Constructor.
virtual ~JMA_Dictionary ()
Destructor.
Friends
class JMA_KnowledgeTest
Detailed Description
JMA_Dictionary is a collection of DictArchive shared by multiple threads.
Definition at line 71 of file jma_dictionary.h.
Constructor & Destructor Documentation
jma::JMA_Dictionary::JMA_Dictionary () [protected]
Constructor.
Definition at line 187 of file jma_dictionary.cpp.
jma::JMA_Dictionary::~JMA_Dictionary () [protected, virtual]
Destructor.
Definition at line 191 of file jma_dictionary.cpp.
Member Function Documentation
bool jma::JMA_Dictionary::close (const char * dirName)
Close the opened archive file "sys.bin" under dirName.
Parameters:
dirName the directory name
Returns:
true for success, false for failure
Definition at line 332 of file jma_dictionary.cpp.
References jma::normalizeDirPath().
Referenced by jma::JMA_Knowledge::~JMA_Knowledge().
bool jma::JMA_Dictionary::compile (const std::vector< std::string > & srcFiles, const char * destFile) [static]
Complile dictionary files srcVec into archive destFile.
Archive format.
Parameters:
srcFiles the file names of dictionary files
destFile the archive file name
Returns:
true for success, false for failure
All the [SECTION] below are rounded up to 512 bytes, the extra space is zero filled.
[TOTAL HEAD] version, 4 bytes file count, 4 bytes total size, 4 bytes (the uncompressed size of all sections below)
multiple [FILE HEAD] (compressed) file name, 500 bytes (terminated with null) file size in bytes, 4 bytes (maximum file size is 4 Gigabytes)
multiple [FILE CONTENT] (compressed)
Definition at line 390 of file jma_dictionary.cpp.
References jma::getFileName().
void jma::JMA_Dictionary::debugPrint () const
Print status for debug use.
Definition at line 497 of file jma_dictionary.cpp.
const DictUnit * jma::JMA_Dictionary::getDict (const char * fileName) const
Get a dictionary file.
Parameters:
fileName the full file name including path
Returns:
the pointer to dictionary file, 0 is returned if not loaded
Definition at line 356 of file jma_dictionary.cpp.
References jma::getDirPath(), and jma::getFileName().
Referenced by jma::POSTable::loadConfig(), and jma::CharTable::loadConfig().
JMA_Dictionary * jma::JMA_Dictionary::instance () [static]
Get the instance of JMA_Dictionary.
Returns:
the pointer to instance
Definition at line 177 of file jma_dictionary.cpp.
Referenced by jma::POSTable::loadConfig(), and jma::CharTable::loadConfig().
bool jma::JMA_Dictionary::open (const char * dirName)
Load the archive file "sys.bin" under dirName.
Parameters:
dirName the directory name
Returns:
true for success, false for failure
Definition at line 202 of file jma_dictionary.cpp.
References jma::createFilePath(), jma::DictArchive::dictMap_, jma::DictUnit::fileName_, jma::DictUnit::length_, jma::normalizeDirPath(), and jma::DictUnit::text_.
Referenced by jma::JMA_Knowledge::loadDict().
Friends And Related Function Documentation
friend class JMA_KnowledgeTest [friend]
Definition at line 126 of file jma_dictionary.h.
The documentation for this class was generated from the following files:
source/include/jma_dictionary.h
source/src/jma_dictionary.cpp