Japanese Morphological Analyzer: MeCab::ContextID Class Reference
MeCab::ContextID Class Reference
#include <context_id.h>
Public Member Functions
void clear ()
void add (const char *l, const char *r)
void addBOS (const char *l, const char *r)
bool save (const char *lfile, const char *rfile)
bool build ()
bool open (const char *lfile, const char *rfile, Iconv *iconv=0)
int lid (const char *l) const
int rid (const char *r) const
size_t left_size () const
size_t right_size () const
const std::map< std::string,
int > & left_ids () const
const std::map< std::string,
int > & right_ids () const
bool is_valid (size_t lid, size_t rid)
Detailed Description
Definition at line 19 of file context_id.h.
Member Function Documentation
void MeCab::ContextID::add (const char * l, const char * r)
Definition at line 69 of file context_id.cpp.
void MeCab::ContextID::addBOS (const char * l, const char * r)
Definition at line 74 of file context_id.cpp.
bool MeCab::ContextID::build ()
Definition at line 91 of file context_id.cpp.
Referenced by MeCab::DictionaryGenerator::run().
void MeCab::ContextID::clear ()
Definition at line 62 of file context_id.cpp.
bool MeCab::ContextID::is_valid (size_t lid, size_t rid) [inline]
Definition at line 45 of file context_id.h.
References left_size(), and right_size().
const std::map<std::string, int>& MeCab::ContextID::left_ids () const [inline]
Definition at line 42 of file context_id.h.
size_t MeCab::ContextID::left_size () const [inline]
Definition at line 39 of file context_id.h.
Referenced by is_valid().
int MeCab::ContextID::lid (const char * l) const
Definition at line 95 of file context_id.cpp.
References CHECK_DIE.
bool MeCab::ContextID::open (const char * lfile, const char * rfile, Iconv * iconv = 0)
Definition at line 84 of file context_id.cpp.
int MeCab::ContextID::rid (const char * r) const
Definition at line 102 of file context_id.cpp.
References CHECK_DIE.
const std::map<std::string, int>& MeCab::ContextID::right_ids () const [inline]
Definition at line 43 of file context_id.h.
size_t MeCab::ContextID::right_size () const [inline]
Definition at line 40 of file context_id.h.
Referenced by is_valid().
bool MeCab::ContextID::save (const char * lfile, const char * rfile)
Definition at line 79 of file context_id.cpp.
Referenced by MeCab::DictionaryGenerator::run().
The documentation for this class was generated from the following files:
source/libmecab/context_id.h
source/libmecab/context_id.cpp