Japanese Morphological Analyzer: MeCab::DictionaryRewriter Class Reference
MeCab::DictionaryRewriter Class Reference
#include <dictionary_rewriter.h>
Public Member Functions
bool open (const char *filename, Iconv *iconv=0)
void clear ()
bool rewrite (const std::string &feature, std::string *ufeature, std::string *lfeature, std::string *rfeature) const
bool rewrite2 (const std::string &feature, std::string *ufeature, std::string *lfeature, std::string *rfeature)
Detailed Description
Definition at line 44 of file dictionary_rewriter.h.
Member Function Documentation
void MeCab::DictionaryRewriter::clear ()
Definition at line 131 of file dictionary_rewriter.cpp.
Referenced by MeCab::EncoderFeatureIndex::clearcache().
bool MeCab::DictionaryRewriter::open (const char * filename, Iconv * iconv = 0)
Definition at line 133 of file dictionary_rewriter.cpp.
References CHECK_DIE, and MeCab::Iconv::convert().
Referenced by MeCab::FeatureIndex::openTemplate(), MeCab::HMMLearner::run(), and MeCab::DictionaryGenerator::run().
bool MeCab::DictionaryRewriter::rewrite (const std::string & feature, std::string * ufeature, std::string * lfeature, std::string * rfeature) const
Definition at line 162 of file dictionary_rewriter.cpp.
References BUF_SIZE, CHECK_DIE, MeCab::RewriteRules::rewrite(), and MeCab::tokenizeCSV().
Referenced by rewrite2(), and MeCab::HMMLearner::run().
bool MeCab::DictionaryRewriter::rewrite2 (const std::string & feature, std::string * ufeature, std::string * lfeature, std::string * rfeature)
Definition at line 181 of file dictionary_rewriter.cpp.
References MeCab::FeatureSet::lfeature, rewrite(), MeCab::FeatureSet::rfeature, and MeCab::FeatureSet::ufeature.
Referenced by MeCab::EncoderFeatureIndex::buildFeature(), and MeCab::DecoderFeatureIndex::buildFeature().
The documentation for this class was generated from the following files:
source/libmecab/dictionary_rewriter.h
source/libmecab/dictionary_rewriter.cpp