Japanese Morphological Analyzer: MeCab::Mutex Class Reference
MeCab::Mutex Class Reference
#include <mutex.h>
Public Member Functions
const char * what ()
Mutex ()
virtual ~Mutex ()
void lock ()
void unlock ()
Detailed Description
Definition at line 34 of file mutex.h.
Constructor & Destructor Documentation
MeCab::Mutex::Mutex () [inline]
Definition at line 63 of file mutex.h.
References WHAT.
virtual MeCab::Mutex::~Mutex () [inline, virtual]
Definition at line 64 of file mutex.h.
Member Function Documentation
void MeCab::Mutex::lock () [inline]
Definition at line 65 of file mutex.h.
Referenced by MeCab::MemoryPool< _Key, _Value >::get(), MeCab::MemoryPool< _Key, _Value >::lock(), MeCab::MemoryPool< _Key, _Value >::release(), setGlobalError(), and MeCab::MemoryPool< _Key, _Value >::~MemoryPool().
void MeCab::Mutex::unlock () [inline]
Definition at line 66 of file mutex.h.
Referenced by MeCab::MemoryPool< _Key, _Value >::get(), MeCab::MemoryPool< _Key, _Value >::release(), setGlobalError(), MeCab::MemoryPool< _Key, _Value >::unlock(), and MeCab::MemoryPool< _Key, _Value >::~MemoryPool().
const char* MeCab::Mutex::what () [inline]
Definition at line 46 of file mutex.h.
References MeCab::whatlog::str().
The documentation for this class was generated from the following file:
source/libmecab/mutex.h