Japanese Morphological Analyzer: MeCab::TestSentenceGenerator Class Reference
MeCab::TestSentenceGenerator Class Reference
Static Public Member Functions
static int run (int argc, char **argv)
Detailed Description
Definition at line 197 of file eval.cpp.
Member Function Documentation
static int MeCab::TestSentenceGenerator::run (int argc, char ** argv) [inline, static]
Definition at line 199 of file eval.cpp.
References BUF_SIZE, CHECK_DIE, COPYRIGHT, MeCab::Param::get(), MeCab::Param::help_version(), MeCab::Param::open(), MeCab::Param::rest_args(), MeCab::tokenize(), and MeCab::Param::what().
Referenced by mecab_test_gen().
The documentation for this class was generated from the following file:
source/libmecab/eval.cpp