Japanese Morphological Analyzer: jma::Iconv Class Reference
jma::Iconv Class Reference
#include <iconv_utils.h>
Public Member Functions
Iconv ()
virtual ~Iconv ()
bool open (Knowledge::EncodeType from, Knowledge::EncodeType to)
bool convert (std::string *)
Detailed Description
Definition at line 31 of file iconv_utils.h.
Constructor & Destructor Documentation
jma::Iconv::Iconv () [explicit]
Definition at line 179 of file iconv_utils.cpp.
jma::Iconv::~Iconv () [virtual]
Definition at line 184 of file iconv_utils.cpp.
Member Function Documentation
bool jma::Iconv::convert (std::string * str)
Definition at line 92 of file iconv_utils.cpp.
References jma::scoped_array< T >::get().
Referenced by jma::POSTable::loadConfig(), and jma::KanaTable::loadConfig().
bool jma::Iconv::open (Knowledge::EncodeType from, Knowledge::EncodeType to)
Definition at line 61 of file iconv_utils.cpp.
Referenced by jma::POSTable::loadConfig(), and jma::KanaTable::loadConfig().
The documentation for this class was generated from the following files:
source/include/iconv_utils.h
source/src/iconv_utils.cpp