Japanese Morphological Analyzer: AnalyzerThread Class Reference
AnalyzerThread Class Reference
Public Member Functions
AnalyzerThread ()
~AnalyzerThread ()
void run ()
Public Attributes
unsigned int id_
string input_
string output_
Analyzer * analyzer_
Knowledge * knowledge_
Detailed Description
Definition at line 57 of file test_jma_multithread.cpp.
Constructor & Destructor Documentation
AnalyzerThread::AnalyzerThread () [inline]
Definition at line 65 of file test_jma_multithread.cpp.
AnalyzerThread::~AnalyzerThread () [inline]
Definition at line 67 of file test_jma_multithread.cpp.
References analyzer_, and knowledge_.
Member Function Documentation
void AnalyzerThread::run () [inline]
Definition at line 74 of file test_jma_multithread.cpp.
References analyzer_, jma::createFilePath(), jma::getFileName(), id_, input_, output_, and jma::Analyzer::runWithStream().
Member Data Documentation
Analyzer* AnalyzerThread::analyzer_
Definition at line 62 of file test_jma_multithread.cpp.
Referenced by run(), and ~AnalyzerThread().
unsigned int AnalyzerThread::id_
Definition at line 59 of file test_jma_multithread.cpp.
Referenced by run().
string AnalyzerThread::input_
Definition at line 60 of file test_jma_multithread.cpp.
Referenced by run().
Knowledge* AnalyzerThread::knowledge_
Definition at line 63 of file test_jma_multithread.cpp.
Referenced by ~AnalyzerThread().
string AnalyzerThread::output_
Definition at line 61 of file test_jma_multithread.cpp.
Referenced by run().
The documentation for this class was generated from the following file:
source/test/test_jma_multithread.cpp