Japanese Morphological Analyzer: MeCab::EncoderFeatureIndex Class Reference
MeCab::EncoderFeatureIndex Class Reference
#include <feature_index.h>
Public Member Functions
bool open (const Param &param)
void close ()
void clear ()
bool save (const char *filename)
void shrink (size_t, std::vector< double > *)
bool buildFeature (LearnerPath *path)
void clearcache ()
Detailed Description
Definition at line 70 of file feature_index.h.
Member Function Documentation
bool MeCab::EncoderFeatureIndex::buildFeature (LearnerPath * path) [virtual]
Implements MeCab::FeatureIndex.
Definition at line 218 of file feature_index.cpp.
References MeCab::FeatureIndex::buildUnigramFeature(), CHECK_DIE, MeCab::StringBuffer::clear(), MeCab::FeatureIndex::os_, MeCab::DictionaryRewriter::rewrite2(), MeCab::FeatureIndex::rewrite_, and MeCab::StringBuffer::str().
void MeCab::EncoderFeatureIndex::clear () [virtual]
Implements MeCab::FeatureIndex.
Definition at line 145 of file feature_index.cpp.
void MeCab::EncoderFeatureIndex::clearcache ()
Definition at line 147 of file feature_index.cpp.
References MeCab::DictionaryRewriter::clear(), and MeCab::FeatureIndex::rewrite_.
void MeCab::EncoderFeatureIndex::close () [virtual]
Implements MeCab::FeatureIndex.
Definition at line 152 of file feature_index.cpp.
References MeCab::FeatureIndex::maxid_.
bool MeCab::EncoderFeatureIndex::open (const Param & param) [virtual]
Implements MeCab::FeatureIndex.
Definition at line 116 of file feature_index.cpp.
References MeCab::FeatureIndex::openTemplate().
bool MeCab::EncoderFeatureIndex::save (const char * filename)
Definition at line 504 of file feature_index.cpp.
References MeCab::FeatureIndex::alpha_, and CHECK_FALSE.
void MeCab::EncoderFeatureIndex::shrink (size_t freq, std::vector< double > * observed)
Definition at line 403 of file feature_index.cpp.
References MeCab::FeatureIndex::maxid_.
The documentation for this class was generated from the following files:
source/libmecab/feature_index.h
source/libmecab/feature_index.cpp