Japanese Morphological Analyzer: source/libmecab/eval.cpp File Reference
source/libmecab/eval.cpp File Reference
#include <cstdio>
#include <iostream>
#include <map>
#include <fstream>
#include <vector>
#include "mecab.h"
#include "stream_wrapper.h"
#include "param.h"
#include "common.h"
#include "utils.h"
Classes
class MeCab::Eval
class MeCab::TestSentenceGenerator
Namespaces
namespace MeCab
Functions
int mecab_system_eval (int argc, char **argv)
int mecab_test_gen (int argc, char **argv)
Function Documentation
int mecab_system_eval (int argc, char ** argv)
Definition at line 252 of file eval.cpp.
References MeCab::Eval::eval().
Referenced by main().
int mecab_test_gen (int argc, char ** argv)
Definition at line 256 of file eval.cpp.
References MeCab::TestSentenceGenerator::run().
Referenced by main().