Japanese Morphological Analyzer: source/libmecab/libmecab.cpp File Reference
source/libmecab/libmecab.cpp File Reference
#include "mecab.h"
#include "mutex.h"
#include "utils.h"
#include "tokenizer.h"
Classes
struct mecab_t
Defines
#define MECAB_CHECK_FIRST_ARG(c, t)
#define MECAB_CHECK_FIRST_ARG_VOID(c, t)
Functions
MeCab::Mutex * getGlobalMutex ()
std::string * getStaticErrorString ()
const char * getGlobalError ()
void setGlobalError (const char *str)
mecab_t * mecab_new (int argc, char **argv)
mecab_t * mecab_new2 (const char *arg)
const char * mecab_version ()
const char * mecab_strerror (mecab_t *c)
void mecab_destroy (mecab_t *c)
int mecab_get_partial (mecab_t *c)
void mecab_set_partial (mecab_t *c, int partial)
float mecab_get_theta (mecab_t *c)
void mecab_set_theta (mecab_t *c, float theta)
int mecab_get_lattice_level (mecab_t *c)
void mecab_set_lattice_level (mecab_t *c, int level)
int mecab_get_all_morphs (mecab_t *c)
void mecab_set_all_morphs (mecab_t *c, int all_morphs)
const char * mecab_sparse_tostr (mecab_t *c, const char *str)
const char * mecab_sparse_tostr2 (mecab_t *c, const char *str, size_t len)
char * mecab_sparse_tostr3 (mecab_t *c, const char *str, size_t len, char *out, size_t len2)
const mecab_node_t * mecab_sparse_tonode (mecab_t *c, const char *str)
const mecab_node_t * mecab_sparse_tonode2 (mecab_t *c, const char *str, size_t len)
const char * mecab_nbest_sparse_tostr (mecab_t *c, size_t N, const char *str)
const char * mecab_nbest_sparse_tostr2 (mecab_t *c, size_t N, const char *str, size_t len)
char * mecab_nbest_sparse_tostr3 (mecab_t *c, size_t N, const char *str, size_t len, char *out, size_t len2)
int mecab_nbest_init (mecab_t *c, const char *str)
int mecab_nbest_init2 (mecab_t *c, const char *str, size_t len)
const char * mecab_nbest_next_tostr (mecab_t *c)
char * mecab_nbest_next_tostr2 (mecab_t *c, char *out, size_t len2)
const mecab_node_t * mecab_nbest_next_tonode (mecab_t *c)
const char * mecab_format_node (mecab_t *c, const mecab_node_t *n)
const mecab_dictionary_info_t * mecab_dictionary_info (mecab_t *c)
Define Documentation
#define MECAB_CHECK_FIRST_ARG (c, t)
Value:
if (!(c) || (c)->allocated != LIBMECAB_ID) {          \
    setGlobalError("first argment seems invalid");      \
    return 0;                                           \
  } MeCab::Tagger *(t) = (c)->ptr;
Definition at line 116 of file libmecab.cpp.
Referenced by mecab_dictionary_info(), mecab_format_node(), mecab_get_all_morphs(), mecab_get_lattice_level(), mecab_get_partial(), mecab_get_theta(), mecab_nbest_init(), mecab_nbest_init2(), mecab_nbest_next_tonode(), mecab_nbest_next_tostr(), mecab_nbest_next_tostr2(), mecab_nbest_sparse_tostr(), mecab_nbest_sparse_tostr2(), mecab_nbest_sparse_tostr3(), mecab_sparse_tonode(), mecab_sparse_tonode2(), mecab_sparse_tostr(), mecab_sparse_tostr2(), and mecab_sparse_tostr3().
#define MECAB_CHECK_FIRST_ARG_VOID (c, t)
Value:
if (!(c) || (c)->allocated != LIBMECAB_ID) {          \
    setGlobalError("first argment seems invalid");      \
    return;                                             \
  } MeCab::Tagger *(t) = (c)->ptr;
Definition at line 122 of file libmecab.cpp.
Referenced by mecab_set_all_morphs(), mecab_set_lattice_level(), mecab_set_partial(), and mecab_set_theta().
Function Documentation
const char* getGlobalError ()
Definition at line 33 of file libmecab.cpp.
References getStaticErrorString().
Referenced by MeCab::getTaggerError(), and mecab_strerror().
MeCab::Mutex* getGlobalMutex ()
Definition at line 23 of file libmecab.cpp.
Referenced by setGlobalError().
std::string* getStaticErrorString ()
Definition at line 28 of file libmecab.cpp.
Referenced by getGlobalError(), and setGlobalError().
void mecab_destroy (mecab_t * c)
Definition at line 108 of file libmecab.cpp.
References mecab_t::allocated, and mecab_t::ptr.
const mecab_dictionary_info_t* mecab_dictionary_info (mecab_t * c)
Definition at line 244 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
const char* mecab_format_node (mecab_t * c, const mecab_node_t * n)
Definition at line 239 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
int mecab_get_all_morphs (mecab_t * c)
Definition at line 158 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
int mecab_get_lattice_level (mecab_t * c)
Definition at line 148 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
int mecab_get_partial (mecab_t * c)
Definition at line 128 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
float mecab_get_theta (mecab_t * c)
Definition at line 138 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
int mecab_nbest_init (mecab_t * c, const char * str)
Definition at line 214 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
int mecab_nbest_init2 (mecab_t * c, const char * str, size_t len)
Definition at line 219 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
const mecab_node_t* mecab_nbest_next_tonode (mecab_t * c)
Definition at line 234 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
const char* mecab_nbest_next_tostr (mecab_t * c)
Definition at line 224 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
char* mecab_nbest_next_tostr2 (mecab_t * c, char * out, size_t len2)
Definition at line 229 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
const char* mecab_nbest_sparse_tostr (mecab_t * c, size_t N, const char * str)
Definition at line 195 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
const char* mecab_nbest_sparse_tostr2 (mecab_t * c, size_t N, const char * str, size_t len)
Definition at line 201 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
char* mecab_nbest_sparse_tostr3 (mecab_t * c, size_t N, const char * str, size_t len, char * out, size_t len2)
Definition at line 207 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
mecab_t* mecab_new (int argc, char ** argv)
Definition at line 70 of file libmecab.cpp.
References mecab_t::allocated, c, MeCab::createTagger(), MeCab::getTaggerError(), mecab_t::ptr, and setGlobalError().
mecab_t* mecab_new2 (const char * arg)
Definition at line 84 of file libmecab.cpp.
References mecab_t::allocated, c, MeCab::createTagger(), MeCab::getTaggerError(), mecab_t::ptr, and setGlobalError().
void mecab_set_all_morphs (mecab_t * c, int all_morphs)
Definition at line 163 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG_VOID.
void mecab_set_lattice_level (mecab_t * c, int level)
Definition at line 153 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG_VOID.
void mecab_set_partial (mecab_t * c, int partial)
Definition at line 133 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG_VOID.
void mecab_set_theta (mecab_t * c, float theta)
Definition at line 143 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG_VOID.
const mecab_node_t* mecab_sparse_tonode (mecab_t * c, const char * str)
Definition at line 184 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
const mecab_node_t* mecab_sparse_tonode2 (mecab_t * c, const char * str, size_t len)
Definition at line 189 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
const char* mecab_sparse_tostr (mecab_t * c, const char * str)
Definition at line 168 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
const char* mecab_sparse_tostr2 (mecab_t * c, const char * str, size_t len)
Definition at line 173 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
char* mecab_sparse_tostr3 (mecab_t * c, const char * str, size_t len, char * out, size_t len2)
Definition at line 178 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
const char* mecab_strerror (mecab_t * c)
Definition at line 102 of file libmecab.cpp.
References mecab_t::allocated, getGlobalError(), and mecab_t::ptr.
const char* mecab_version ()
Definition at line 98 of file libmecab.cpp.
void setGlobalError (const char * str)
Definition at line 37 of file libmecab.cpp.
References getGlobalMutex(), getStaticErrorString(), MeCab::Mutex::lock(), and MeCab::Mutex::unlock().
Referenced by MeCab::createTagger(), mecab_new(), and mecab_new2().