Japanese Morphological Analyzer: source/libmecab/mecab.h File Reference
source/libmecab/mecab.h File Reference
#include <stdio.h>
Classes
struct mecab_dictionary_info_t
struct mecab_path_t
struct mecab_learner_path_t
struct mecab_token_t
struct mecab_node_t
struct mecab_learner_node_t
Defines
#define MECAB_NOR_NODE (0)
#define MECAB_UNK_NODE (1)
#define MECAB_BOS_NODE (2)
#define MECAB_EOS_NODE (3)
#define MECAB_EON_NODE (4)
#define MECAB_USR_DIC (1)
#define MECAB_SYS_DIC (0)
#define MECAB_UNK_DIC (2)
#define MECAB_DLL_EXTERN extern
Typedefs
typedef struct mecab_t mecab_t
typedef struct
mecab_dictionary_info_t mecab_dictionary_info_t
typedef struct mecab_node_t mecab_node_t
typedef struct mecab_learner_node_t mecab_learner_node_t
typedef struct mecab_path_t mecab_path_t
typedef struct mecab_learner_path_t mecab_learner_path_t
typedef struct mecab_token_t mecab_token_t
Functions
MECAB_DLL_EXTERN int mecab_do (int argc, char **argv)
MECAB_DLL_EXTERN mecab_t * mecab_new (int argc, char **argv)
MECAB_DLL_EXTERN mecab_t * mecab_new2 (const char *arg)
MECAB_DLL_EXTERN const char * mecab_version ()
MECAB_DLL_EXTERN const char * mecab_strerror (mecab_t *mecab)
MECAB_DLL_EXTERN void mecab_destroy (mecab_t *mecab)
MECAB_DLL_EXTERN int mecab_get_partial (mecab_t *mecab)
MECAB_DLL_EXTERN void mecab_set_partial (mecab_t *mecab, int partial)
MECAB_DLL_EXTERN float mecab_get_theta (mecab_t *mecab)
MECAB_DLL_EXTERN void mecab_set_theta (mecab_t *mecab, float theta)
MECAB_DLL_EXTERN int mecab_get_lattice_level (mecab_t *mecab)
MECAB_DLL_EXTERN void mecab_set_lattice_level (mecab_t *mecab, int level)
MECAB_DLL_EXTERN int mecab_get_all_morphs (mecab_t *mecab)
MECAB_DLL_EXTERN void mecab_set_all_morphs (mecab_t *mecab, int all_morphs)
MECAB_DLL_EXTERN const char * mecab_sparse_tostr (mecab_t *mecab, const char *str)
MECAB_DLL_EXTERN const char * mecab_sparse_tostr2 (mecab_t *mecab, const char *str, size_t len)
MECAB_DLL_EXTERN char * mecab_sparse_tostr3 (mecab_t *mecab, const char *str, size_t len, char *ostr, size_t olen)
MECAB_DLL_EXTERN const
mecab_node_t * mecab_sparse_tonode (mecab_t *mecab, const char *)
MECAB_DLL_EXTERN const
mecab_node_t * mecab_sparse_tonode2 (mecab_t *mecab, const char *, size_t)
MECAB_DLL_EXTERN const char * mecab_nbest_sparse_tostr (mecab_t *mecab, size_t N, const char *str)
MECAB_DLL_EXTERN const char * mecab_nbest_sparse_tostr2 (mecab_t *mecab, size_t N, const char *str, size_t len)
MECAB_DLL_EXTERN char * mecab_nbest_sparse_tostr3 (mecab_t *mecab, size_t N, const char *str, size_t len, char *ostr, size_t olen)
MECAB_DLL_EXTERN int mecab_nbest_init (mecab_t *mecab, const char *str)
MECAB_DLL_EXTERN int mecab_nbest_init2 (mecab_t *mecab, const char *str, size_t len)
MECAB_DLL_EXTERN const char * mecab_nbest_next_tostr (mecab_t *mecab)
MECAB_DLL_EXTERN char * mecab_nbest_next_tostr2 (mecab_t *mecab, char *ostr, size_t olen)
MECAB_DLL_EXTERN const
mecab_node_t * mecab_nbest_next_tonode (mecab_t *mecab)
MECAB_DLL_EXTERN const char * mecab_format_node (mecab_t *mecab, const mecab_node_t *node)
MECAB_DLL_EXTERN const
mecab_dictionary_info_t * mecab_dictionary_info (mecab_t *mecab)
MECAB_DLL_EXTERN int mecab_dict_index (int argc, char **argv)
MECAB_DLL_EXTERN int mecab_dict_gen (int argc, char **argv)
MECAB_DLL_EXTERN int mecab_cost_train (int argc, char **argv)
MECAB_DLL_EXTERN int mecab_system_eval (int argc, char **argv)
MECAB_DLL_EXTERN int mecab_test_gen (int argc, char **argv)
Define Documentation
#define MECAB_BOS_NODE (2)
Definition at line 112 of file mecab.h.
Referenced by MeCab::TokenizerImpl< N, P >::getBOSNode(), MeCab::is_empty(), MeCab::NBestGenerator::next(), and MeCab::Writer::writeNode().
#define MECAB_DLL_EXTERN extern
Definition at line 141 of file mecab.h.
#define MECAB_EON_NODE (4)
Definition at line 114 of file mecab.h.
Referenced by MeCab::TaggerImpl::parseNBest(), and MeCab::Writer::writeNode().
#define MECAB_EOS_NODE (3)
Definition at line 113 of file mecab.h.
Referenced by MeCab::calc_expectation(), MeCab::calc_online_update(), MeCab::FeatureIndex::calcCost(), MeCab::TokenizerImpl< N, P >::getEOSNode(), MeCab::is_empty(), MeCab::EncoderLearnerTagger::read(), and MeCab::Writer::writeNode().
#define MECAB_NOR_NODE (0)
Definition at line 110 of file mecab.h.
Referenced by MeCab::Dictionary::compile(), MeCab::TokenizerImpl< N, P >::lookup(), MeCab::EncoderLearnerTagger::read(), and MeCab::Writer::writeNode().
#define MECAB_SYS_DIC (0)
Definition at line 117 of file mecab.h.
Referenced by MeCab::DictionaryComplier::run().
#define MECAB_UNK_DIC (2)
Definition at line 118 of file mecab.h.
Referenced by MeCab::Dictionary::compile(), and MeCab::DictionaryComplier::run().
#define MECAB_UNK_NODE (1)
Definition at line 111 of file mecab.h.
Referenced by MeCab::node_cmp_eq(), and MeCab::Writer::writeNode().
#define MECAB_USR_DIC (1)
Definition at line 116 of file mecab.h.
Referenced by MeCab::DictionaryComplier::run().
Typedef Documentation
typedef struct mecab_dictionary_info_t mecab_dictionary_info_t
Definition at line 145 of file mecab.h.
typedef struct mecab_learner_node_t mecab_learner_node_t
Definition at line 147 of file mecab.h.
typedef struct mecab_learner_path_t mecab_learner_path_t
Definition at line 149 of file mecab.h.
typedef struct mecab_node_t mecab_node_t
Definition at line 146 of file mecab.h.
typedef struct mecab_path_t mecab_path_t
Definition at line 148 of file mecab.h.
typedef struct mecab_t mecab_t
Definition at line 144 of file mecab.h.
typedef struct mecab_token_t mecab_token_t
Definition at line 150 of file mecab.h.
Function Documentation
MECAB_DLL_EXTERN int mecab_cost_train (int argc, char ** argv)
Definition at line 677 of file learner.cpp.
References MeCab::Learner::run().
Referenced by main().
MECAB_DLL_EXTERN void mecab_destroy (mecab_t * mecab)
Definition at line 108 of file libmecab.cpp.
References mecab_t::allocated, and mecab_t::ptr.
MECAB_DLL_EXTERN int mecab_dict_gen (int argc, char ** argv)
Definition at line 336 of file dictionary_generator.cpp.
References MeCab::DictionaryGenerator::run().
Referenced by main().
MECAB_DLL_EXTERN int mecab_dict_index (int argc, char ** argv)
Definition at line 159 of file dictionary_compiler.cpp.
References MeCab::DictionaryComplier::run().
Referenced by jma::JMA_Knowledge::encodeSystemDict(), and main().
MECAB_DLL_EXTERN const mecab_dictionary_info_t* mecab_dictionary_info (mecab_t * mecab)
Definition at line 244 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN int mecab_do (int argc, char ** argv)
Definition at line 404 of file tagger.cpp.
References MeCab::_max(), MeCab::_min(), BUF_SIZE, MeCab::TaggerImpl::dictionary_info(), MeCab::Param::dump_config(), EXIT_FAILURE, EXIT_SUCCESS, MeCab::scoped_array< T >::get(), MeCab::Param::get(), MAX_INPUT_BUFFER_SIZE, MIN_INPUT_BUFFER_SIZE, NBEST_MAX, MeCab::TaggerImpl::open(), MeCab::Param::open(), MeCab::TaggerImpl::parse(), MeCab::TaggerImpl::parseNBest(), MeCab::Param::rest_args(), MeCab::Param::set(), MeCab::TaggerImpl::what(), MeCab::Param::what(), and WHAT_ERROR.
Referenced by main().
MECAB_DLL_EXTERN const char* mecab_format_node (mecab_t * mecab, const mecab_node_t * node)
Definition at line 239 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN int mecab_get_all_morphs (mecab_t * mecab)
Definition at line 158 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN int mecab_get_lattice_level (mecab_t * mecab)
Definition at line 148 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN int mecab_get_partial (mecab_t * mecab)
Definition at line 128 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN float mecab_get_theta (mecab_t * mecab)
Definition at line 138 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN int mecab_nbest_init (mecab_t * mecab, const char * str)
Definition at line 214 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN int mecab_nbest_init2 (mecab_t * mecab, const char * str, size_t len)
Definition at line 219 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN const mecab_node_t* mecab_nbest_next_tonode (mecab_t * mecab)
Definition at line 234 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN const char* mecab_nbest_next_tostr (mecab_t * mecab)
Definition at line 224 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN char* mecab_nbest_next_tostr2 (mecab_t * mecab, char * ostr, size_t olen)
Definition at line 229 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN const char* mecab_nbest_sparse_tostr (mecab_t * mecab, size_t N, const char * str)
Definition at line 195 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN const char* mecab_nbest_sparse_tostr2 (mecab_t * mecab, size_t N, const char * str, size_t len)
Definition at line 201 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN char* mecab_nbest_sparse_tostr3 (mecab_t * mecab, size_t N, const char * str, size_t len, char * ostr, size_t olen)
Definition at line 207 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN mecab_t* mecab_new (int argc, char ** argv)
Definition at line 70 of file libmecab.cpp.
References mecab_t::allocated, c, MeCab::createTagger(), MeCab::getTaggerError(), mecab_t::ptr, and setGlobalError().
MECAB_DLL_EXTERN mecab_t* mecab_new2 (const char * arg)
Definition at line 84 of file libmecab.cpp.
References mecab_t::allocated, c, MeCab::createTagger(), MeCab::getTaggerError(), mecab_t::ptr, and setGlobalError().
MECAB_DLL_EXTERN void mecab_set_all_morphs (mecab_t * mecab, int all_morphs)
Definition at line 163 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG_VOID.
MECAB_DLL_EXTERN void mecab_set_lattice_level (mecab_t * mecab, int level)
Definition at line 153 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG_VOID.
MECAB_DLL_EXTERN void mecab_set_partial (mecab_t * mecab, int partial)
Definition at line 133 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG_VOID.
MECAB_DLL_EXTERN void mecab_set_theta (mecab_t * mecab, float theta)
Definition at line 143 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG_VOID.
MECAB_DLL_EXTERN const mecab_node_t* mecab_sparse_tonode (mecab_t * mecab, const char *)
Definition at line 184 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN const mecab_node_t* mecab_sparse_tonode2 (mecab_t * mecab, const char * , size_t)
Definition at line 189 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN const char* mecab_sparse_tostr (mecab_t * mecab, const char * str)
Definition at line 168 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN const char* mecab_sparse_tostr2 (mecab_t * mecab, const char * str, size_t len)
Definition at line 173 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN char* mecab_sparse_tostr3 (mecab_t * mecab, const char * str, size_t len, char * ostr, size_t olen)
Definition at line 178 of file libmecab.cpp.
References MECAB_CHECK_FIRST_ARG.
MECAB_DLL_EXTERN const char* mecab_strerror (mecab_t * mecab)
Definition at line 102 of file libmecab.cpp.
References mecab_t::allocated, getGlobalError(), and mecab_t::ptr.
MECAB_DLL_EXTERN int mecab_system_eval (int argc, char ** argv)
Definition at line 252 of file eval.cpp.
References MeCab::Eval::eval().
Referenced by main().
MECAB_DLL_EXTERN int mecab_test_gen (int argc, char ** argv)
Definition at line 256 of file eval.cpp.
References MeCab::TestSentenceGenerator::run().
Referenced by main().
MECAB_DLL_EXTERN const char* mecab_version ()
Definition at line 98 of file libmecab.cpp.