Japanese Morphological Analyzer: jma Namespace Reference
jma Namespace Reference
namespace of library JMA (Japanese Morphological Analyzer)
Classes
class Analyzer
Analyzer executes the Japanese morphological analysis.
class JMA_Factory
JMA_Factory creates instances for Japanese morphological analysis.
class Knowledge
Knowledge manages the linguistic information for Japanese morphological analysis.
struct Morpheme
Morpheme is a pair of lexicon string and its part-of-speech tag.
class Sentence
Sentence saves the results of Japanese morphological analysis.
class CharTable
CharTable stores the mapping table between characters from one type to another.
class JMA_Analyzer
JMA_Analyzer executes the Japanese morphological analysis based on conditional random field.
class JMA_CType
JMA_CType gives the character type information.
class JMA_CType_EUCJP
class JMA_CType_SJIS
class JMA_CType_UTF8
JMA_CType_UTF8 gives the character type information in UTF-8 encoding.
struct DictUnit
DictUnit is a dictionary file in archive.
struct DictArchive
DictArchive is a system dictionary as an archive of dictionary files.
class JMA_Dictionary
JMA_Dictionary is a collection of DictArchive shared by multiple threads.
class JMA_UserDictionary
JMA_UserDictionary is a collection of user dictionaries shared by multiple threads.
class JMA_Knowledge
JMA_Knowledge manages the linguistic information for Japanese morphological analysis.
struct RuleNode
RuleNode is a Trie node, the path from root to leaf means a rule to combine POS.
class POSTable
POSTable stores the table of part-of-speech tags, each tag includes a string value and its index code.
class CTypeTokenizer
Tokenizer tokenizes a raw input string in specific encoding to a sequence of characters.
Typedefs
typedef std::vector< Morpheme > MorphemeList
A list of morphemes.
typedef std::map< std::string,
DictUnit > DictMap
mapping from dictionary file name to dictionary instance
Functions
bool createTempFile (std::string &tempName)
Create a unique temporary file and output its file name.
bool removeFile (const std::string &fileName)
Delete the file on disk.
bool isDirExist (const char *dirPath)
Check whether the directory exists.
bool copyFile (const char *src, const char *dest)
Copy a file from source path to destination path.
std::string createFilePath (const char *dir, const char *file)
Create the complete file path from directory path and file name.
std::string getFileName (const std::string &path)
Extract file name from path string.
std::string getDirPath (const std::string &filePath)
Extract directory path from file path.
std::string normalizeDirPath (const std::string &dirPath)
Normalize directory path.
bool isSameMorphemeList (const MorphemeList *list1, const MorphemeList *list2, bool printPOS)
Whether the two MorphemeLists is the same.
string * getMapValue (map< string, string > &map, const string &key)
Detailed Description
namespace of library JMA (Japanese Morphological Analyzer)
Typedef Documentation
typedef std::map<std::string, DictUnit> jma::DictMap
mapping from dictionary file name to dictionary instance
Definition at line 42 of file jma_dictionary.h.
typedef std::vector<Morpheme> jma::MorphemeList
A list of morphemes.
Definition at line 71 of file sentence.h.
Function Documentation
bool jma::copyFile (const char * src, const char * dest) [inline]
Copy a file from source path to destination path.
Parameters:
src the source path
dest the destination path
Returns:
true for copy successfully, false for copy failed.
Definition at line 150 of file file_utils.h.
std::string jma::createFilePath (const char * dir, const char * file) [inline]
Create the complete file path from directory path and file name.
Parameters:
dir the directory path
file the file name
Returns:
the file path string consisting of directory path and file name.
Precondition:
the file name file is assumed as non empty.
Definition at line 191 of file file_utils.h.
References PATH_DELIMIT_CHECK, and PATH_DELIMIT_CREATE.
Referenced by jma::JMA_Knowledge::loadDict(), main(), jma::JMA_Dictionary::open(), and AnalyzerThread::run().
bool jma::createTempFile (std::string & tempName) [inline]
Create a unique temporary file and output its file name.
It is commented out as the temporary file is replaced with memory.
Parameters:
tempName the string to save the temporary file name
Returns:
true for success and tempName is set as the temporary file name. false for fail and tempName is not modified.
Definition at line 45 of file file_utils.h.
std::string jma::getDirPath (const std::string & filePath) [inline]
Extract directory path from file path.
Parameters:
filePath the file path such as "/usr/bin/man", "c:\\windows\\winhelp.exe", or "man"
Returns:
the directory path such as "/usr/bin", "c:\\windows", "."
Definition at line 226 of file file_utils.h.
References PATH_DELIMIT_CHECK.
Referenced by jma::JMA_Dictionary::getDict(), and main().
std::string jma::getFileName (const std::string & path) [inline]
Extract file name from path string.
Parameters:
path the path such as "/usr/bin/man", "c:\\windows\\winhelp.exe", or "man"
Returns:
the file name such as "man", "winhelp.exe"
Definition at line 211 of file file_utils.h.
References PATH_DELIMIT_CHECK.
Referenced by jma::JMA_Dictionary::compile(), jma::JMA_Dictionary::getDict(), and AnalyzerThread::run().
string* jma::getMapValue (map< string, string > & map, const string & key) [inline]
Definition at line 164 of file jma_knowledge.cpp.
bool jma::isDirExist (const char * dirPath) [inline]
Check whether the directory exists.
Parameters:
dirPath the directory path to be checked
Returns:
true for the direcotory exists, false for not exists.
Definition at line 107 of file file_utils.h.
References PATH_DELIMIT_CHECK.
bool jma::isSameMorphemeList (const MorphemeList * list1, const MorphemeList * list2, bool printPOS) [inline]
Whether the two MorphemeLists is the same.
Parameters:
list1 the MorphemeList 1
list2 the MorphemeList 2
printPOS whether also compare POS result
Returns:
true for the same, false for not the same
Definition at line 158 of file jma_analyzer.cpp.
References jma::Morpheme::lexicon_, jma::Morpheme::posCode_, and jma::Morpheme::posStr_.
Referenced by jma::JMA_Analyzer::runNBest().
std::string jma::normalizeDirPath (const std::string & dirPath) [inline]
Normalize directory path.
Parameters:
dirPath the directory path such as "/usr/bin/", "/usr/bin", "c:\\windows\\", "c:\\windows", "./", "."
Returns:
the normalized directory path such as "/usr/bin", "c:\\windows", "."
Definition at line 247 of file file_utils.h.
References PATH_DELIMIT_CHECK.
Referenced by jma::JMA_Dictionary::close(), and jma::JMA_Dictionary::open().
bool jma::removeFile (const std::string & fileName) [inline]
Delete the file on disk.
Parameters:
fileName the name of the file to be deleted
Returns:
true for success and false for fail.
Definition at line 94 of file file_utils.h.
Referenced by TEST_F().