Japanese Morphological Analyzer: MeCab Namespace Reference
MeCab Namespace Reference
Namespaces
namespace Darts
Classes
struct CharInfo
class CharProperty
class die
class warn
struct whatlog
class wlog
class Connector
class ContextID
class Dictionary
class DictionaryComplier
class DictionaryGenerator
class RewritePattern
class RewriteRules
struct FeatureSet
class DictionaryRewriter
class POSIDGenerator
class Eval
class TestSentenceGenerator
class FeatureIndex
class EncoderFeatureIndex
class DecoderFeatureIndex
class FreeList
class ChunkFreeList
class Iconv
class LBFGS
class HMMLearner
class OLLearner
class CRFLearner
class Learner
class LearnerTagger
class EncoderLearnerTagger
class DecoderLearnerTagger
class MemoryPool
class Mmap
class Mutex
class NBestGenerator
struct Option
class Param
class scoped_ptr
class scoped_array
class scoped_string
class istream_wrapper
class ostream_wrapper
class StringBuffer
class TaggerImpl
class thread
class TokenizerImpl
class Viterbi
class Writer
Typedefs
typedef TokenizerImpl< Node, Path > Tokenizer
typedef TokenizerImpl
< LearnerNode, LearnerPath > LearnerTokenizer
Enumerations
enum {
EUC_JP, CP932, UTF8, UTF16,
UTF16LE, UTF16BE, ASCII
}
Functions
int progress_bar_darts (size_t current, size_t total)
short int tocost (double d, int n, int default_cost)
void copy (const char *src, const char *dst)
template<class T1 , class T2 >
T1 repeat_find_if (T1 b, T1 e, const T2 &v, size_t n)
bool node_cmp_eq (const LearnerNode &node1, const LearnerNode &node2, size_t size, size_t unk_size)
bool is_empty (LearnerPath *path)
void calc_expectation (LearnerPath *path, double *expected, double Z)
void calc_online_update (LearnerPath *path, double *expected)
void calc_alpha (LearnerNode *n)
void calc_beta (LearnerNode *n)
template<class _Key , class _Value >
MemoryPool< _Key, _Value > & getMemoryPool ()
void init_param (std::string *help, std::string *version, const std::string &system_name, const Option *opts)
Tagger * createTagger (int argc, char **argv)
Tagger * createTagger (const char *argv)
const char * getTaggerError ()
unsigned short utf8_to_ucs2 (const char *begin, const char *end, size_t *mblen)
unsigned short ascii_to_ucs2 (const char *begin, const char *end, size_t *mblen)
unsigned short utf16be_to_ucs2 (const char *begin, const char *end, size_t *mblen)
unsigned short utf16le_to_ucs2 (const char *begin, const char *end, size_t *mblen)
unsigned short utf16_to_ucs2 (const char *begin, const char *end, size_t *mblen)
unsigned short euc_to_ucs2 (const char *begin, const char *end, size_t *mblen)
unsigned short cp932_to_ucs2 (const char *begin, const char *end, size_t *mblen)
int decode_charset (const char *charset)
std::string create_filename (const std::string &path, const std::string &file)
void remove_filename (std::string *s)
void remove_pathname (std::string *s)
void replace_string (std::string *s, const std::string &src, const std::string &dst)
void enum_csv_dictionaries (const char *path, std::vector< std::string > *dics)
bool toLower (std::string *s)
bool escape_csv_element (std::string *w)
int progress_bar (const char *message, size_t current, size_t total)
bool load_dictionary_resource (Param *param)
template<class T >
T _min (T x, T y)
template<class T >
T _max (T x, T y)
void dtoa (double val, char *s)
template<class T >
void itoa (T val, char *s)
template<class T >
void uitoa (T val, char *s)
const char * read_ptr (const char **ptr, size_t size)
template<class T >
void read_static (const char **ptr, T &value)
template<class Iterator >
size_t tokenizeCSV (char *str, Iterator out, size_t max)
template<class Iterator >
size_t tokenize (char *str, const char *del, Iterator out, size_t max)
template<class Iterator >
size_t tokenize2 (char *str, const char *del, Iterator out, size_t max)
double logsumexp (double x, double y, bool flg)
char getEscapedChar (const char p)
Typedef Documentation
typedef TokenizerImpl<LearnerNode, LearnerPath> MeCab::LearnerTokenizer
Definition at line 66 of file tokenizer.h.
typedef TokenizerImpl<Node, Path> MeCab::Tokenizer
Definition at line 65 of file tokenizer.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
EUC_JP
CP932
UTF8
UTF16
UTF16LE
UTF16BE
ASCII
Definition at line 29 of file utils.h.
Function Documentation
template<class T > T MeCab::_max (T x, T y) [inline]
Definition at line 25 of file utils.h.
Referenced by MeCab::ChunkFreeList< char >::alloc(), init_param(), logsumexp(), mecab_do(), MeCab::OLLearner::run(), and tocost().
template<class T > T MeCab::_min (T x, T y) [inline]
Definition at line 24 of file utils.h.
Referenced by logsumexp(), mecab_do(), and tocost().
unsigned short MeCab::ascii_to_ucs2 (const char * begin, const char * end, size_t * mblen) [inline]
Definition at line 56 of file ucs.h.
Referenced by MeCab::CharProperty::getCharInfo().
void MeCab::calc_alpha (LearnerNode * n) [inline]
Definition at line 89 of file learner_node.h.
References logsumexp().
Referenced by MeCab::EncoderLearnerTagger::gradient().
void MeCab::calc_beta (LearnerNode * n) [inline]
Definition at line 97 of file learner_node.h.
References logsumexp().
Referenced by MeCab::EncoderLearnerTagger::gradient().
void MeCab::calc_expectation (LearnerPath * path, double * expected, double Z) [inline]
Definition at line 56 of file learner_node.h.
References c, is_empty(), and MECAB_EOS_NODE.
Referenced by MeCab::EncoderLearnerTagger::gradient().
void MeCab::calc_online_update (LearnerPath * path, double * expected) [inline]
Definition at line 74 of file learner_node.h.
References is_empty(), and MECAB_EOS_NODE.
Referenced by MeCab::EncoderLearnerTagger::online_update().
void MeCab::copy (const char * src, const char * dst)
Definition at line 35 of file dictionary_generator.cpp.
References MeCab::Mmap< T >::begin(), CHECK_DIE, MeCab::Mmap< T >::open(), MeCab::Mmap< T >::size(), and MeCab::Mmap< T >::what().
Referenced by MeCab::DictionaryGenerator::run(), and vectorToString().
unsigned short MeCab::cp932_to_ucs2 (const char * begin, const char * end, size_t * mblen) [inline]
Definition at line 128 of file ucs.h.
Referenced by MeCab::CharProperty::getCharInfo().
std::string MeCab::create_filename (const std::string & path, const std::string & file)
Definition at line 67 of file utils.cpp.
Referenced by enum_csv_dictionaries(), load_dictionary_resource(), MeCab::TokenizerImpl< N, P >::open(), MeCab::Connector::open(), MeCab::CharProperty::open(), and MeCab::FeatureIndex::openTemplate().
Tagger* MeCab::createTagger (const char * argv)
Definition at line 389 of file tagger.cpp.
References MeCab::TaggerImpl::open(), setGlobalError(), and MeCab::TaggerImpl::what().
Tagger* MeCab::createTagger (int argc, char ** argv)
Definition at line 379 of file tagger.cpp.
References MeCab::TaggerImpl::open(), setGlobalError(), and MeCab::TaggerImpl::what().
Referenced by mecab_new(), and mecab_new2().
int MeCab::decode_charset (const char * charset)
Definition at line 40 of file utils.cpp.
References ASCII, CP932, EUC_JP, toLower(), UTF16, UTF16BE, UTF16LE, and UTF8.
Referenced by MeCab::Dictionary::isCompatible(), and MeCab::CharProperty::set_charset().
void MeCab::dtoa (double val, char * s) [inline]
Definition at line 32 of file utils.h.
void MeCab::enum_csv_dictionaries (const char * path, std::vector< std::string > * dics)
Definition at line 131 of file utils.cpp.
References CHECK_DIE, create_filename(), and toLower().
Referenced by MeCab::HMMLearner::run(), MeCab::DictionaryGenerator::run(), and MeCab::DictionaryComplier::run().
bool MeCab::escape_csv_element (std::string * w)
Definition at line 177 of file utils.cpp.
Referenced by MeCab::RewritePattern::rewrite(), and MeCab::HMMLearner::run().
unsigned short MeCab::euc_to_ucs2 (const char * begin, const char * end, size_t * mblen) [inline]
Definition at line 103 of file ucs.h.
Referenced by MeCab::CharProperty::getCharInfo().
char MeCab::getEscapedChar (const char p) [inline]
Definition at line 205 of file utils.h.
Referenced by MeCab::FeatureIndex::buildBigramFeature(), MeCab::FeatureIndex::buildUnigramFeature(), and MeCab::Writer::writeNode().
template<class _Key , class _Value > MemoryPool<_Key, _Value>& MeCab::getMemoryPool () [inline]
Definition at line 104 of file mempool.h.
const char* MeCab::getTaggerError ()
Definition at line 399 of file tagger.cpp.
References getGlobalError().
Referenced by mecab_new(), and mecab_new2().
void MeCab::init_param (std::string * help, std::string * version, const std::string & system_name, const Option * opts)
Definition at line 22 of file param.cpp.
References _max(), MeCab::Option::arg_description, COPYRIGHT, MeCab::Option::description, max, MeCab::Option::name, and MeCab::Option::short_name.
Referenced by MeCab::Param::open().
bool MeCab::is_empty (LearnerPath * path) [inline]
Definition at line 51 of file learner_node.h.
References MECAB_BOS_NODE, and MECAB_EOS_NODE.
Referenced by calc_expectation(), calc_online_update(), and MeCab::FeatureIndex::calcCost().
template<class T > void MeCab::itoa (T val, char * s) [inline]
Definition at line 41 of file utils.h.
bool MeCab::load_dictionary_resource (Param * param)
Definition at line 214 of file utils.cpp.
References BUF_SIZE, create_filename(), DICRC, MeCab::Param::get(), MeCab::Param::load(), remove_filename(), replace_string(), and MeCab::Param::set().
Referenced by MeCab::TaggerImpl::open().
double MeCab::logsumexp (double x, double y, bool flg) [inline]
Definition at line 192 of file utils.h.
References _max(), _min(), and MINUS_LOG_EPSILON.
Referenced by calc_alpha(), and calc_beta().
bool MeCab::node_cmp_eq (const LearnerNode & node1, const LearnerNode & node2, size_t size, size_t unk_size) [inline]
Definition at line 30 of file learner_node.h.
References MECAB_UNK_NODE, and repeat_find_if().
Referenced by MeCab::EncoderLearnerTagger::eval(), and MeCab::EncoderLearnerTagger::read().
int MeCab::progress_bar (const char * message, size_t current, size_t total)
Definition at line 191 of file utils.cpp.
Referenced by MeCab::Connector::compile(), and progress_bar_darts().
int MeCab::progress_bar_darts (size_t current, size_t total)
Definition at line 25 of file dictionary.cpp.
References progress_bar().
Referenced by MeCab::Dictionary::compile().
const char* MeCab::read_ptr (const char ** ptr, size_t size) [inline]
Definition at line 81 of file utils.h.
Referenced by MeCab::CharProperty::open(), and read_static().
template<class T > void MeCab::read_static (const char ** ptr, T & value) [inline]
Definition at line 88 of file utils.h.
References read_ptr().
void MeCab::remove_filename (std::string * s)
Definition at line 79 of file utils.cpp.
Referenced by load_dictionary_resource().
void MeCab::remove_pathname (std::string * s)
Definition at line 101 of file utils.cpp.
Referenced by MeCab::DictionaryGenerator::run().
template<class T1 , class T2 > T1 MeCab::repeat_find_if (T1 b, T1 e, const T2 & v, size_t n) [inline]
Definition at line 17 of file learner_node.h.
Referenced by node_cmp_eq().
void MeCab::replace_string (std::string * s, const std::string & src, const std::string & dst)
Definition at line 123 of file utils.cpp.
Referenced by load_dictionary_resource().
short int MeCab::tocost (double d, int n, int default_cost)
Definition at line 25 of file dictionary_generator.cpp.
References _max(), _min(), max, and min.
template<class Iterator > size_t MeCab::tokenize (char * str, const char * del, Iterator out, size_t max) [inline]
Definition at line 152 of file utils.h.
Referenced by MeCab::EncoderLearnerTagger::read(), MeCab::HMMLearner::run(), and MeCab::TestSentenceGenerator::run().
template<class Iterator > size_t MeCab::tokenize2 (char * str, const char * del, Iterator out, size_t max) [inline]
Definition at line 172 of file utils.h.
Referenced by MeCab::Connector::compile(), MeCab::CharProperty::compile(), MeCab::FeatureIndex::convert(), MeCab::POSIDGenerator::open(), MeCab::FeatureIndex::openTemplate(), MeCab::Connector::openText(), and MeCab::HMMLearner::run().
template<class Iterator > size_t MeCab::tokenizeCSV (char * str, Iterator out, size_t max) [inline]
Definition at line 113 of file utils.h.
Referenced by MeCab::FeatureIndex::buildBigramFeature(), MeCab::FeatureIndex::buildUnigramFeature(), MeCab::Dictionary::compile(), MeCab::CharProperty::compile(), MeCab::POSIDGenerator::id(), MeCab::TokenizerImpl< N, P >::open(), MeCab::DictionaryRewriter::rewrite(), MeCab::HMMLearner::run(), MeCab::RewritePattern::set_pattern(), and MeCab::Writer::writeNode().
bool MeCab::toLower (std::string * s)
Definition at line 166 of file utils.cpp.
References c.
Referenced by decode_charset(), enum_csv_dictionaries(), MeCab::Learner::run(), and MeCab::DictionaryGenerator::run().
template<class T > void MeCab::uitoa (T val, char * s) [inline]
Definition at line 65 of file utils.h.
unsigned short MeCab::utf16_to_ucs2 (const char * begin, const char * end, size_t * mblen) [inline]
Definition at line 92 of file ucs.h.
References utf16be_to_ucs2(), and utf16le_to_ucs2().
Referenced by MeCab::CharProperty::getCharInfo().
unsigned short MeCab::utf16be_to_ucs2 (const char * begin, const char * end, size_t * mblen) [inline]
Definition at line 61 of file ucs.h.
Referenced by MeCab::CharProperty::getCharInfo(), and utf16_to_ucs2().
unsigned short MeCab::utf16le_to_ucs2 (const char * begin, const char * end, size_t * mblen) [inline]
Definition at line 77 of file ucs.h.
Referenced by MeCab::CharProperty::getCharInfo(), and utf16_to_ucs2().
unsigned short MeCab::utf8_to_ucs2 (const char * begin, const char * end, size_t * mblen) [inline]
Definition at line 20 of file ucs.h.
Referenced by MeCab::CharProperty::getCharInfo().