Japanese Morphological Analyzer: source/include/strutil.h File Reference
source/include/strutil.h File Reference
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <iterator>
#include <algorithm>
#include <functional>
#include <string.h>
Classes
class fCapitals
Defines
#define SPACES " \t\r\n"
Functions
string trimRight (const string &s, const string &t=SPACES)
void trimRightSelf (string &d, const string &t=SPACES)
string trimLeft (const string &s, const string &t=SPACES)
void trimLeftSelf (string &d, const string &t=SPACES)
string trim (const string &s, const string &t=SPACES)
void trimSelf (string &d, const string &t=SPACES)
string toLower (const string &s)
void toLowerSelf (string &d)
string toUpper (const string &s)
string toCapitals (const string &s)
bool replace (string &str1, const string &str2, const string &str3)
bool replaceAll (string &str1, const string &str2, const string &str3)
string getWord (string &s, const string delim=" ", const bool trim_spaces=true)
void stringToVector (const string &s, vector< string > &v, const string delim=" ", const bool trim_spaces=true)
string vectorToString (const vector< string > &v, const string delim=" ")
string depTrim (const string &s, const string &t=SPACES)
void tokenizeAndLowerCase (vector< string > &vec, string text, const char *delimiter)
size_t computeLength (const string &str, bool isWordLan)
vector< size_t > * findTokens (const string &str, bool isWordLan)
Define Documentation
#define SPACES " \t\r\n"
Definition at line 21 of file strutil.h.
Function Documentation
size_t computeLength (const string & str, bool isWordLan) [inline]
Definition at line 289 of file strutil.h.
string depTrim (const string & s, const string & t = SPACES) [inline]
Definition at line 244 of file strutil.h.
References stringToVector().
vector<size_t>* findTokens (const string & str, bool isWordLan) [inline]
Definition at line 314 of file strutil.h.
string getWord (string & s, const string delim = " ", const bool trim_spaces = true) [inline]
Definition at line 167 of file strutil.h.
References trim().
Referenced by stringToVector().
bool replace (string & str1, const string & str2, const string & str3) [inline]
Definition at line 138 of file strutil.h.
Referenced by replaceAll(), jma::JMA_CType_UTF8::replaceSpaces(), jma::JMA_CType_SJIS::replaceSpaces(), and jma::JMA_CType_EUCJP::replaceSpaces().
bool replaceAll (string & str1, const string & str2, const string & str3) [inline]
Definition at line 154 of file strutil.h.
References replace().
void stringToVector (const string & s, vector< string > & v, const string delim = " ", const bool trim_spaces = true) [inline]
Definition at line 202 of file strutil.h.
References getWord(), and trim().
Referenced by depTrim().
string toCapitals (const string & s) [inline]
Definition at line 130 of file strutil.h.
void tokenizeAndLowerCase (vector< string > & vec, string text, const char * delimiter) [inline]
Definition at line 266 of file strutil.h.
References toLowerSelf(), and trimSelf().
string toLower (const string & s) [inline]
Definition at line 67 of file strutil.h.
Referenced by jma::Knowledge::decodeEncodeType(), enum_csv_dictionaries(), and fCapitals::operator()().
void toLowerSelf (string & d) [inline]
Definition at line 75 of file strutil.h.
Referenced by tokenizeAndLowerCase().
string toUpper (const string & s) [inline]
Definition at line 96 of file strutil.h.
Referenced by fCapitals::operator()().
string trim (const string & s, const string & t = SPACES) [inline]
Definition at line 54 of file strutil.h.
References trimLeft(), and trimRight().
Referenced by getWord(), and stringToVector().
string trimLeft (const string & s, const string & t = SPACES) [inline]
Definition at line 42 of file strutil.h.
Referenced by trim().
void trimLeftSelf (string & d, const string & t = SPACES) [inline]
Definition at line 48 of file strutil.h.
Referenced by trimSelf().
string trimRight (const string & s, const string & t = SPACES) [inline]
Definition at line 23 of file strutil.h.
Referenced by trim().
void trimRightSelf (string & d, const string & t = SPACES) [inline]
Definition at line 34 of file strutil.h.
Referenced by trimSelf().
void trimSelf (string & d, const string & t = SPACES) [inline]
Definition at line 60 of file strutil.h.
References trimLeftSelf(), and trimRightSelf().
Referenced by main(), and tokenizeAndLowerCase().
string vectorToString (const vector< string > & v, const string delim = " ") [inline]
Definition at line 227 of file strutil.h.
References MeCab::copy().