Japanese Morphological Analyzer: MeCab::whatlog Struct Reference
MeCab::whatlog Struct Reference
#include <common.h>
Public Member Functions
const char * str ()
Public Attributes
std::ostringstream stream_
std::string str_
jmp_buf cond_
Detailed Description
Definition at line 110 of file common.h.
Member Function Documentation
const char* MeCab::whatlog::str () [inline]
Definition at line 113 of file common.h.
References str_, and stream_.
Referenced by MeCab::Writer::what(), MeCab::Viterbi::what(), MeCab::TaggerImpl::what(), MeCab::Param::what(), MeCab::Mutex::what(), MeCab::Mmap< char >::what(), MeCab::LearnerTagger::what(), MeCab::FeatureIndex::what(), MeCab::Dictionary::what(), MeCab::Connector::what(), MeCab::CharProperty::what(), and MeCab::TokenizerImpl< Node, Path >::what().
Member Data Documentation
jmp_buf MeCab::whatlog::cond_
Definition at line 117 of file common.h.
Referenced by MeCab::wlog::~wlog().
std::string MeCab::whatlog::str_
Definition at line 112 of file common.h.
Referenced by str().
std::ostringstream MeCab::whatlog::stream_
Definition at line 111 of file common.h.
Referenced by str(), and MeCab::wlog::wlog().
The documentation for this struct was generated from the following file:
source/libmecab/common.h