Japanese Morphological Analyzer: source/libmecab/tagger.cpp File Reference
source/libmecab/tagger.cpp File Reference
#include <cstring>
#include <iostream>
#include "viterbi.h"
#include "common.h"
#include "param.h"
#include "mecab.h"
#include "string_buffer.h"
#include "writer.h"
#include "connector.h"
#include "nbest_generator.h"
#include "stream_wrapper.h"
Classes
class MeCab::TaggerImpl
Namespaces
namespace MeCab
Defines
#define WHAT_ERROR(msg)
Functions
const char * getGlobalError ()
void setGlobalError (const char *str)
Tagger * MeCab::createTagger (int argc, char **argv)
Tagger * MeCab::createTagger (const char *argv)
const char * MeCab::getTaggerError ()
int mecab_do (int argc, char **argv)
Define Documentation
#define WHAT_ERROR (msg)
Value:
do {                    \
    std::cout << msg << std::endl;              \
    return EXIT_FAILURE; }                      \
  while (0);
Referenced by mecab_do().
Function Documentation
const char* getGlobalError ()
Definition at line 33 of file libmecab.cpp.
References getStaticErrorString().
Referenced by MeCab::getTaggerError(), and mecab_strerror().
int mecab_do (int argc, char ** argv)
Definition at line 404 of file tagger.cpp.
References MeCab::_max(), MeCab::_min(), BUF_SIZE, MeCab::TaggerImpl::dictionary_info(), MeCab::Param::dump_config(), EXIT_FAILURE, EXIT_SUCCESS, MeCab::scoped_array< T >::get(), MeCab::Param::get(), MAX_INPUT_BUFFER_SIZE, MIN_INPUT_BUFFER_SIZE, NBEST_MAX, MeCab::TaggerImpl::open(), MeCab::Param::open(), MeCab::TaggerImpl::parse(), MeCab::TaggerImpl::parseNBest(), MeCab::Param::rest_args(), MeCab::Param::set(), MeCab::TaggerImpl::what(), MeCab::Param::what(), and WHAT_ERROR.
Referenced by main().
void setGlobalError (const char * str)
Definition at line 37 of file libmecab.cpp.
References getGlobalMutex(), getStaticErrorString(), MeCab::Mutex::lock(), and MeCab::Mutex::unlock().
Referenced by MeCab::createTagger(), mecab_new(), and mecab_new2().