Japanese Morphological Analyzer: source/test/test_jma_ctype.cpp File Reference
source/test/test_jma_ctype.cpp File Reference
Test JMA_CType in processing EUC-JP, Shift-JIS, UTF-8 characters.
#include "jma_ctype.h"
#include <cassert>
#include <iostream>
#include <fstream>
#include <string>
#include <stdlib.h>
#include <string.h>
Functions
void testGetByteCount (JMA_CType *ctype, const char *str)
Test method getByteCount.
void printUsage ()
Print the test usage.
int main (int argc, char *argv[])
Main function.
Detailed Description
Test JMA_CType in processing EUC-JP, Shift-JIS, UTF-8 characters.
Below is the usage examples:
 Read characters from test data file in UTF-8 encoding, and print those characters information to standard output.
 $./test_jma_ctype --encode utf8 ../db/test/test_jma_ctype_utf8.txt
Author:
Jun Jiang
Version:
0.1
Date:
Jul 17, 2009
Definition in file test_jma_ctype.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function.
Definition at line 82 of file test_jma_ctype.cpp.
References printUsage(), and testGetByteCount().
void printUsage ()
Print the test usage.
Definition at line 74 of file test_jma_ctype.cpp.
void testGetByteCount (JMA_CType * ctype, const char * str)
Test method getByteCount.
Definition at line 35 of file test_jma_ctype.cpp.
References jma::JMA_CType::getByteCount(), and jma::JMA_CType::length().
Referenced by main().