Japanese Morphological Analyzer: source/test/test_jma_run.cpp File Reference
source/test/test_jma_run.cpp File Reference
Test JMA in Japanese word segmentation and POS tagging analysis.
#include "jma_factory.h"
#include "analyzer.h"
#include "knowledge.h"
#include "sentence.h"
#include "test_jma_common.h"
#include <iostream>
#include <fstream>
#include <cassert>
#include <string>
#include <ctime>
#include <string.h>
#include <stdlib.h>
Functions
void testWithSentence (Analyzer *analyzer)
Analyze a sentence.
void testWithString (Analyzer *analyzer)
Analyze a string.
void testWithStream (Analyzer *analyzer, const char *source, const char *dest)
Analyze a stream.
void printUsage ()
Print the test usage.
int main (int argc, char *argv[])
Main function.
Detailed Description
Test JMA in Japanese word segmentation and POS tagging analysis.
Below is the usage examples: The "DICT_PATH" in below examples is the dictionary path, which is "../db/jumandic/bin_eucjp" defautly.
 To analyze a sentence from standard input and print 5 n-best results to standard output.
 $ ./jma_run --sentence 5 [--dict DICT_PATH]
 To analyze a paragraph string from standard input and print the one-best result to standard output.
 $ ./jma_run --string [--dict DICT_PATH]
 To exit the loop in the above examples, please press CTRL-C.
 To analyze the raw input file "INPUT", and print the one-best result to "OUTPUT".
 (the example of "INPUT" file could be available as "../db/test/asahi_test_raw_eucjp.txt")
 $ ./jma_run --stream INPUT OUTPUT [--dict DICT_PATH]
Author:
Jun Jiang
Version:
0.1
Date:
Jul 2, 2009
Definition in file test_jma_run.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function.
Definition at line 162 of file test_jma_run.cpp.
References pthread_t_data::analyzer, jma::JMA_Factory::createAnalyzer(), jma::JMA_Factory::createKnowledge(), jma::Knowledge::loadDict(), printUsage(), jma::Knowledge::setEncodeType(), jma::Analyzer::setKnowledge(), jma::Analyzer::setOption(), jma::Knowledge::setSystemDict(), TEST_JMA_DEFAULT_SYSTEM_DICT, testWithSentence(), testWithStream(), and testWithString().
void printUsage ()
Print the test usage.
Definition at line 152 of file test_jma_run.cpp.
void testWithSentence (Analyzer * analyzer)
Analyze a sentence.
Definition at line 55 of file test_jma_run.cpp.
References jma::Sentence::getBaseForm(), jma::Sentence::getCount(), jma::Sentence::getLexicon(), jma::Sentence::getListSize(), jma::Sentence::getOneBestIndex(), jma::Sentence::getScore(), jma::Sentence::getStrPOS(), jma::Analyzer::runWithSentence(), and jma::Sentence::setString().
void testWithStream (Analyzer * analyzer, const char * source, const char * dest)
Analyze a stream.
Definition at line 133 of file test_jma_run.cpp.
References jma::Analyzer::runWithStream().
void testWithString (Analyzer * analyzer)
Analyze a string.
Definition at line 117 of file test_jma_run.cpp.
References jma::Analyzer::runWithString().
Referenced by main().