Japanese Morphological Analyzer: source/test/test_jma_multithread.cpp File Reference
source/test/test_jma_multithread.cpp File Reference
Test JMA in multithread environment.
#include "ijma.h"
#include "test_jma_common.h"
#include "thread.h"
#include "file_utils.h"
#include <iostream>
#include <sstream>
#include <cassert>
#include <string>
#include <vector>
#include <cstring>
#include <cstdlib>
Classes
class AnalyzerThread
Defines
#define TEST_CASE_SINGLE_KNOWLEDGE 0
multihreads share single knowledge
#define TEST_CASE_MULTI_KNOWLEDGE 1
each thread creates its own knowledge, and each knowledge shares single system dictionary
#define TEST_CASE_MULTI_SYS_DICT 2
each thread creates its own knowledge, and the knowledges shares multiple system dictionaries
#define TEST_CASE_NUM TEST_CASE_SINGLE_KNOWLEDGE
current test case
#define TEST_USER_DICT 0
whether test user dictionary
#define PAUSE_BEFORE_DESTROY 0
whether pause for user input before destroy resources
Functions
void printUsage ()
Print the test usage.
int main (int argc, char *argv[])
Main function.
Detailed Description
Test JMA in multithread environment.
Below is the usage examples: The "DICT_PATH" in below examples is the dictionary path, which is "../db/ipadic/bin_eucjp" defautly.
 Each thread prints its own output.
 $ ./jma_multithread INPUT_FILE OUTPUT_DIR [--dict DICT_PATH] [--num THREAD_NUM]
Author:
Jun
Version:
0.1
Date:
Sep 1, 2010
Definition in file test_jma_multithread.cpp.
Define Documentation
#define PAUSE_BEFORE_DESTROY 0
whether pause for user input before destroy resources
Definition at line 45 of file test_jma_multithread.cpp.
#define TEST_CASE_MULTI_KNOWLEDGE 1
each thread creates its own knowledge, and each knowledge shares single system dictionary
Definition at line 33 of file test_jma_multithread.cpp.
#define TEST_CASE_MULTI_SYS_DICT 2
each thread creates its own knowledge, and the knowledges shares multiple system dictionaries
Definition at line 36 of file test_jma_multithread.cpp.
#define TEST_CASE_NUM TEST_CASE_SINGLE_KNOWLEDGE
current test case
Definition at line 39 of file test_jma_multithread.cpp.
Referenced by main().
#define TEST_CASE_SINGLE_KNOWLEDGE 0
multihreads share single knowledge
Definition at line 30 of file test_jma_multithread.cpp.
#define TEST_USER_DICT 0
whether test user dictionary
Definition at line 42 of file test_jma_multithread.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function.
Definition at line 102 of file test_jma_multithread.cpp.
References jma::Knowledge::addUserDict(), jma::JMA_Factory::createAnalyzer(), jma::createFilePath(), jma::JMA_Factory::createKnowledge(), jma::getDirPath(), jma::Knowledge::getEncodeType(), jma::Knowledge::loadDict(), printUsage(), jma::Knowledge::setSystemDict(), TEST_CASE_NUM, TEST_JMA_DEFAULT_SYSTEM_DICT, and TEST_JMA_DEFAULT_USER_DICT.
void printUsage ()
Print the test usage.
Definition at line 93 of file test_jma_multithread.cpp.