Japanese Morphological Analyzer: source/test/test_gen_posid_def.cpp File Reference
source/test/test_gen_posid_def.cpp File Reference
Test to generate "pos-id.def" from "*.csv" files in source directory of system dictionary.
#include <vector>
#include <set>
#include <iostream>
#include <fstream>
#include <string>
#include <cassert>
#include <cstdlib>
#include <dirent.h>
Functions
bool toLower (string &s)
string create_filename (const string &path, const string &file)
bool enum_csv_dictionaries (const char *path, vector< string > &dics)
string::size_type findSeparator (const string &str, size_t n)
Find the index of the nth separator "," in string.
bool extractPOS (const vector< string > &dics, set< string > &posSet, size_t posColumn)
Extract POS string from "*.csv" files.
void printUsage ()
Print the test usage.
int main (int argc, char *argv[])
Main function.
Detailed Description
Test to generate "pos-id.def" from "*.csv" files in source directory of system dictionary.
Below is the usage examples:
 "pos-id.def" defines POS index number for each POS string, which appears in "*.csv" files in source directory of system dictionary.
 Below is an example of generating "pos-id.def", which was then moved into source directory as a definition file for POS index number.
 $ ./jma_gen_posid_def ../db/unidic/src pos-id.def
 how many POS columns in *.csv files? (input 4 as there are four columns as POS category strings)
 $ mv pos-id.def ../db/unidic/src/
Author:
Jun Jiang
Version:
0.1
Date:
Jun 29, 2009
Definition in file test_gen_posid_def.cpp.
Function Documentation
string create_filename (const string & path, const string & file)
Definition at line 51 of file test_gen_posid_def.cpp.
Referenced by enum_csv_dictionaries().
bool enum_csv_dictionaries (const char * path, vector< string > & dics)
Definition at line 63 of file test_gen_posid_def.cpp.
References create_filename(), and toLower().
Referenced by main().
bool extractPOS (const vector< string > & dics, set< string > & posSet, size_t posColumn)
Extract POS string from "*.csv" files.
Parameters:
dics the file names of "*.csv"
posSet the extraction result
posColumn the number of POS columns in "*.csv"
Returns:
true for succeed in POS string extraction, false for failure.
Definition at line 157 of file test_gen_posid_def.cpp.
References findSeparator().
Referenced by main().
string::size_type findSeparator (const string & str, size_t n)
Find the index of the nth separator "," in string.
Parameters:
str string value to find
n count of separator, starting from 1
Returns:
the separator index, string::npos means no result found.
Definition at line 110 of file test_gen_posid_def.cpp.
Referenced by extractPOS().
int main (int argc, char * argv[])
Main function.
Definition at line 212 of file test_gen_posid_def.cpp.
References enum_csv_dictionaries(), extractPOS(), and printUsage().
void printUsage ()
Print the test usage.
Definition at line 204 of file test_gen_posid_def.cpp.
bool toLower (string & s)
Definition at line 36 of file test_gen_posid_def.cpp.
References c.