Japanese Morphological Analyzer: source/test/test_jma_convert_kana.cpp File Reference
source/test/test_jma_convert_kana.cpp File Reference
Test to convert Japanese Hiragana and Katakana characters.
#include "jma_factory.h"
#include "analyzer.h"
#include "knowledge.h"
#include "test_jma_common.h"
#include <string>
#include <iostream>
#include <cassert>
#include <cstdlib>
Functions
void printUsage ()
Print the test usage.
int main (int argc, char *argv[])
Main function.
Detailed Description
Test to convert Japanese Hiragana and Katakana characters.
Below is the usage examples:
 Test to create and use JMA_Factory.
 $ ./test_jma_convert_kana --to [hira|kata] [--dict DICT_PATH]
Author:
Jun Jiang
Version:
0.1
Date:
Feb 10, 2010
Definition in file test_jma_convert_kana.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function.
Definition at line 47 of file test_jma_convert_kana.cpp.
References jma::Analyzer::convertToHiragana(), jma::Analyzer::convertToKatakana(), jma::JMA_Factory::createAnalyzer(), jma::JMA_Factory::createKnowledge(), jma::Knowledge::loadDict(), printUsage(), jma::Knowledge::setEncodeType(), jma::Analyzer::setKnowledge(), jma::Knowledge::setSystemDict(), and TEST_JMA_DEFAULT_SYSTEM_DICT.
void printUsage ()
Print the test usage.
Definition at line 39 of file test_jma_convert_kana.cpp.