Japanese Morphological Analyzer: source/test/test_encode_sysdict.cpp File Reference
source/test/test_encode_sysdict.cpp File Reference
Test for encoding the system dictionary from text type to binary type.
#include "jma_factory.h"
#include "knowledge.h"
#include <iostream>
#include <cassert>
#include <cstdlib>
#include <string.h>
Functions
void printUsage ()
Print the test usage.
int main (int argc, char *argv[])
Main function.
Detailed Description
Test for encoding the system dictionary from text type to binary type.
Below is the usage examples:
 The encoding type of those CSV files in source directory is predefined by the "dictionary-charset" entry of "dicrc" file.
 While the encoding type of binary files in destination directory could be set to "eucjp", "sjis" or "utf8" like below, which is "eucjp" defaultly.
 $ ./jma_encode_sysdict --encode eucjp ../db/jumandic/src ../db/jumandic/bin_eucjp
 $ ./jma_encode_sysdict --encode sjis ../db/jumandic/src ../db/jumandic/bin_sjis
 $ ./jma_encode_sysdict --encode utf8 ../db/jumandic/src ../db/jumandic/bin_utf8
Author:
Jun Jiang
Version:
0.1
Date:
Jun 22, 2009
Definition in file test_encode_sysdict.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function.
Definition at line 40 of file test_encode_sysdict.cpp.
References jma::JMA_Factory::createKnowledge(), jma::Knowledge::encodeSystemDict(), printUsage(), and jma::Knowledge::setEncodeType().
void printUsage ()
Print the test usage.
Definition at line 31 of file test_encode_sysdict.cpp.
Referenced by main().