Japanese Morphological Analyzer: source/test/test_jma_analyzer.cpp File Reference
source/test/test_jma_analyzer.cpp File Reference
Test to create an instance of JMA_Analyzer.
#include "jma_knowledge.h"
#include "mecab.h"
#include "jma_analyzer.h"
#include "test_jma_common.h"
#include <iostream>
#include <cassert>
#include <stdlib.h>
Functions
int main ()
Main function.
Detailed Description
Test to create an instance of JMA_Analyzer.
Below is the usage examples:
 Test to create and use Knowledge.
 $./test_jma_analyzer
Author:
Vernin
Version:
0.1
Date:
Jun 23, 2009
Definition in file test_jma_analyzer.cpp.
Function Documentation
int main ()
Main function.
Definition at line 28 of file test_jma_analyzer.cpp.
References jma::Knowledge::addUserDict(), jma::Sentence::getBaseForm(), jma::Sentence::getCount(), jma::Sentence::getLexicon(), jma::Sentence::getListSize(), jma::Sentence::getScore(), jma::Sentence::getStrPOS(), jma::JMA_Knowledge::loadDict(), jma::JMA_Analyzer::runWithSentence(), jma::JMA_Analyzer::runWithString(), jma::JMA_Analyzer::setKnowledge(), jma::Analyzer::setOption(), jma::Sentence::setString(), jma::Knowledge::setSystemDict(), TEST_JMA_DEFAULT_SYSTEM_DICT, TEST_JMA_DEFAULT_USER_DICT_CSV, and TEST_JMA_DEFAULT_USER_DICT_TXT.