Japanese Morphological Analyzer: source/test/test_jma_pos_nbest.cpp File Reference
source/test/test_jma_pos_nbest.cpp File Reference
Test JMA in Japanese word segmentation with POS tagging analysis, and output the n-best result.
#include "jma_factory.h"
#include "analyzer.h"
#include "knowledge.h"
#include "sentence.h"
#include <iostream>
#include <fstream>
#include <cassert>
#include <string>
#include <vector>
#include <ctime>
#include <string.h>
#include <stdlib.h>
Functions
void testWithSentence (Analyzer &analyzer, const string &str, ofstream &output)
Analyze a sentence.
void testWithStream (Analyzer &analyzer, const char *source, const char *dest)
Analyze a stream.
void printUsage ()
Print the test usage.
int main (int argc, char *argv[])
Main function.
Detailed Description
Test JMA in Japanese word segmentation with POS tagging analysis, and output the n-best result.
Below is the usage examples: The "DICT_PATH" in below examples is the dictionary path.
 To analyze the raw input file "INPUT", and print the n-best result to "OUTPUT".
 (the example of the parameters below could be:
 DICT_PATH: ../db/jumandic/bin_eucjp
 INPUT: ../db/test/asahi_test_raw_eucjp.txt
 )
 $ ./jma_pos_nbest --dict DICT_PATH --nbest N INPUT OUTPUT
 The output format for each sentence is defined below:
 k (int, the number of candidates for the sentence)
 prob1 (double, the probability of this candidate)  word1/pos1  word2/pos2  ...
 prob2  word1/pos1  word2/pos2  ...
 ...
Author:
Jun Jiang
Version:
0.1
Date:
Aug 12, 2009
Definition in file test_jma_pos_nbest.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function.
Definition at line 131 of file test_jma_pos_nbest.cpp.
References pthread_t_data::analyzer, jma::JMA_Factory::createAnalyzer(), jma::JMA_Factory::createKnowledge(), jma::Knowledge::loadDict(), printUsage(), jma::Knowledge::setEncodeType(), jma::Analyzer::setKnowledge(), jma::Analyzer::setOption(), jma::Knowledge::setSystemDict(), and testWithStream().
void printUsage ()
Print the test usage.
Definition at line 123 of file test_jma_pos_nbest.cpp.
void testWithSentence (Analyzer & analyzer, const string & str, ofstream & output)
Analyze a sentence.
Definition at line 47 of file test_jma_pos_nbest.cpp.
References jma::Analyzer::getPOSDelimiter(), jma::Analyzer::getWordDelimiter(), and jma::Analyzer::runWithSentence().
Referenced by main(), and testWithStream().
void testWithStream (Analyzer & analyzer, const char * source, const char * dest)
Analyze a stream.
Definition at line 94 of file test_jma_pos_nbest.cpp.
References testWithSentence().
Referenced by main().