Japanese Morphological Analyzer: source/test/test_jma_knowledge.cpp File Reference
source/test/test_jma_knowledge.cpp File Reference
Test to create an instance of JMA_Knowledge.
#include "jma_knowledge.h"
#include "mecab.h"
#include "test_jma_common.h"
#include <iostream>
#include <cassert>
#include <stdlib.h>
Functions
int main ()
Main function.
Detailed Description
Test to create an instance of JMA_Knowledge.
Below is the usage examples:
 Test to create and use JMA_Knowledge.
 $./test_jma_knowledge
Author:
Jun Jiang
Version:
0.1
Date:
Jun 18, 2009
Definition in file test_jma_knowledge.cpp.
Function Documentation
int main ()
Main function.
Definition at line 28 of file test_jma_knowledge.cpp.
References jma::Knowledge::addUserDict(), jma::JMA_Knowledge::createTagger(), jma::JMA_Knowledge::isSentenceSeparator(), jma::JMA_Knowledge::isStopWord(), jma::JMA_Knowledge::loadDict(), jma::JMA_Knowledge::loadSentenceSeparatorConfig(), jma::JMA_Knowledge::loadStopWordDict(), jma::Knowledge::setSystemDict(), TEST_JMA_DEFAULT_SENTENCE_CONFIG, TEST_JMA_DEFAULT_STOPWORD_DICT, TEST_JMA_DEFAULT_SYSTEM_DICT, and TEST_JMA_DEFAULT_USER_DICT_CSV.