Japanese Morphological Analyzer: source/test/test_jma_stopword.cpp File Reference
source/test/test_jma_stopword.cpp File Reference
Test to filter stop word.
#include "ijma.h"
#include "test_jma_common.h"
#include <vector>
#include <string>
#include <iostream>
#include <cassert>
#include <cstdlib>
#include <cstring>
Functions
void printUsage ()
Print the test usage.
int main (int argc, char *argv[])
Main function.
Detailed Description
Test to filter stop word.
Below is the usage examples:
 Specify stop word file by command option "--stop":
 $ ./test_jma_stopword [--stop STOPWORD_PATH] [--dict DICT_PATH]
Author:
Jun Jiang
Version:
0.1
Date:
Sep 08, 2010
Definition in file test_jma_stopword.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function.
Definition at line 38 of file test_jma_stopword.cpp.
References jma::JMA_Factory::createAnalyzer(), jma::JMA_Factory::createKnowledge(), jma::Sentence::getCount(), jma::Knowledge::getEncodeType(), jma::Sentence::getLexicon(), jma::Sentence::getOneBestIndex(), jma::Sentence::getStrPOS(), jma::Knowledge::loadDict(), jma::Knowledge::loadStopWordDict(), printUsage(), jma::Analyzer::runWithSentence(), jma::Analyzer::setKnowledge(), jma::Sentence::setString(), jma::Knowledge::setSystemDict(), TEST_JMA_DEFAULT_STOPWORD_DICT, and TEST_JMA_DEFAULT_SYSTEM_DICT.
void printUsage ()
Print the test usage.
Definition at line 30 of file test_jma_stopword.cpp.