Japanese Morphological Analyzer: source/test/test_jma_split_sentence.cpp File Reference
source/test/test_jma_split_sentence.cpp File Reference
Test sentence split in JMA analysis.
#include "ijma.h"
#include "test_jma_common.h"
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <cassert>
#include <cstdlib>
#include <cstring>
Functions
int main (int argc, char *argv[])
Main function.
Detailed Description
Test sentence split in JMA analysis.
Below is the usage examples to split the sentences from "INPUT" to "OUTPUT" with each sentence in one line, the "DICT_PATH" is the dictionary path, which is "../db/ipadic/bin_eucjp" defautly.
 The character encoding of "INPUT" should be the same to that of "DICT_PATH"
 $./jma_split_sentence INPUT OUTPUT [--dict DICT_PATH]
Author:
Jun Jiang
Version:
0.1
Date:
Jul 27, 2009
Definition in file test_jma_split_sentence.cpp.
Function Documentation
int main (int argc, char * argv[])
Main function.
Definition at line 60 of file test_jma_split_sentence.cpp.
References jma::JMA_Factory::createAnalyzer(), jma::JMA_Factory::createKnowledge(), jma::Knowledge::getEncodeType(), jma::Knowledge::loadDict(), printUsage(), jma::Analyzer::setKnowledge(), jma::Knowledge::setSystemDict(), jma::Analyzer::splitSentence(), and TEST_JMA_DEFAULT_SYSTEM_DICT.