Japanese Morphological Analyzer: source/unit_test/unittest_jma_analyzer.cpp File Reference
source/unit_test/unittest_jma_analyzer.cpp File Reference
Unit test of class JMA_Analyzer.
#include <gtest/gtest.h>
#include <jma_analyzer.h>
#include <jma_knowledge.h>
#include "../../test/test_jma_common.h"
#include "../../include/file_utils.h"
#include <vector>
#include <string>
#include <iostream>
#include <fstream>
Classes
class JMA_AnalyzerTest
Functions
TEST_F (JMA_AnalyzerTest, setKnowledgeFail)
TEST_F (JMA_AnalyzerTest, runWithString)
TEST_F (JMA_AnalyzerTest, runWithSentence)
TEST_F (JMA_AnalyzerTest, loadMultipleKnowledge)
TEST_F (JMA_AnalyzerTest, multipleAnalyzer)
TEST_F (JMA_AnalyzerTest, runWithStreamFail)
TEST_F (JMA_AnalyzerTest, runWithStream)
TEST_F (JMA_AnalyzerTest, splitSentence)
TEST_F (JMA_AnalyzerTest, convertCharacters)
TEST_F (JMA_AnalyzerTest, nbest)
TEST_F (JMA_AnalyzerTest, posFormatNone)
TEST_F (JMA_AnalyzerTest, posFormatAlphabet)
TEST_F (JMA_AnalyzerTest, posFormatFull)
TEST_F (JMA_AnalyzerTest, compoundNotCombine)
TEST_F (JMA_AnalyzerTest, userNounDecompose)
Detailed Description
Unit test of class JMA_Analyzer.
Author:
Jun Jiang
Version:
0.1
Date:
Sep 14, 2010
Definition in file unittest_jma_analyzer.cpp.
Function Documentation
TEST_F (JMA_AnalyzerTest , userNounDecompose)
Definition at line 318 of file unittest_jma_analyzer.cpp.
TEST_F (JMA_AnalyzerTest , compoundNotCombine)
Definition at line 311 of file unittest_jma_analyzer.cpp.
TEST_F (JMA_AnalyzerTest , posFormatFull)
Definition at line 282 of file unittest_jma_analyzer.cpp.
References jma::removeFile().
TEST_F (JMA_AnalyzerTest , posFormatAlphabet)
Definition at line 253 of file unittest_jma_analyzer.cpp.
References jma::removeFile().
TEST_F (JMA_AnalyzerTest , posFormatNone)
Definition at line 230 of file unittest_jma_analyzer.cpp.
References jma::removeFile().
TEST_F (JMA_AnalyzerTest , nbest)
Definition at line 216 of file unittest_jma_analyzer.cpp.
TEST_F (JMA_AnalyzerTest , convertCharacters)
Definition at line 201 of file unittest_jma_analyzer.cpp.
TEST_F (JMA_AnalyzerTest , splitSentence)
Definition at line 186 of file unittest_jma_analyzer.cpp.
TEST_F (JMA_AnalyzerTest , runWithStream)
Definition at line 168 of file unittest_jma_analyzer.cpp.
References jma::removeFile().
TEST_F (JMA_AnalyzerTest , runWithStreamFail)
Definition at line 163 of file unittest_jma_analyzer.cpp.
TEST_F (JMA_AnalyzerTest , multipleAnalyzer)
Definition at line 146 of file unittest_jma_analyzer.cpp.
References jma::JMA_Analyzer::setKnowledge().
TEST_F (JMA_AnalyzerTest , loadMultipleKnowledge)
Definition at line 128 of file unittest_jma_analyzer.cpp.
References TEST_JMA_DEFAULT_SYSTEM_DICT.
TEST_F (JMA_AnalyzerTest , runWithSentence)
Definition at line 124 of file unittest_jma_analyzer.cpp.
TEST_F (JMA_AnalyzerTest , runWithString)
Definition at line 118 of file unittest_jma_analyzer.cpp.
TEST_F (JMA_AnalyzerTest , setKnowledgeFail)
Definition at line 112 of file unittest_jma_analyzer.cpp.