Japanese Morphological Analyzer: source/unit_test/unittest_sentence.cpp File Reference
source/unit_test/unittest_sentence.cpp File Reference
Unit test of class Sentence.
#include <gtest/gtest.h>
#include <sentence.h>
#include <algorithm>
Functions
TEST (SentenceTest, morphemeDefault)
TEST (SentenceTest, getDefault)
TEST (SentenceTest, getValue)
Detailed Description
Unit test of class Sentence.
Author:
Jun Jiang
Version:
0.1
Date:
Sep 10, 2010
Definition in file unittest_sentence.cpp.
Function Documentation
TEST (SentenceTest , getValue)
Definition at line 35 of file unittest_sentence.cpp.
References jma::Sentence::addList(), jma::Sentence::getBaseForm(), jma::Sentence::getCount(), jma::Sentence::getLexicon(), jma::Sentence::getListSize(), jma::Sentence::getNormForm(), jma::Sentence::getOneBestIndex(), jma::Sentence::getPOS(), jma::Sentence::getReadForm(), jma::Sentence::getScore(), jma::Sentence::getStrPOS(), and jma::Sentence::setScore().
TEST (SentenceTest , getDefault)
Definition at line 27 of file unittest_sentence.cpp.
References jma::Sentence::getListSize(), jma::Sentence::getOneBestIndex(), and jma::Sentence::getString().
TEST (SentenceTest , morphemeDefault)
Definition at line 16 of file unittest_sentence.cpp.
References jma::Morpheme::baseForm_, jma::Morpheme::lexicon_, jma::Morpheme::normForm_, jma::Morpheme::posCode_, jma::Morpheme::posStr_, and jma::Morpheme::readForm_.